feat(docs): How does telemetry data collection work
iotaledger/iota pull request #1000
Opened 2024-07-04 12:59 UTC by samuel-rufi

# Description

Documents how telemetry/data collection/monitoring works with the node sofware.

 Crates that are to document:
- [X] iota-telemetry
- [X] telemetry-subscribers
- [X] mysten-metrics

# Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/801

## Type of change

- Documentation

2024-07-08 11:40 UTC, lzpap requested changes
Hi @samuel-rufi , let's add these docs to the actual docs site. You'll need to edit `docs/content/sidebars/concepts.js` to make these topic discoverable (and to add the titles to the sidebar)

2024-07-09 15:22 UTC, lucas-tortora requested changes

2024-07-09 20:18 UTC, lucas-tortora submitted a review, later dismissed

2024-07-12 12:40 UTC, Thoralf-M submitted a review, later dismissed

2024-07-16 10:35 UTC, lzpap reviewed
@samuel-rufi pls commit the changes, it will update the sidebar headers

2024-07-16 14:14 UTC, kodemartin reviewed
Looks good @samuel-rufi , found a few typos, and made a couple of minor suggestions.

2024-07-16 19:46 UTC, lzpap submitted a review, later dismissed

2024-07-18 09:16 UTC, Thoralf-M approved these changes

2024-07-18 09:18 UTC, lzpap approved these changes

2024-07-22 08:04 UTC, kodemartin approved these changes

2024-07-22 12:43 UTC, Dr-Electron approved these changes

2024-07-22 12:47 UTC, merged