refactor(iota-framework/timelock): Split `timelock` package into framework and system
iotaledger/iota pull request #1030
Opened 2024-07-06 11:07 UTC by miker83z

# Description of change

The main change introduced by this PR is the refactor of the `timelock` package. 
Following [this comment](https://github.com/iotaledger/iota/issues/987#issuecomment-2208264314), but also previous discussions when the `TimeLock` was designed, the package has been split in half and moved to `iota-framework` and `iota-system`:
- `labeler.move` and `timelock.move` (and related tests) were moved to `iota-framework`
- `timelocked_staking.move` was moved to `iota-system`
- `stardust_upgrade_label` was moved to `stardust`

Moreover:
- `timelock_balance.move` was integrated into `timelock.move` so that crucial functions such as `pack` and `unpack` could become private instead of `public(package)`; in fact, in my opinion this prevents a possible "illegal" use of such functions in some `iota-framework` modules in the future; this was not the case when `timelock` was a standalone package.
- `timelocked_staked_iota.move` was integrated into `timelocked_staking.move` for the same reason. 

Key change:
- A capability mechanism was added so that the `iota-system` modules are the only ones able to invoke the TimeLock priviledged functions `pack` and `unpack`.
- This is implemented through the use of a `iota::timelock::SystemTimelockCap` that must be created at genesis; `iota_system::genesis::create`, then, adds this cap as a `IotaSystemState` dynamic field.
- This cap is used to invoke 2 new public functions `iota::timelock::system_pack` and `iota::timelock::system_unpack`.
- All the other functionalities of timelock and timelocked_staking are left untouched

Minor change propedeutic to the next PR related to the genesis staking and useful to test the new integration of `timelocked_staking` into `iota_system`:
- `iota_system::validator::request_add_timelocked_stake_at_genesis_internal` was introduced in order to create a `staked_iota` and not transfer it, but return it at the end of the function
- This is then used by a new function `iota_system::timelocked_staking::request_add_stake_at_genesis` that can be called by `iota_system::genesis::create` (this last step will be implemented with a future PR).     
- Check commit 512243d677

## Links to any relevant issues

Fixes #1002 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

`cargo check`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-07-08 15:46 UTC, kodemartin requested changes
Hey @miker83z looks good in general. I left a couple of suggestions not of critical nature.

Plus, you have to remove the `run_timelocks_tests` from `iota_framework_tests::unit_tests.`

2024-07-09 08:12 UTC, kodemartin approved these changes

2024-07-09 12:56 UTC, lzpap approved these changes
LGTM, only nits which I let you decide what to do with.

2024-07-10 09:22 UTC, lzpap requested changes
The framework snapshot still contains the bytecode for the timelock package, which makes tests fail.

2024-07-10 10:24 UTC, lzpap approved these changes

2024-07-10 10:27 UTC, merged