feat(wallet): Initialize Account Finder with existing accounts
iotaledger/iota pull request #1082
Opened 2024-07-09 12:02 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/842
Depends on https://github.com/iotaledger/iota/pull/1075

2024-07-09 13:43 UTC, panteleymonchuk approved these changes

2024-07-10 08:21 UTC, panteleymonchuk submitted a review, later dismissed

2024-07-10 15:32 UTC, panteleymonchuk submitted a review, later dismissed

2024-07-11 07:46 UTC, begonaalvarezd requested changes
We are spamming the node with balance requests of all found accounts 🙏🏼 we shouldnt be polling balances, the balance comes from the balance finder and the is no need to keep fetching them

2024-07-11 08:12 UTC, panteleymonchuk submitted a review, later dismissed

2024-07-11 08:54 UTC, panteleymonchuk approved these changes

2024-07-11 08:56 UTC, begonaalvarezd approved these changes
🚀

2024-07-11 09:16 UTC, merged