refactor(iota-genesis-builder): Adapt `TokenAllocation` to support timelocks
iotaledger/iota pull request #1105
Opened 2024-07-09 18:00 UTC by miker83z

# Description of change

This PR refactors `TokenAllocation` on the rust side to support timelock informations for the staking. 

The main change was removing `TimelockAllocation` and adding `staked_with_timelock` to `TokenAllocation`. Then all objects manipulations were adapted to support this change.

Additionally, a new PTB was created to split TimeLock objects (`split_timelocks`) in `iota_genesis_builder/lib.rs`.  

[edit] The code in this PR does not allow to build a genesis blob, #1130 fixes this. 

## Links to any relevant issues

Fixes #1003 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

`cargo check`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-07-10 14:34 UTC, lucas-tortora approved these changes

2024-07-11 10:24 UTC, lzpap approved these changes

2024-07-11 10:29 UTC, samuel-rufi requested changes

2024-07-11 10:30 UTC, kodemartin requested changes
Hey @miker83z, looks good in general. Left a few comments that need your attention.

2024-07-11 12:47 UTC, kodemartin approved these changes

2024-07-11 13:11 UTC, merged