fix(CI): Fix cargo deny
iotaledger/iota pull request #1106
Opened 2024-07-09 18:43 UTC by DaughterOfMars

# Description of change

This PR fixes the errors in the cargo deny CI by updating various out of date dependencies with audit issues.

## Weirdness
Some changes were made because dependencies are out-of-date, non-update-able, and have out-of-date sub-dependencies that cause build errors for us due to mismatching versions. 

For instance, in [crates/iota-node/src/lib.rs](https://github.com/iotaledger/iota/pull/1106/files/d32671d4b1e07fda9302a3af7f629159b1900520#diff-d94fd2d86704496015150596e6ae71b6b1097787db739ccd27b4a76d27c045d0) I have had to copy the functionality from the `fastcrypto` crate because that library uses an older version of `reqwest`, and the public API accepts a `reqwest::Client`. If we tried to use the provided `fetch_jwks` function then we would have a compilation error due to the different versions of that type.

Similarly for [crates/iota-tls/src/acceptor.rs](https://github.com/iotaledger/iota/pull/1106/files/d32671d4b1e07fda9302a3af7f629159b1900520#diff-ebd1fe9d226402047ddd63c87333cb397dde3d5fc85c7449ca395dd09489f729), the functionality of the `RustlsAcceptor` from `axum_server` was copied to avoid version conflicts with `rustls`.

These could be resolved in some cases by forking the dependency and updating the sub-dependencies.

## Links to any relevant issues

Fixes #805

2024-07-17 10:54 UTC, miker83z requested changes
LGTM! 
Maybe only the external-crate/move-package test baseline could be update to make the CI work again for that?

2024-07-17 13:22 UTC, miker83z submitted a review, later dismissed

2024-07-19 15:40 UTC, miker83z submitted a review, later dismissed

2024-07-24 13:57 UTC, Thoralf-M approved these changes

2024-07-25 14:07 UTC, Thoralf-M approved these changes

2024-07-25 17:42 UTC, thibault-martinez approved these changes

2024-07-25 19:36 UTC, Dr-Electron approved these changes
Just here to approve the workflow changes ;)
Out of interest, do we have a formatter for yml files now? Is it dprint?
And why use double quotes if you can save space and just use a single one? :trollface:

2024-07-26 07:56 UTC, miker83z approved these changes

2024-07-26 08:22 UTC, merged