feat(apps-ui-kit): add address component
iotaledger/iota pull request #1138
Opened 2024-07-11 13:23 UTC by brancoder

# Description of change

Adds address  component to ui kit

## Links to any relevant issues

resolves #874 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-07-11 14:22 UTC, evavirseda requested changes
some comments :pray:

2024-07-12 07:18 UTC, evavirseda submitted a review, later dismissed

2024-07-12 11:21 UTC, evavirseda approved these changes

2024-07-15 08:35 UTC, panteleymonchuk approved these changes

2024-07-15 08:58 UTC, merged