fix(genesis-ceremony): Update Genesis Ceremony docs
iotaledger/iota pull request #1150
Opened 2024-07-12 08:55 UTC by Thoralf-M

# Description of change

Update Genesis Ceremony docs and fix typo

https://github.com/iotaledger/iota/issues/1056

## Type of change

- Documentation Fix

## How the change has been tested

Running the commands

2024-07-24 10:00 UTC, Alex6323 approved these changes

2024-07-24 12:27 UTC, thibault-martinez requested changes
conflicts

2024-07-24 13:43 UTC, DaughterOfMars approved these changes

2024-07-24 13:50 UTC, kodemartin approved these changes
lgtm

2024-07-30 13:45 UTC, thibault-martinez approved these changes

2024-07-30 14:27 UTC, merged