feat(wallet): Support `Ledger` in Accounts Finder
iotaledger/iota pull request #1175
Opened 2024-07-16 09:27 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/1149

2024-07-17 16:19 UTC, begonaalvarezd requested changes
Something is off with the search algorith, when you run search again, it repeats the same bip paths it searched before

2024-07-18 12:08 UTC, panteleymonchuk submitted a review, later dismissed
Tested with ledger emulator (macbook).
Everything works properly.

2024-07-18 13:22 UTC, begonaalvarezd approved these changes
🚀 works, great job

2024-07-18 14:05 UTC, panteleymonchuk approved these changes

2024-07-18 14:47 UTC, merged