feat: get rid of TOTAL_SUPPLY_NANOS
iotaledger/iota pull request #1179
Opened 2024-07-16 10:42 UTC by valeriyr

# Description of change

Since the inflation mechanism is implemented TOTAL_IOTA_SUPPLY should be considered as a legacy constant which is valid only for the migration supply.

## Links to any relevant issues

fixes #1171

2024-07-18 07:38 UTC, miker83z requested changes
LGTM! 
I left just 2 comments for minor changes.

2024-07-18 07:44 UTC, PhilippGackstatter submitted a review, later dismissed
LGTM!

2024-07-18 08:26 UTC, kodemartin reviewed
Hey @valeriyr looks good in general. Left a couple of non-critical suggestions.

2024-07-18 10:19 UTC, kodemartin submitted a review, later dismissed

2024-07-19 07:20 UTC, miker83z submitted a review, later dismissed

2024-07-23 08:15 UTC, Dkwcs approved these changes

2024-07-23 08:19 UTC, PhilippGackstatter approved these changes

2024-07-23 08:43 UTC, lzpap approved these changes

2024-07-23 08:45 UTC, kodemartin approved these changes

2024-07-23 08:45 UTC, merged