fix(iota-core): Fix CI after inflation introduction
iotaledger/iota pull request #1196
Opened 2024-07-17 05:30 UTC by Dkwcs

# Description of change

Fixing non_refundable_storage_fee related tests(iota-core)
Cargo clippy, fmt 

## Links to any relevant issues

Fixes #1173 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Run iota-core tests

2024-07-18 07:50 UTC, miker83z requested changes
Just 1 suggestion

2024-07-18 07:54 UTC, PhilippGackstatter approved these changes

2024-07-18 08:19 UTC, valeriyr requested changes
Seems like the following tests are also broken because of `non_refundable_storage_fee` and need to be fixed:
https://github.com/iotaledger/iota/actions/runs/9980954811/job/27583523851?pr=1196

2024-07-19 07:29 UTC, miker83z approved these changes

2024-07-19 11:11 UTC, valeriyr requested changes
@miker83z, We are still checking the `graphql-rpc` CI. It seems to be ok but there some amount of changes in the snapshots.
I think we can create a separate issue for updating the test snapshots and not to block this PP.

2024-07-19 13:33 UTC, valeriyr approved these changes

2024-07-19 13:51 UTC, merged