feat(devx): excluded GraphQL from docs
iotaledger/iota pull request #1202
Opened 2024-07-17 13:16 UTC by lucas-tortora

# Description of change

* Commented out GraphQL docs from sidebars
* Added an `_` at the beginning of GraphQL docs so they aren't built

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-07-17 13:43 UTC, salaheldinsoliman requested changes
Why not remove the related files instead of commenting things out?

2024-07-17 14:25 UTC, salaheldinsoliman submitted a review, later dismissed

2024-07-17 17:11 UTC, salaheldinsoliman approved these changes

2024-07-18 11:36 UTC, fijter approved these changes

2024-07-18 12:09 UTC, merged