fix(devx): remove remaining mentions of Mysten Labs
iotaledger/iota pull request #1207
Opened 2024-07-17 20:07 UTC by lucas-tortora

# Description of change

Replaced straggling mentions of MystenLabs and associated websites.

## Links to any relevant issues

fixes https://github.com/iotaledger/devx/issues/469

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-07-18 11:34 UTC, fijter requested changes
Sorry for all the comments, there's a lot of dead links in here (only read the previous comments just now about hosting these urls, but I was indeed under the assumption we wanted to move all this internally into the docs). I think we have to strip out some more to simplify the docs - we might not need every PoC and example hosted and such.

2024-07-18 16:39 UTC, salaheldinsoliman requested changes
There is a screenshot in `Getting started/ IOTA Environment Setup` that mentions Sui:
<img width="710" alt="image" src="https://github.com/user-attachments/assets/41604e73-537f-474e-948b-ea28efefee23">

2024-07-22 15:32 UTC, Dr-Electron requested changes

2024-07-22 19:53 UTC, Dr-Electron submitted a review, later dismissed

2024-07-23 11:32 UTC, fijter submitted a review, later dismissed
Looks good now! :)

2024-07-23 14:31 UTC, fijter approved these changes

2024-07-23 14:37 UTC, salaheldinsoliman requested changes
In [this line](https://github.com/iotaledger/iota/blob/486ed240f98d9e9bc16f530f5e2fd49be903cd42/docs/content/developer/advanced/asset-tokenization.mdx#L16),
there is a mention of Sui: `This makes it a suitable choice for Solidity based use cases that one might want to implement on Sui.`

2024-07-23 16:17 UTC, salaheldinsoliman approved these changes

2024-07-23 22:13 UTC, merged