feat(ci): fix typos and add typos CI
iotaledger/iota pull request #1230
Opened 2024-07-19 12:30 UTC by thibault-martinez

2024-07-19 14:31 UTC, Thoralf-M submitted a review, later dismissed

2024-07-19 15:43 UTC, miker83z requested changes
iota-framework should be re-built: `cargo run --release --bin iota-framework-snapshot`

2024-07-22 07:34 UTC, Thoralf-M approved these changes

2024-07-22 08:10 UTC, miker83z approved these changes

2024-07-22 08:20 UTC, merged