fix(CI): Force clippy to run on the stable channel
iotaledger/iota pull request #1277
Opened 2024-07-22 18:58 UTC by DaughterOfMars

# Description of change

This just ensures that we run clippy on the stable channel, so we don't get inconsistent reporting from nightly-only lints.

2024-07-22 20:26 UTC, miker83z submitted a review, later dismissed

2024-07-23 07:07 UTC, Thoralf-M submitted a review, later dismissed

2024-07-23 07:55 UTC, thibault-martinez submitted a review, later dismissed

2024-07-23 08:15 UTC, lzpap requested changes
What we uncovered yesterday is that https://github.com/iotaledger/iota/pull/917 introduced new lint headers that do not work well with some clippy versions on some runners. Take a look at [this run for example](https://github.com/iotaledger/iota/actions/runs/9942349320/job/27463701122):
 - clippy is added via rustup, and the job says: `info: component 'clippy' for target 'x86_64-unknown-linux-gnu' is up to date`
 - clippy doesn't know the `#[allow(clippy::const_is_empty)]` lint and the job fails

The `unknown` lints were added in the latest clippy release ([release notes](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#new-lints)), so it seems that some runners don't have the newest clippy version.
 - either we remove these new lints from the code, or
 - make sure that every runner has updated clippy. @shufps could you help with that? 
 
Until the issue is resolved we should not merge this PR.

2024-07-23 12:01 UTC, lzpap reviewed
> We should remove them, but that makes me confused about why the CI passed for this PR.

Because you got a runner that has the updated one. [This one](https://github.com/iotaledger/iota/actions/runs/10058091033/job/27800610587?pr=1172) got a runner that was not.

2024-07-23 13:16 UTC, thibault-martinez approved these changes

2024-07-23 13:21 UTC, Thoralf-M approved these changes

2024-07-23 14:43 UTC, lzpap approved these changes

2024-07-23 15:15 UTC, merged