fix(iota-genesis-builder): Add native tokens to bag with the proper key
iotaledger/iota pull request #1462
Opened 2024-07-26 13:54 UTC by miker83z

# Description of change

Fixes #1461 
This created unexpected behaviors during Stardust native tokens claiming. 
Stardust objects snapshots need to be regenerated after this.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo run --release --bin iota-genesis-builder -- --disable-global-snapshot-verification iota --snapshot-path ../test-latest-full_snapshot-iota.bin --target-network alphanetv0`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-07-26 15:58 UTC, lzpap approved these changes

2024-07-26 19:25 UTC, Thoralf-M approved these changes

2024-07-29 07:43 UTC, kodemartin requested changes
Hey @miker83z , have you considered modifying the claim utility function on the Move side instead? We could avoid altering the a part of the code that is already correct (indeed [tests are failing](https://github.com/iotaledger/iota/actions/runs/10116084634/job/27978179594?pr=1462)), and  the need to regenerate the snapshots.

If we must change the logic in the `genesis-builder` I would suggest to use the `ObjectID::to_canonical_string` method in `FoundryLedgerData.canonical_coin_type` to format the package id. That is instead of the new `with_no_prefix` function.

2024-07-29 13:58 UTC, Dkwcs approved these changes

2024-07-29 15:45 UTC, kodemartin approved these changes

2024-07-29 15:47 UTC, merged