feat(docs/examples): nft output extraction example based on sdk
iotaledger/iota pull request #1478
Opened 2024-07-29 09:44 UTC by Dkwcs

# Description of change

This PR adds an example for claiming a NFT Output assets.

## Links to any relevant issues

Fixes #1326. 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Setup a iota-test-validator network and then
`cargo run --example nft_output`

2024-07-29 14:45 UTC, Thoralf-M approved these changes

2024-07-29 15:15 UTC, DaughterOfMars requested changes
Clippy is failing

2024-07-30 15:25 UTC, miker83z requested changes
The flow seems correct but I couldn't test it because it seems it needs to be updated to the latest objects snapshot.

Pls, also rebase and move it to `docs/examples`

2024-07-31 14:21 UTC, miker83z approved these changes
Just the last change below!

2024-07-31 14:35 UTC, valeriyr approved these changes

2024-07-31 14:59 UTC, merged