chore(iota-json-rpc): Refactor some utility code
iotaledger/iota pull request #1489
Opened 2024-07-29 15:54 UTC by DaughterOfMars

# Description of change

This PR adds a trait to clean up some utility code.

## Motivation

The existing code is not super flexible, and a trait impl helps to clean it up and also allow easy extensibility.

2024-07-30 13:14 UTC, Thoralf-M approved these changes

2024-08-16 08:48 UTC, samuel-rufi approved these changes
Nice one!

2024-08-16 09:28 UTC, thibault-martinez requested changes
temporarily preventing this from being merged

2024-09-02 11:16 UTC, thibault-martinez approved these changes

2024-09-02 11:33 UTC, merged