docs(advanced-topics): Refactor `advanced-topics`
iotaledger/iota pull request #1491
Opened 2024-07-29 19:02 UTC by samuel-rufi

# Description of change

Refactors the `advanced-topics`:
- removes unnecessary files, updating the sidebar
- improves the wording in the `asset-tokenization` doc
- hosts  the missing `asset-tokenization` package including its `template` code as an example
- makes it Move 2024 compatible
- removes the WASM/Typescript references

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/1295

## Type of change

- Documentation Fix

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-07-30 09:16 UTC, Dr-Electron requested changes
We aligned on using `IOTA`

2024-07-30 12:16 UTC, lucas-tortora approved these changes

2024-07-31 08:48 UTC, lzpap requested changes
hey @samuel-rufi , please move the `Stardust On Move` section out from the advanced topics. It belongs to the `Stardust Migration` topic, more precisely just copy it over to the `Migration Process` page inside `Stardust Migration`. There is already some content (taken from exactly this page) but IMO we could just copy this whole page into the `Migration Process` page.

2024-07-31 15:03 UTC, lzpap approved these changes

2024-08-01 07:31 UTC, Dr-Electron approved these changes

2024-08-01 07:33 UTC, merged