feat(apps-ui-kit): add Table component
iotaledger/iota pull request #1536
Opened 2024-07-31 14:40 UTC by brancoder

# Description of change

Adds table component

## Links to any relevant issues

fixes issue #895 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-08-02 15:07 UTC, panteleymonchuk approved these changes

2024-08-05 11:15 UTC, evavirseda requested changes

2024-08-06 12:16 UTC, VmMad requested changes

2024-08-06 14:44 UTC, VmMad requested changes

2024-08-07 13:26 UTC, panteleymonchuk approved these changes
All looks good to me. Approved with a few minor comments.

2024-08-07 13:36 UTC, evavirseda approved these changes
LGTM :rocket:

2024-08-07 13:38 UTC, VmMad approved these changes

2024-08-07 13:41 UTC, merged