feat(docs/examples): add unlock condition example based on rust sdk
iotaledger/iota pull request #1559
Opened 2024-08-01 12:17 UTC by Dkwcs

# Description of change

Demonstration on how to claim the assets from nft_output owned by alias_output with unlock conditions.

## Links to any relevant issues

Fixes #1328 .

## Type of change

Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Run:

`cargo run --example address_unlock_condition
`

2024-08-02 15:10 UTC, miker83z requested changes
Great example! I left some comments to fix the inline comments and a add possibly a new function. 
Pls, run cargo fmt again after writing down the comments.

2024-08-05 07:50 UTC, miker83z approved these changes
LGTM! 
Just a fix to the main comment, then could be merged.

2024-08-05 13:10 UTC, valeriyr approved these changes

2024-08-05 13:45 UTC, lucas-tortora approved these changes

2024-08-05 13:46 UTC, DaughterOfMars approved these changes

2024-08-05 13:58 UTC, merged