feat(devx): edit getting-started > your first dApp
iotaledger/iota pull request #1579
Opened 2024-08-01 17:39 UTC by lucas-tortora

# Description of change

* Edited all the articles in the Getting Started > First App section
* Fixed sidebar

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/1389

## Type of change

- Documentation Enhancement

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-08-01 21:17 UTC, salaheldinsoliman requested changes
LGTM except for some lints.

2024-08-15 09:43 UTC, salaheldinsoliman approved these changes

2024-08-15 17:04 UTC, Ginowine approved these changes

2024-08-19 12:20 UTC, fijter approved these changes
Will clean up the examples/Move2024' them after this one has been merged and go over it all again :)

2024-08-26 13:14 UTC, merged