feat(sui-genesis-builder): implement creation of basic outputs
iotaledger/iota pull request #159
Opened 2024-05-01 15:52 UTC by kodemartin

# Description of change

This patch implements the transformation logic for basic outputs in the `sui_genesis_builder::stardust::migration::Executor`. 

It follows the [basic_migration_graph logic](https://github.com/iotaledger/kinesis/blob/develop/crates/sui-framework/packages/stardust/basic_migration_graph.svg) with the following exceptions (cc: @miker83z):

* The owner of generated owned basic-output object is not the hash of the unlock address, but the 32-byte array of the address. 

It further amends the existing implementation in `sui_genesis_builder::stardust::migration` according to the following:

* All `create_{<output-kind>_objects` update the executor store internally and do not return the created objects. Less pure, but more ergonomic.

Will rebase to squash fixups before merging.

## Links to any relevant issues

Resolves #112

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo build -p sui-genesis-builder`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-05-08 13:18 UTC, samuel-rufi reviewed
Hey @kodemartin, absolutely fantastic work. Could follow it well.

I have added already a few thoughts in advance while reading it.

2024-05-13 10:34 UTC, samuel-rufi approved these changes

2024-05-14 15:14 UTC, miker83z requested changes
Just a couple of oversights! Then it's ready to be merged

2024-05-14 16:09 UTC, miker83z approved these changes

2024-05-14 16:13 UTC, merged