refactor(iota-indexer): add db schema diagram in README.md
iotaledger/iota pull request #1594
Opened 2024-08-02 15:08 UTC by sergiupopescu199

# Description of change

This patch adds a diagram with the database schema of the `iota-indexer`.

## Links to any relevant issues

Resolves #1248 
## Type of change

- Documentation Fix

2024-08-06 09:36 UTC, kodemartin requested changes
Great job @sergiupopescu199 ! Just a few suggestions to make the presentation of the infro more compact and readable.

2024-08-07 07:08 UTC, kodemartin approved these changes
lgtm, well done!

Just run `dprint fmt` to resolve https://github.com/iotaledger/iota/actions/runs/10270349358/job/28417865141?pr=1594

2024-08-07 14:21 UTC, lzpap approved these changes
Looks good, very thorough!

2024-08-12 12:16 UTC, DaughterOfMars approved these changes

2024-08-12 12:21 UTC, merged