feat(docs/examples): Test the positive scenarios for using an NFT object
iotaledger/iota pull request #1615
Opened 2024-08-05 13:36 UTC by Dkwcs

# Description of change

Add example of third-party simple nft package, PTB that create custom nft from stardust::nft

## Links to any relevant issues

Fix #1334 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Run:

`cargo run --example nft-migration`

2024-08-06 20:55 UTC, miker83z requested changes
LGTM! Just left some minor comments...

2024-08-07 09:23 UTC, miker83z approved these changes
LGTM! Great work 💪🏻

2024-08-07 12:22 UTC, lzpap approved these changes

2024-08-07 14:11 UTC, valeriyr approved these changes

2024-08-07 14:38 UTC, merged