chore(CI): Refactor rust CI workflows into a hierarchy
iotaledger/iota pull request #1616
Opened 2024-08-05 13:44 UTC by DaughterOfMars

# Description of change

Splits out the workflows from `rust.yml` and `external.yml` into several reusable workflows and calls them hierarchically so that easy workflows are run first and their success determines whether harder ones will run.

## Links to any relevant issues

Closes #1368

2024-08-09 14:31 UTC, msarcev approved these changes

2024-08-10 21:22 UTC, Dr-Electron approved these changes
Lovely PR. Will build on it and cleanup our docs workflows ❤️ 
Just some minor things/questions:
- We could also use just `workflow_call` instead of `[workflow_call]` (I prefer that, but no strong opinion :trollface: )
- Just out of curiousity: Why the underscore? Just for us to see the difference or has it any practical use case?

2024-08-13 12:44 UTC, thibault-martinez requested changes
To prevent merge, not done with my review.

2024-08-13 15:38 UTC, thibault-martinez approved these changes

2024-08-14 08:39 UTC, merged