feat(explorer): Update with latest inflation changes
iotaledger/iota pull request #1627
Opened 2024-08-06 07:47 UTC by marc2332

DEPENDS ON https://github.com/iotaledger/iota/pull/1626
Closes https://github.com/iotaledger/iota/issues/1583
Closes https://github.com/iotaledger/iota/issues/1354

2024-08-06 15:15 UTC, begonaalvarezd requested changes

2024-08-07 14:07 UTC, begonaalvarezd reviewed
> Add Current IOTA Total Supply to the landing page

This part of the task is missing 🙏🏼 please note that after the inflation changes the total supply is always returned in `nano`

2024-08-07 16:33 UTC, begonaalvarezd requested changes

2024-08-08 14:31 UTC, begonaalvarezd approved these changes

2024-08-08 14:53 UTC, begonaalvarezd approved these changes

2024-08-08 14:53 UTC, msarcev approved these changes

2024-08-08 14:54 UTC, merged