feat(sui-genesis-builder): migrate Alias Outputs
iotaledger/iota pull request #163
Opened 2024-05-03 15:18 UTC by PhilippGackstatter

# Description of change

Implements the Move models in Rust for the migration of the Alias Output.

Changes to the Alias Move model:
- Make `attach_alias` method public (was test-only before). This is needed so we can easily attach the `Alias` to the `AliasOutput` from a PTB, since we cannot pass `alias_output.id` as an argument to `dynamic_object_field::add` directly.
- Make State Controller non-optional. A state controller is always present in the stardust model, so imho it does not make sense to make it `Option<SuiAddress>` in the move code, unless I missed the argument for it.

## Links to any relevant issues

fixes issue #154.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Added a migration test. More to be added for native tokens and in case the alias id is zeroed.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-05-15 17:25 UTC, miker83z requested changes
Great PR, it follows almost perfectly the assumed design! 

I just signaled a major issue related to the security of generating ObjectIds + some small issues.

2024-05-16 11:57 UTC, kodemartin requested changes

2024-05-16 12:12 UTC, miker83z approved these changes

2024-05-16 13:11 UTC, kodemartin approved these changes

2024-05-16 13:14 UTC, merged