doc(node): Add doc comments to iota-network/state_sync mod
iotaledger/iota pull request #1645
Opened 2024-08-06 12:47 UTC by jkrvivian

# Description of change

Add comments and doc comments to `state_sync` mod in `iota-network` .

## Links to any relevant issues

Part of #1555 

## Type of change

- Documentation Fix

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code

2024-08-07 10:21 UTC, muXxer requested changes

2024-08-09 13:00 UTC, DaughterOfMars approved these changes

2024-08-09 13:56 UTC, muXxer approved these changes

2024-08-13 10:46 UTC, samuel-rufi approved these changes
Great!

2024-08-13 17:48 UTC, merged