feat(iota-genesis-builder): Remove brotli compression flag in genesis builder
iotaledger/iota pull request #1651
Opened 2024-08-06 14:01 UTC by tomxey

# Description of change

Removed an option to use brotli compression in iota-genesis-builder through the `--compress` flag.
The reasoning is explained here: #926

## Links to any relevant issues

fix #926 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected):
    - The `--compress` flag in `iota-genesis-builder` will no longer be accepted

## How the change has been tested

- `cargo test`
- manually checked that the command `cargo run --bin iota-genesis-builder...` executes successfully

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-08-07 07:27 UTC, kodemartin requested changes

2024-08-07 14:51 UTC, kodemartin approved these changes
lgtm :tada: kudos on your first PR @tomxey :tada:

2024-08-07 16:16 UTC, DaughterOfMars approved these changes

2024-08-08 08:19 UTC, Thoralf-M approved these changes

2024-08-08 09:48 UTC, merged