docs: Proofread Standards docs
iotaledger/iota pull request #1668
Opened 2024-08-07 09:38 UTC by PhilippGackstatter

# Description of change

Proofread _Standards_ section in the docs.

- Fix various typos.
- Convert tabs to spaces (because tabs have a different indentation on the rendered page).
- Add missing PTB examples, mostly in the kiosk doc.
- References to Sui projects have been removed or adapted.
- The tooling team told me that `@iota/wallet-standard` is a package that will be published, so the _Wallet Standard_ page should be correct as-is once the wiki goes public.
- I double-checked the syntax of the JavaScript and Rust examples and fixed them if they were broken.
- All `struct` definition examples in Move were made `public` since structs [must always be public](https://github.com/iotaledger/iota/blob/0a7946d4129c652b0844bc70dc3294bebf68f713/external-crates/move/crates/move-compiler/src/parser/syntax.rs#L2750) and the examples should be syntactically correct. Unnecessary imports were also removed and some occurrences were rewritten to method-style syntax.

## Links to any relevant issues

fixes #1293

2024-08-09 12:04 UTC, lucas-tortora approved these changes

2024-08-09 13:14 UTC, lzpap reviewed
It's a nit, but let's put the `Overview` page on the header of `Standards`. like we did it here https://github.com/iotaledger/iota/pull/1710/commits/4681b24dfdd04aa62dc7e15a210366a25cebb3ac

2024-08-12 07:14 UTC, Thoralf-M approved these changes

2024-08-12 14:15 UTC, valeriyr approved these changes
@PhilippGackstatter well done! Just left several minor comments.

2024-08-12 15:02 UTC, Dr-Electron requested changes
Suggested a better way to autogenerate index pages.

This is also the reason why we need description frontmatter everywhere, because then it gets added to the cards in the index page

2024-08-13 13:36 UTC, Dr-Electron approved these changes

2024-08-13 14:17 UTC, merged