docs(iota-json-rpc-api): Add crate and trait level documentation
iotaledger/iota pull request #1676
Opened 2024-08-07 14:22 UTC by samuel-rufi

# Description of change

Adds crate and trait level documentation to the `iota-json-rpc-api` crate.

In addition, the following points were identified that may be converted into issues:
- `total_transactions` exists both in `IndexerApi` and `ExtendedApi`.  Furthermore there exists `get_total_transaction_blocks` in `ReadApi`
- `query_objects` in `ExtendedApi` might better fit in the `IndexerApi` scope
-  are`multi_*` read-methods in `ReadApi` really needed?
- should `get_latest_iota_system_state` from `GovernanceApi` be moved to `ExtendedApi`?
- should `GovernanceReadApi` be refactored to only include staking and validator related methods?
- the `ReadApi` contains methods that might better fit the  `IndexerApi` scope: for example `get_object` or `get_child_objects`

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/1375

## Type of change

- Documentation

## How the change has been tested

`cargo build`

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-08-08 07:54 UTC, thibault-martinez requested changes
Clippy

2024-08-08 10:21 UTC, lzpap approved these changes

2024-08-08 13:30 UTC, Thoralf-M approved these changes

2024-08-08 13:54 UTC, DaughterOfMars approved these changes

2024-08-09 09:17 UTC, kodemartin requested changes
hey @samuel-rufi, looks good. Made a few suggestions to further refine the docs.

2024-08-09 12:42 UTC, kodemartin approved these changes
One spurious proofing oversight needs fixing but other than that good to go!

2024-08-12 08:10 UTC, thibault-martinez approved these changes

2024-08-12 08:24 UTC, merged