feat(docs/content): docs implementation for address unlock condition example
iotaledger/iota pull request #1706
Opened 2024-08-08 09:36 UTC by Dkwcs

# Description of change

Documentation for the example that demonstrate how to unlock an output owned by an alias output

## Links to any relevant issues

Fix #1332 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

2024-08-08 15:09 UTC, DaughterOfMars approved these changes

2024-08-09 13:10 UTC, lucas-tortora approved these changes

2024-08-09 13:26 UTC, DaughterOfMars approved these changes

2024-08-09 15:59 UTC, miker83z requested changes
LGTM! Added some comments for clarification:

2024-08-12 13:44 UTC, miker83z approved these changes
LGTM!

2024-08-12 14:03 UTC, Dr-Electron approved these changes
Quite a task for a beginner in Move/Objects 😅 
But the PR looks good to me 👍

2024-08-13 07:36 UTC, merged