feat!(crates): remove iota name service
iotaledger/iota pull request #1722
Opened 2024-08-09 09:25 UTC by Thoralf-M

# Description of change

Removed all iota name service related things from crates/* as we won't have a name service for now and later it might look a bit different. Remaining things will be done in another PR #1611 
Graphql schema was updated with `cargo run generate-schema > schema/current_progress_schema.graphql`

## Links to any relevant issues

Fixes #1607 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

cargo check

2024-08-09 11:12 UTC, thibault-martinez reviewed
There is a mention to `NAME_SERVICE` in `crates/iota-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap`, do you know if we should remove?

2024-08-09 13:52 UTC, DaughterOfMars approved these changes

2024-08-20 12:23 UTC, kodemartin requested changes
Hey @Thoralf-M, looks good in general. Left a few suggestions/questions of non-critical nature.

2024-08-21 08:32 UTC, kodemartin approved these changes
lgtm :rose:

2024-08-21 09:32 UTC, thibault-martinez approved these changes

2024-08-26 09:06 UTC, merged