feat(docs): Alias usage documentation was added
iotaledger/iota pull request #1723
Opened 2024-08-09 10:01 UTC by valeriyr

# Description of change

Alias usage documentation was added.

## Links to any relevant issues

fixes #1329
fixes #1335

2024-08-09 12:58 UTC, Dkwcs approved these changes

2024-08-09 13:27 UTC, DaughterOfMars approved these changes

2024-08-09 15:36 UTC, miker83z requested changes
Looks good! Just some clarifications added:

2024-08-12 11:29 UTC, miker83z approved these changes

2024-08-12 11:30 UTC, merged