feat(docs/content): Create example doc for claiming a Foundry Output
iotaledger/iota pull request #1724
Opened 2024-08-09 10:27 UTC by Dkwcs

# Description of change

Documentation for the example that demonstrate how to claim an foundry output.

## Links to any relevant issues

Fix #1661 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

2024-08-09 13:28 UTC, DaughterOfMars approved these changes

2024-08-09 16:21 UTC, miker83z requested changes
Also here, some clarifications to do!

2024-08-12 11:45 UTC, lucas-tortora approved these changes

2024-08-12 13:45 UTC, miker83z approved these changes

2024-08-13 07:36 UTC, merged