chore(CI): Add unused dependencies check
iotaledger/iota pull request #1741
Opened 2024-08-09 16:52 UTC by DaughterOfMars

# Description of change

Adds unused dependency checks. These are per-crate like tests as it requires building.

## Links to any relevant issues

Closes #1664

2024-08-13 09:52 UTC, thibault-martinez requested changes
Some little udeps failures

2024-08-13 14:32 UTC, Thoralf-M approved these changes
Great!

2024-08-14 15:40 UTC, thibault-martinez approved these changes

2024-08-14 15:57 UTC, miker83z approved these changes

2024-08-15 13:43 UTC, sergiupopescu199 approved these changes

2024-08-16 12:34 UTC, merged