refactor(wallet): improve component imports
iotaledger/iota pull request #1743
Opened 2024-08-09 17:36 UTC by panteleymonchuk

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Closes #1704

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-08-12 10:25 UTC, begonaalvarezd requested changes
Just submitting a quick review before this PR grows bigger 🙏🏼 
The original issue was open just to create an index for components which is missing and update those imports so you can import like `import { CompA, CompB, ...} from blabla` instead of having 1 line per component like now.

I would not get into refactoring more imports for now, refactoring imports can escalate a lot, lets try to narrow the task to the only refactor described in the issue 🙏🏼

2024-08-13 10:24 UTC, marc2332 requested changes
What about imports like `import { Button } from '../../../shared/ButtonUI';` ?

2024-08-13 11:31 UTC, marc2332 approved these changes

2024-08-14 11:06 UTC, evavirseda approved these changes

2024-08-14 11:22 UTC, begonaalvarezd approved these changes

2024-08-14 16:45 UTC, merged