feat(devx) - Edit About IOTA
iotaledger/iota pull request #1776
Opened 2024-08-13 14:29 UTC by lucas-tortora

# Description of change

Edited the About IOTA section, except Tokenomics, which will be covered in another PR after https://github.com/iotaledger/iota/pull/1726 has been merged.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/1402

## Type of change

- Documentation 

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-08-15 09:42 UTC, salaheldinsoliman requested changes

2024-08-15 12:13 UTC, fijter approved these changes

2024-08-19 10:00 UTC, Dr-Electron approved these changes
LGTM, but why get rid of the frontmatter? I would rather try to add it where it is missing 😅

2024-08-20 13:56 UTC, salaheldinsoliman approved these changes

2024-08-20 14:18 UTC, merged