fix!(general): rename micros to nanos
iotaledger/iota pull request #1866
Opened 2024-08-15 10:06 UTC by Thoralf-M

# Description of change

Rename micros to nanos, as this is the correct name for the smallest unit now.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/1281

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo check`

2024-08-15 12:01 UTC, fijter approved these changes

2024-08-15 12:35 UTC, lucas-tortora approved these changes

2024-08-15 17:08 UTC, DaughterOfMars approved these changes

2024-08-16 08:39 UTC, samuel-rufi approved these changes

2024-08-20 07:15 UTC, thibault-martinez requested changes
Conflicts

2024-08-20 13:43 UTC, thibault-martinez approved these changes

2024-08-21 08:26 UTC, kodemartin approved these changes

2024-08-22 07:10 UTC, merged