feat(wallet-dashboard): hook timelocked staking feature
iotaledger/iota pull request #1976
Opened 2024-08-21 15:31 UTC by brancoder

# Description of change

Adds timelocked staking feature to dashboard vesting page.
- Staking Transaction creation uses simple algorithm to split objects selected for staking.
- merge the timelocked objects before staking them to clean them up

## Links to any relevant issues

resolves #1084 .

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

1. Using tooling resources create vesting portfolio with: `pnpm timelock:publish` and `pnpm timelock:vesting`
 Optionally use split example to split some of the vesting objects in the vesting portfolio using `pnpm timelock:split`
 2. Update the vesting label constant, in the dashboard, to your published package id: 
 `example:
 export const SUPPLY_INCREASE_VESTING_LABEL = 'eaa22e4cbb1e8b41dca038fc175f147180265a41617c3e4125e54434506df45f::stardust_upgrade_label::STARDUST_UPGRADE_LABEL';`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-08-26 14:58 UTC, cpl121 requested changes
also conflicts 🙏🏼

2024-08-29 08:46 UTC, cpl121 requested changes

2024-08-29 10:01 UTC, marc2332 requested changes
Looks like I forgot to click on "request changes"

2024-09-03 07:50 UTC, cpl121 approved these changes

2024-09-04 12:36 UTC, msarcev approved these changes

2024-09-10 08:50 UTC, begonaalvarezd approved these changes

2024-09-10 08:59 UTC, marc2332 approved these changes

2024-09-10 09:32 UTC, merged