docs: Add README.md for `iota-json-rpc`
iotaledger/iota pull request #1986
Opened 2024-08-22 12:26 UTC by samuel-rufi

# Description of change

Discussing the general purpose, use, and design of the JSON-RPC.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/1985
FIxes https://github.com/iotaledger/iota/issues/1341

## Type of change

- Documentation

2024-08-22 12:32 UTC, sergiupopescu199 approved these changes
lgtm 🚀

2024-08-22 14:45 UTC, tomxey approved these changes
lgtm 🥳

2024-08-22 14:52 UTC, kodemartin requested changes
A few minor comments @samuel-rufi that could help improve the README.

2024-08-27 10:34 UTC, lzpap approved these changes

2024-08-27 13:23 UTC, merged