feat(tooling-explorer): Rebrand network activity on homepage
iotaledger/iota pull request #1987
Opened 2024-08-22 12:43 UTC by msarcev

# Description of change

* Rebrand Network activity like on figma
* Adds types mapping to `ui-kit` so typing works in explorer

Closes https://github.com/iotaledger/iota/issues/1884

2024-08-22 13:18 UTC, marc2332 requested changes

2024-08-22 13:34 UTC, marc2332 requested changes

2024-08-23 11:33 UTC, marc2332 approved these changes
LGTM

2024-08-23 12:02 UTC, evavirseda submitted a review, later dismissed
added some suggestions :pray:

2024-08-23 12:40 UTC, evavirseda approved these changes

2024-08-23 12:45 UTC, merged