feat(tooling-explorer): Rebrand homepage pagination
iotaledger/iota pull request #2008
Opened 2024-08-23 10:36 UTC by marc2332

DEPENDS on https://github.com/iotaledger/iota/pull/2230
Closes https://github.com/iotaledger/iota/issues/2006

2024-08-26 12:23 UTC, panteleymonchuk submitted a review, later dismissed

2024-09-05 11:31 UTC, cpl121 requested changes
The `CheckpointTransactionBlocks` component hasnt the changes

2024-09-06 07:46 UTC, cpl121 approved these changes

2024-09-06 09:50 UTC, evavirseda requested changes

2024-09-10 09:42 UTC, evavirseda approved these changes

2024-09-10 16:40 UTC, merged