chore(docs): Remove papers
iotaledger/iota pull request #2029
Opened 2024-08-23 13:52 UTC by Dr-Electron

# Description of change

Removed the papers in doc and their duplicates in other locations, and the references to them.

## Links to any relevant issues

Fixes #2002.

## Type of change

- Documentation Fix

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-08-23 14:59 UTC, thibault-martinez requested changes
What about `docs/site/static/paper`?

2024-08-26 17:42 UTC, thibault-martinez approved these changes

2024-08-26 18:09 UTC, lucas-tortora approved these changes

2024-08-28 12:13 UTC, samuel-rufi approved these changes

2024-08-28 12:18 UTC, msarcev approved these changes

2024-08-28 12:18 UTC, merged