feat(sui-genesis-builder): Test creation of Foundry outputs
iotaledger/iota pull request #209
Opened 2024-05-14 13:12 UTC by samuel-rufi

# Description of change

Adds test cases for transforming foundry outputs.

## Links to any relevant issues

Fixes https://github.com/iotaledger/kinesis/issues/204
Fixes https://github.com/iotaledger/iota/issues/541

2024-05-29 13:16 UTC, lzpap requested changes
Hi @samuel-rufi , I started reviewing this but saw that we already have some overlaps with https://github.com/iotaledger/kinesis/pull/383 . Therefore, I would like to ask you to clean up this PR:
 - put tests in `crates/sui-genesis-builder/src/stardust/migration/tests` folder
 - match the alias tests against what we already have in `develop`
 - put the foundry tests there as well

Once done, we can proceed with the review.

2024-06-04 16:37 UTC, miker83z submitted a review, later dismissed
LGTM after you fix the other comments!

2024-06-05 10:53 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-05 11:28 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-05 11:47 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-05 11:54 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-05 12:22 UTC, Thoralf-M submitted a review, later dismissed

2024-06-05 12:36 UTC, lzpap submitted a review, later dismissed
LGTM with a minor comment

2024-06-05 12:39 UTC, miker83z submitted a review, later dismissed

2024-06-05 14:15 UTC, DaughterOfMars approved these changes

2024-06-05 15:27 UTC, miker83z approved these changes

2024-06-05 15:29 UTC, merged