feat(devx): add migrate to coin-manager article
iotaledger/iota pull request #2131
Opened 2024-08-29 13:31 UTC by salaheldinsoliman

# Description of change

Add a full example to migrate a `Coin` to `CoinManager`

## Links to any relevant issues

#1838 

## Type of change

- Documentation

## How the change has been tested

Locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-08-30 11:22 UTC, lucas-tortora requested changes

2024-09-05 16:14 UTC, lucas-tortora requested changes
Please add links to the references section for the modules and functions you mention in the article,  like :
https://docs.iota.org/references/framework/iota-framework/coin_manager
https://docs.iota.org/references/framework/iota-framework/coin

2024-09-10 12:20 UTC, lucas-tortora requested changes

2024-09-17 17:09 UTC, lucas-tortora requested changes

2024-09-19 16:06 UTC, lucas-tortora approved these changes

2024-09-20 10:51 UTC, fijter approved these changes
Looks like a good example, including a practical application of the witness pattern. Just reviewed the docs part and not the Rust changes which don't belong in this PR I think. I'd probably leave out the local setup stuff given you can test this just as well on the testnet.

2024-09-20 14:47 UTC, merged