refactor(explorer, wallet, sdk): Unified, extensible and private configuration for Networks
iotaledger/iota pull request #219
Opened 2024-05-15 14:09 UTC by marc2332

# Description of change

- Unifies all network-related environment variables and hard-coded values into 1 single JSON served as an env var to the apps and the SDK
- The `IOTA_NETWORKS` env var contains all the networks configurations
- The `DEFAULT_NETWORK` env var contains the default network to be used
- I removed `dotenv-webpack` because it doesn't support multi-line `.env` files
- Any change to the `.env` file should invalidate the cache of turborepo so it should run just fine on CI/CD

Example using the public SUI endpoints

```env
DEFAULT_NETWORK = 'testnet'

IOTA_NETWORKS = '
{
    "mainnet": {
        "id": "mainnet",
        "name": "Mainnet",
        "url": "https://sui-mainnet.mystenlabs.com/json-rpc",
        "explorer": "https://suiexplorer.com"
    },
    "testnet": {
        "id": "testnet",
        "name": "Testnet",
        "url": "https://sui-testnet.mystenlabs.com/json-rpc",
        "explorer": "https://suiexplorer.com",
        "faucet": "https://faucet.testnet.sui.io/gas"
    }
}
'
```

## But Why?
- Values are not hardcoded
   - Private and harder to leak
   - Easier to change as you only need to change the env var in whatever deploy platform it's being deployed and deploy again, instead of having to change the code itself
- Code is easier to understand and scale as all the values come from the same place   

## Links to any relevant issues

Closes https://github.com/iotaledger/kinesis/issues/198

## Type of change

- Refactor

## How the change has been tested

Running the Wallet and the Explorer

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-05-16 11:10 UTC, msarcev approved these changes

2024-05-17 10:03 UTC, brancoder requested changes
Great job :muscle: 
We should also use `.env.defaults ` as default values in SDK

2024-05-17 10:14 UTC, brancoder reviewed
selecting Custom Network messes up the select button.

![image](https://github.com/iotaledger/kinesis/assets/52735957/eca9f4f6-5091-4db5-a245-b9849a0f8995)

2024-05-17 12:01 UTC, brancoder approved these changes
LGTM :1st_place_medal:

2024-05-20 11:24 UTC, merged