Fixed sui-execution compile errors after crates removal
iotaledger/iota pull request #22
Opened 2024-02-21 15:25 UTC by valeriyr

## Description 

Fixed sui-execution compile errors after deleting crates.

Issue #6

2024-02-21 15:44 UTC, miker83z requested changes

2024-02-21 17:35 UTC, samuel-rufi approved these changes

2024-02-22 09:15 UTC, miker83z approved these changes

2024-02-22 09:28 UTC, kodemartin requested changes
Looks good, and builds even better! Left a couple of minor suggestions on the new `sui_types::multiaddr` module.

2024-02-22 10:14 UTC, samuel-rufi approved these changes

2024-02-22 12:47 UTC, kodemartin approved these changes

2024-02-22 12:53 UTC, merged