feat(iota): add doc comments to validator commands
iotaledger/iota pull request #2212
Opened 2024-09-03 11:51 UTC by Thoralf-M

# Description of change

Updated docs for iota validator commands

## Links to any relevant issues

https://github.com/iotaledger/iota/issues/1059

## Type of change

- Documentation Fix

2024-09-06 13:59 UTC, DaughterOfMars approved these changes

2024-09-06 14:00 UTC, DaughterOfMars requested changes
Gotta update the CLI output in the doc too

2024-09-09 13:17 UTC, lucas-tortora approved these changes

2024-09-11 21:09 UTC, Dr-Electron approved these changes

2024-09-16 12:13 UTC, DaughterOfMars approved these changes

2024-09-30 11:40 UTC, lucas-tortora approved these changes

2024-10-01 18:44 UTC, merged