(tooling/explorer): rebrand epoch page: checkpoints
iotaledger/iota pull request #2248
Opened 2024-09-04 18:00 UTC by panteleymonchuk

Closes #1896

2024-09-05 07:32 UTC, marc2332 requested changes
better to have controlled tabs rather than uncontrolled.

Btw, shouldn't we add a storybook as well?

2024-09-09 09:06 UTC, marc2332 requested changes

2024-09-11 11:23 UTC, evavirseda requested changes
nice job, just one detail :blush:

2024-09-11 12:59 UTC, evavirseda approved these changes
nice job :guitar:

2024-09-12 10:45 UTC, VmMad approved these changes

2024-09-12 11:07 UTC, marc2332 approved these changes

2024-09-12 11:07 UTC, merged