feat(wallet): rebrand stake tx details page
iotaledger/iota pull request #2266
Opened 2024-09-05 14:51 UTC by brancoder

# Description of change

Rebrands stake transaction details page

## Links to any relevant issues

resolves #2235
resolves #2236

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2024-09-09 15:52 UTC, cpl121 requested changes
Amazing work, I left some comments 🙏🏼

2024-09-09 16:13 UTC, evavirseda requested changes

2024-09-10 15:37 UTC, cpl121 requested changes
It's weird, but if I look the card from alphanet I see it fine, but if I see it from testnet, I see it shifted to the left
![Captura de pantalla de 2024-09-10 17-12-02](https://github.com/user-attachments/assets/ae88eb99-2dd1-4aca-b8af-c68db1375a14)
![Captura de pantalla de 2024-09-10 17-18-04](https://github.com/user-attachments/assets/b9de6b9f-70db-427d-ab5b-7d79f5211098)

2024-09-11 09:10 UTC, cpl121 requested changes

2024-09-11 13:46 UTC, evavirseda approved these changes
:rocket:

2024-09-11 18:10 UTC, cpl121 approved these changes

2024-09-12 07:14 UTC, merged