fix(iota-replay): sandbox snapshots are outdated due to rename
iotaledger/iota pull request #2269
Opened 2024-09-05 15:58 UTC by Dkwcs

# Description of change

The sandbox snapshots were originally generated based on some Sui mainnet transactions.
However, we can no longer support them due to significant code changes (rebate, renaming, balance, etc.). 
We need to generate new ones using the SandboxPersist command (for this, we require a non-system transactions to replay).

`cargo run --example make_sandbox_snapshot <your tx digest>` generates a snapshot based on a mock transaction (package publishing) you published earlier. This should be sufficient to make the tests pass, at least until we have specific transactions we want to replay on the testnet/mainnet.

## Links to any relevant issues

Fix #1499 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

To make a snapshot(local example):

1. iota-test-validator - `cargo run`
2. `iota client faucet`
3. iota-replay/move/tx_instance - `iota client publish --gas-budget 1000000000`
4. Save tx digest 
5. iota-replay - `cargo run --example make_sandbox_snapshot <your tx digest>`

iota-replay - `cargo test`

2024-09-06 09:34 UTC, valeriyr requested changes

2024-09-09 10:23 UTC, Thoralf-M approved these changes

2024-09-09 10:28 UTC, valeriyr approved these changes

2024-09-11 09:42 UTC, miker83z requested changes
LGTM! Just a change to continue ignoring the test

2024-09-11 10:07 UTC, miker83z submitted a review, later dismissed

2024-11-26 10:39 UTC, miker83z commented on crates/iota-replay/tests/README.md
@Dkwcs we can remove most of the text now, just leave the description and the commands

2024-11-26 14:39 UTC, Dkwcs commented on crates/iota-replay/tests/README.md
Done

2024-11-26 14:45 UTC, Thoralf-M approved these changes

2024-11-26 15:02 UTC, miker83z approved these changes

2024-11-26 15:07 UTC, merged