feat(iota-json-rpc-types, iota-graphql-rpc): Update IotaGenesisTransaction with events vector in JSON-RPC and GraphQL schema
iotaledger/iota pull request #2280
Opened 2024-09-06 00:03 UTC by samuel-rufi

# Description of change

Adds a vector of `EventID`s to `IotaGenesisTransaction` JSON-RPC type and adjusts the GraphQL schema.

## Links to any relevant issues

https://github.com/iotaledger/iota/issues/2268

## How the change has been tested

`cargo build`, `cargo test`

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-09-06 08:06 UTC, kodemartin requested changes
Thanks for the quick patch @samuel-rufi! 

My first remakr is to make this the PR the one that closes https://github.com/iotaledger/iota/issues/2268.

To this end, there a few things need to be done:
1. Again we should target an interim `update-rpc-genesis-transaction` branch to stage all changes together with the tooling team (@begonaalvarezd , @msarcev, @marc2332 )
2. We should regenerate the graphql process schema (see cli argument in `iota-graphql-rpc`)
3. We should expose the events in the `GenesisTransaction` type in `iota-graphql-rpc`.

Regarding this first patch itself, I would recommend relying on `IotaEvent` to represent the view of `Event` values in the json-rpc interface.

2024-09-12 07:40 UTC, kodemartin approved these changes
lgtm :cactus: :

2024-09-12 17:45 UTC, begonaalvarezd reviewed
@kodemartin I tried running `cargo run --package iota-graphql-rpc generate-schema --file ./crates/iota-graphql-rpc/schema/current_progress_schema.graphql` to check if the graphq schema was up to date and im getting errors 

```terminal
   Compiling iota-graphql-rpc v2024.2.0 ([monorepo_path]/crates/iota-graphql-rpc)
error[E0425]: cannot find value `cursors` in this scope
  --> crates/iota-graphql-rpc/src/types/transaction_block_kind/genesis.rs:95:23
   |
95 |         for cursor in cursors {
   |                       ^^^^^^^ not found in this scope

error[E0425]: cannot find value `c` in this scope
  --> crates/iota-graphql-rpc/src/types/transaction_block_kind/genesis.rs:96:51
   |
96 |             let native_event = self.native.events[c.ix].clone();
   |                                                   ^ not found in this scope

error[E0425]: cannot find value `c` in this scope
   --> crates/iota-graphql-rpc/src/types/transaction_block_kind/genesis.rs:104:45
    |
104 |             connection.edges.push(Edge::new(c.encode_cursor(), event));
    |                                             ^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `iota-graphql-rpc` (lib) due to 3 previous errors
```

2024-09-16 12:04 UTC, DaughterOfMars approved these changes

2024-09-18 07:24 UTC, begonaalvarezd approved these changes

2024-09-18 12:17 UTC, merged