feat(explorer): rebrand epoch page: validators
iotaledger/iota pull request #2304
Opened 2024-09-06 18:23 UTC by panteleymonchuk

Closes #1897
Depends on #2248

2024-09-09 09:23 UTC, marc2332 requested changes

2024-09-12 17:53 UTC, begonaalvarezd reviewed
Could we maybe improve this column a little bit so the staked amout doesnt break into 2 lines? 
![image](https://github.com/user-attachments/assets/6f829123-34a5-430c-a37a-3afbfd56769f)
We should probably do the same for the amounts in general in the table to avoid 2 lines which makes it hard to read, I would probably not allow to break into 2 lines none of these values 
![image](https://github.com/user-attachments/assets/1fd0842a-2bc2-4046-b128-0be2a437faee)
If this is too much for the scope of this PR, I can open a polish task for it so it is tackled in a different PR, just let me know 🌷

2024-09-13 09:39 UTC, VmMad reviewed
Just a few more upgrades

2024-09-13 13:12 UTC, begonaalvarezd requested changes
Quick thing I just noticed, the validators tab is selected by default when you land on the page when it shouldnt, the first tab should be the selected one
![image](https://github.com/user-attachments/assets/8d509a67-6310-46ab-ae98-df69eb676c1b)

2024-09-16 11:04 UTC, VmMad approved these changes

2024-09-17 09:36 UTC, begonaalvarezd approved these changes

2024-09-17 13:57 UTC, marc2332 approved these changes

2024-09-17 13:59 UTC, merged