fix(docs): Move all images to the static folder
iotaledger/iota pull request #2359
Opened 2024-09-09 19:39 UTC by lucas-tortora

# Description of change

Moved all doc images to `docs/static/img` and deleted unused images

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/1441

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

## Release notes

Organized images used in the docs.

2024-09-11 21:20 UTC, Dr-Electron approved these changes

2024-09-11 21:43 UTC, Dr-Electron requested changes
Maybe you want too look at the images from the just referenced issue too? 😢 ❤️ 

https://github.com/iotaledger/iota/issues/1494

2024-09-26 16:03 UTC, Ginowine approved these changes

2024-09-26 22:02 UTC, salaheldinsoliman approved these changes

2024-09-30 07:20 UTC, vivekjain23 approved these changes

2024-10-04 12:20 UTC, Dr-Electron approved these changes

2024-10-25 10:46 UTC, samuel-rufi approved these changes

2024-10-25 11:28 UTC, merged