feat(sui-genesis-builder): Add Basic Output object validation
iotaledger/iota pull request #237
Opened 2024-05-16 17:20 UTC by DaughterOfMars

# Description of change

Adds a framework for validating outputs that have been created for the genesis against the source stardust types, and an implementation for Basic Outputs.

## Links to any relevant issues

Fixes #227

2024-05-20 09:35 UTC, kodemartin requested changes
Hey @DaughterOfMars! This patch introduces many small improvements and it sets the ground for the next steps of verification.

I made some final minor suggestions, plus [one](https://github.com/iotaledger/kinesis/pull/237#discussion_r1606501631) requiring major revisions following the thread on the mapping implementation. The latter though could be delegated to #239.

2024-05-20 13:58 UTC, kodemartin approved these changes

2024-05-20 14:40 UTC, samuel-rufi approved these changes

2024-05-21 21:19 UTC, Thoralf-M approved these changes

2024-05-22 11:52 UTC, kodemartin requested changes

2024-05-22 18:15 UTC, Alex6323 approved these changes

2024-05-23 07:22 UTC, kodemartin approved these changes

2024-05-24 12:28 UTC, merged