feat(explorer): rebrand object page
iotaledger/iota pull request #2400
Opened 2024-09-10 11:42 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/2274, fixes https://github.com/iotaledger/iota/issues/2275 and fixes https://github.com/iotaledger/iota/issues/2276

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-09-10 15:41 UTC, begonaalvarezd requested changes
Amzing work, just couple of comments 
- NFT stats take a bit too much space (`0x83f875664d0c701eda00c24b10e7de49f08da694985eaf31d7a510dbcb0c0b79`)
![image](https://github.com/user-attachments/assets/4981dff5-804d-42e6-b11d-b996f26a7729) versus 
![image](https://github.com/user-attachments/assets/b4ab3511-b234-448c-98e8-b0091ac2b0a5)
- Stats are overflowing `0x0f4dbc9d38eab2f83552a03a12913c2d473a4bc36f6000aa21d3a6ccb511e5ee` 
![image](https://github.com/user-attachments/assets/7768f6e2-702b-44bf-add4-8c47a4e3c632) versus 
![image](https://github.com/user-attachments/assets/07f64b01-bfe8-4db6-b9fb-0657a4a7d37f)
- I would not make these hoverable, we can discuss about it if its too complicated, but i dont see why it needs hover 
![image](https://github.com/user-attachments/assets/9a8a037b-71c0-42c6-9c46-05a6dff6c909)
- I would make this part like we have in the tx block in figma 
![image](https://github.com/user-attachments/assets/fd96e3cc-dbbe-4d56-833a-5caec797cbd9)
![image](https://github.com/user-attachments/assets/139baced-e577-45fa-ab24-070d026369ae) Title: collapsible `X Fields` (same for dynamic) and then make nested collapsibles like in figma for each field

2024-09-11 09:46 UTC, cpl121 requested changes
Something weird thing about the horizontal scrolling

If there is a type of field that has very long text, the rest of the types are off-center
![Captura de pantalla de 2024-09-11 11-35-48](https://github.com/user-attachments/assets/fd5fd060-f180-4797-a8e7-cf947078fb54)

When expanding a field with very long text, the horizontal scroll is extended to the full screen

Collapsed (without horizontal scrolling)
![Captura de pantalla de 2024-09-11 11-41-38](https://github.com/user-attachments/assets/ed835478-4a26-4f6a-b7b9-ac253547f79b)

Expanded
![Captura de pantalla de 2024-09-11 11-39-07](https://github.com/user-attachments/assets/57f479d9-ae40-4015-b164-7320314f99f3)

I think the size of the fields section should be fixed, and centered with the transaction blocks table

2024-09-11 11:26 UTC, cpl121 approved these changes

2024-09-12 09:24 UTC, begonaalvarezd approved these changes
🕺🏼

2024-09-12 09:30 UTC, merged