feat(explorer): rebrand validators page table
iotaledger/iota pull request #2428
Opened 2024-09-10 16:28 UTC by VmMad

Fixes #2271 
Depends on #2304

2024-09-11 11:11 UTC, evavirseda requested changes
some comments :pray:

2024-09-17 17:46 UTC, cpl121 requested changes
Conflicts too 🙏🏼

2024-09-18 12:52 UTC, cpl121 approved these changes

2024-09-23 08:00 UTC, evavirseda approved these changes

2024-09-23 11:09 UTC, merged