feat(explorer): rebrand txblock (transactions, gas & storage fees and balance changes)
iotaledger/iota pull request #2512
Opened 2024-09-12 15:24 UTC by evavirseda

# Description of change

:arrow_right: they are components that are closely related to each other, which is why I had to resolve several issues in the same PR. I was also going to update the inputs and object changes, but I'll do that in another one to prevent this one from becoming too large... that's why those two sections seem a bit half-finished :pray: 

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/2286 , fixes https://github.com/iotaledger/iota/issues/2297 and fixes https://github.com/iotaledger/iota/issues/2298

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-09-16 16:21 UTC, panteleymonchuk requested changes

2024-09-17 10:17 UTC, panteleymonchuk approved these changes

2024-09-18 08:01 UTC, cpl121 requested changes
The signature tag is not rebranded correctly
![Captura de pantalla de 2024-09-18 10-13-14](https://github.com/user-attachments/assets/f13f8f9e-6b13-4d47-89fc-a12a37781e88)

I also think we could create an issue to check if all the fields in the ui-kit are really optional for later, wdyt?

2024-09-18 12:10 UTC, cpl121 approved these changes

2024-09-18 12:11 UTC, merged