feat(iota-indexer): add read_api rpc tests
iotaledger/iota pull request #2552
Opened 2024-09-13 12:38 UTC by sergiupopescu199

# Description of change

- Add Integration tests for `ReadApi` RPC calls for `iota-indexer`
- Fix `show_raw_effects` on Node RPC & Indexer RPC

## Links to any relevant issues
fixes #2201
fixes #2488

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested
- Start a **postgres** instance using this command:
   - `docker run --name iota-indexer-tests -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=iota_indexer -d -p 5432:5432 postgres`

- run tests using one of the provided commands:
  - `cargo test --features pg_integration -- --test-threads 1`
  - `cargo nextest run --features pg_integration --test-threads 1`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works

2024-09-16 08:15 UTC, kodemartin requested changes
Hey @sergiupopescu199 this definitely lays out the scheme for the integration tests. Made a few suggestions that might improve the patch. To summarize:

* Use `pg_integration` feature only.
* Create dedicated tests for each failure or success case, even when testing the same query.
* Restructure to share common code with `ingestion_tests`
* Add tests cases for query filter flags, where applicable.

2024-09-18 13:22 UTC, tomxey requested changes

2024-09-19 08:27 UTC, tomxey approved these changes

2024-09-19 09:06 UTC, samuel-rufi approved these changes

2024-09-19 13:14 UTC, kodemartin approved these changes
Thanks for this thorough work @sergiupopescu199!

I ran the tests successfully and even in `release` mode they take more than 5min locally. Given that we plan to add many more test sets, this calls for an optimization.

I think we will need to figure a way for sharing the test cluster and indexer among the tests. [This suggestion](https://stackoverflow.com/a/58006287) might be promising.

At any case we should create a dedicated issue to this end.

2024-09-23 07:08 UTC, merged