feat(devx): Add filter flag to Iota CLI
iotaledger/iota pull request #2574
Opened 2024-09-16 08:26 UTC by salaheldinsoliman

# Description of change

This PR adds an `emit` flag to `iota client call`, whose functionality is to filter the outputs of the command. 
The flag takes `"effects" | "input" | "events" | "object_changes" | "balance_changes"` as possible args.

This addresses the issue that `call` command result is often too long.

Note: the PR only addresses `call`. If the approach is agreed upon, it can be extended to `ptb` as well
## Links to any relevant issues

 fixes #2015 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
- Added tests in `iota/tests/cli_tests`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-09-23 10:19 UTC, kodemartin requested changes
Hey @salaheldinsoliman! 

I strongly believe that the functionality you want to expose should be handled exclusively on the client. I made several suggestion that essentially imply that all changes to dependencies (`iota-indexer`, `iota-json-rpc`, `iota-json-rpc-types`) should be reverted.

If you think that you need more options for the queries you are performing to expose this functionality, please create issues with the respective feature request so as to discuss them and plan them accordingly.

2024-10-10 16:31 UTC, Thoralf-M approved these changes
LGTM, also tested locally and works as expected
```
iota client call --package 0x3 --module iota_system --function request_add_stake --args 0x5 0x013a0f93df25fcf2e31aaeb97702637e97dece5984b22e185631221c05bf4088 0x111111111504e9350e635d65cd38ccd2c029434c6a3a480d8947a9ba6a15b215 --gas-budget 10000000 --emit balance_changes,events`
Transaction Digest: GVYK7PQYoVRNW5bDUaGcQD4CwaLbsjKBEGV2b6q8ysKj
╭─────────────────────────────╮
│ No transaction block events │
╰─────────────────────────────╯

╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Balance Changes                                                                                   │
├───────────────────────────────────────────────────────────────────────────────────────────────────┤
│  ┌──                                                                                              │
│  │ Owner: Account Address ( 0x111111111504e9350e635d65cd38ccd2c029434c6a3a480d8947a9ba6a15b215 )  │
│  │ CoinType: 0x2::iota::IOTA                                                                      │
│  │ Amount: -1000000                                                                               │
│  └──                                                                                              │
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
```

2024-11-07 15:54 UTC, DaughterOfMars approved these changes

2024-11-08 12:32 UTC, kodemartin approved these changes

2024-11-08 13:00 UTC, merged