feat(docs) - Doc updates v1.32.2
iotaledger/iota pull request #2595
Opened 2024-09-16 13:02 UTC by lucas-tortora

# Description of change

Imported the updates for the docs folder from v1.22.0 to v1.32.2. The biggest changes are:

- `TransactionBlock` is now `Transaction`
- `--gas-budget` flag is no longer necessary. 
- Automated address management for package upgrades. 
- Added the bridge reference docs.

## Open Questions

If we're launching with v1.32.2, we should probably remove the sections in the upgrade docs that refer to address management. Please confirm. 

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/2415

## Type of change

- Documentation Update

## How the change has been tested

Docs were built locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

## Release notes

Updated docs up to v1.32.2

2024-10-04 12:59 UTC, Dr-Electron requested changes

2024-10-04 15:32 UTC, salaheldinsoliman approved these changes
Looks good, but I suggest adding issues that track user-testing new content like:
1- automated address management
2- rent NFT
3- Onchain randomness
4- Custom indexer

2024-10-04 16:09 UTC, Ginowine approved these changes

2024-10-04 18:55 UTC, Dr-Electron approved these changes
I think this LGTM :trollface: 😆

2024-10-07 15:49 UTC, alexsporn approved these changes
Had a quick overview and looks OK. We will need to go through the docs and proofread before release.

2024-10-07 18:16 UTC, merged