feat(ui-kit): Composable UI Kit components
iotaledger/iota pull request #2610
Opened 2024-09-16 16:03 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/2233, closes https://github.com/iotaledger/iota/issues/2231

2024-09-19 09:21 UTC, evavirseda requested changes

2024-09-19 15:43 UTC, evavirseda requested changes
:pray: :pray:

2024-09-19 16:07 UTC, cpl121 requested changes

2024-09-20 09:21 UTC, cpl121 requested changes

2024-09-20 10:25 UTC, cpl121 approved these changes

2024-09-20 10:39 UTC, evavirseda approved these changes
nice job, we can polish later! you're unstoppable indeed :boom:

2024-09-20 10:47 UTC, panteleymonchuk reviewed
I like how this refactoring looks 👍
Just left some comments & questions before approve it

2024-09-20 12:08 UTC, panteleymonchuk approved these changes

2024-09-20 12:28 UTC, merged