feat(explorer): Rebrand address owned assets - ListView
iotaledger/iota pull request #2620
Opened 2024-09-17 09:58 UTC by panteleymonchuk

Closes #2300 
Depends on https://github.com/iotaledger/iota/pull/2610 because probably we'll need fixed links

2024-09-17 11:06 UTC, evavirseda submitted a review, later dismissed

2024-09-22 09:42 UTC, begonaalvarezd requested changes
The scroll is not working 🙏🏼 you can try with address `0x5a77258bf229783416b933906e0b51e2b6592c2105e1c17ccf192b64269d4941`, The paginator is also hidden 
![image](https://github.com/user-attachments/assets/0f3ab40b-d3e0-4439-b3a3-db8e4268ddf6)

2024-09-24 12:56 UTC, brancoder requested changes
Looks great just a couple of nits/questions:
1.  Is it ok that the Type text color is blue like its a link? I understand that its because ObjectLink is used in every cell to make the row clickable, its just that the text in figma is gray. wdyt?
![image](https://github.com/user-attachments/assets/1bcdc8dd-d529-4b76-9d3a-e4c58733cc7b)
2. there is this weird stretching of the pagination buttons when the address page is loading
![image](https://github.com/user-attachments/assets/2be4d33f-d10f-4d1a-a5e1-164d25d548da)

2024-09-25 08:23 UTC, marc2332 requested changes

2024-09-25 20:08 UTC, brancoder approved these changes
LGTM :confetti_ball:

2024-09-26 08:55 UTC, marc2332 approved these changes

2024-09-26 11:03 UTC, begonaalvarezd approved these changes

2024-09-26 11:03 UTC, merged