feat(wallet): Add main badge to accounts with the `0/0/0` derivation path
iotaledger/iota pull request #2664
Opened 2024-09-17 16:10 UTC by panteleymonchuk

Closes #1764

2024-09-18 07:45 UTC, begonaalvarezd requested changes

2024-09-18 14:34 UTC, begonaalvarezd submitted a review, later dismissed

2024-09-18 14:35 UTC, begonaalvarezd reviewed
conflicts 🙏🏼

2024-09-19 10:55 UTC, brancoder approved these changes
LGTM :+1:

2024-09-19 16:46 UTC, begonaalvarezd approved these changes

2024-09-19 16:46 UTC, merged