Update `examples`
iotaledger/iota pull request #2685
Opened 2024-09-18 09:32 UTC by valeriyr

Fixes #2674
Fixes #2678

The example folder is updated. The topics need to be highlighted:
1. The `examples/move/nft-rental` example refers to the `https://github.com/iotaledger/apps.git` repository that doesn't exist. We need to decide if we fork it or delete the example.
2. @begonaalvarezd, please check if the TS part is merged correctly. The conflicts were mostly about updating the dependencies. 
3. @begonaalvarezd,`mev_bot` was removed since it was removed in our repository.

2024-09-18 11:32 UTC, muXxer approved these changes

2024-09-20 07:09 UTC, marc2332 requested changes
You need to add the examples to the pnpm workspace (pnpm-workspace.yaml) so they can access the SDK packages

2024-09-20 11:50 UTC, begonaalvarezd approved these changes

2024-09-20 13:49 UTC, marc2332 approved these changes
🕯️

2024-09-20 13:56 UTC, merged