Clean Sui's GitHub actions [#27]
iotaledger/iota pull request #27
Opened 2024-02-22 14:02 UTC by samuel-rufi

## Description 

This PR cleans Sui's GitHub actions.

The `diffs` action detects code changes in the repo and depending on where something happened it conditionally runs a certain workflow or not. I think it makes sense to keep this.
I removed the `ts-e2e` as we don't have `e2e` tests for now and removed the `turbo-diffs` as it seems unused.

The `scripts/` folder contains only `rosetta-api `specific scripts, which we don't need for now (we did remove Sui's Rosetta impl). Sui further has a `.changesets` folder which helps manage versioning and changelogs. I removed it as we are not focused on doing or optimizing releases now.

The workflows I kept:
- `rust.yml`: contains build and test, clippy, format, license checks, including `sui-execution-cut` for #34 
- `ci-docs.yml`: for https://github.com/iotaledger/kinesis/issues/28

Fixes https://github.com/iotaledger/kinesis/issues/10

## Open Questions:
1) The license check seems to be failing however with no reason shown in the CI. Any idea what the reason could be?´

2024-02-22 15:17 UTC, kodemartin requested changes

2024-02-23 00:55 UTC, BugFreeSoftware approved these changes

2024-02-23 14:55 UTC, valeriyr approved these changes

2024-02-23 15:56 UTC, kodemartin approved these changes
Thanks for the changes @samuel-rufi! As discussed in #37 please mind the conventional commit spec. I also suggest changing the `issue-10` prefix in the PR title with `[#10]` so that GH creates a link automatically.

2024-02-26 15:17 UTC, merged