feat(devx): Create tutorial for coffee example
iotaledger/iota pull request #2707
Opened 2024-09-18 14:23 UTC by Ginowine

# Description of change

This PR creates a tutorial based on the [Coffee Example](https://github.com/iotaledger/iota/blob/develop/examples/move/token/sources/coffee.move)

## Links to any relevant issues

fixes #2706 
fixes https://github.com/iotaledger/iota/issues/1840

## Type of change

- Documentation Fix

## How the change has been tested

- Docs were built locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-19 17:01 UTC, lucas-tortora requested changes
Lovely article, I love how many topics it introduces. We could consider moving it to the Getting Started section, wdyt?

2024-09-25 13:35 UTC, lucas-tortora requested changes
Just one comment on my end :)

2024-09-26 15:36 UTC, lucas-tortora approved these changes

2024-09-26 22:05 UTC, salaheldinsoliman approved these changes
@Ginowine Awesome article <3
Can the full contract be moved to the examples folder?

2024-09-27 11:46 UTC, Dr-Electron requested changes

2024-10-03 13:07 UTC, vivekjain23 approved these changes

2024-10-28 09:02 UTC, Dr-Electron approved these changes

2024-10-28 11:31 UTC, merged