feat(wallet,apps-backend): Kickoff features controller and include accounts finder
iotaledger/iota pull request #2724
Opened 2024-09-18 18:00 UTC by panteleymonchuk

Closes #1806

2024-09-18 18:38 UTC, brancoder requested changes
looks good just some growthbook config issue

2024-09-19 11:21 UTC, cpl121 requested changes

2024-09-19 11:41 UTC, cpl121 approved these changes

2024-09-19 12:08 UTC, brancoder approved these changes
LGTM :+1:

2024-09-19 12:58 UTC, merged