feat(docs): add interactive CTF challenges to docs
iotaledger/iota pull request #3014
Opened 2024-10-02 14:12 UTC by salaheldinsoliman

# Description of change

This PR references @fijter 's CTF challenges repo in the docs, alongside an interactive component that takes an `objectId`, and verifies it is the correct one. 

## Related Issues
Fixes #2831 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Docs built locally

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-04 13:37 UTC, vivekjain23 requested changes

2024-10-10 15:09 UTC, lucas-tortora requested changes
Great PR :)  Let's fine-tune the first example, and then we can replicate the updates all round.

2024-10-22 19:50 UTC, lucas-tortora requested changes

2024-10-23 17:38 UTC, lucas-tortora approved these changes
Still need to do some functional testing, but the articles look good to me :)

2024-10-25 12:05 UTC, Ginowine approved these changes
LGTM, well done.

2024-10-28 10:50 UTC, vivekjain23 approved these changes

2024-10-28 11:01 UTC, merged