refactor(iota-framework/iota-system): Remove multiple versions from the iota-system types
iotaledger/iota pull request #3048
Opened 2024-10-04 09:34 UTC by jkrvivian

# Description of change

This PR will be merged to the feature branch `core-node/feat/remove-multiple-types`.

Reduce amount of versioned types V2 to V1:
* SystemParametersV1
* IotaSystemStateInnerV1
* VotingPowerInfoV1

----

This PR also includes renaming changes in accordance with the rules:
* Add version postfix to those that will certainly be upgraded in the future.
* No version postfix to those that won't be new version.
* For the wrappers, we don't add `Wrapper` postfix.
* For inner types, we don't add `Inner`, just add version postfix `{structure}V1`.

### Structures with versioning:

* SystemParametersV1
* IotaSystemState (the wrapper)
* IotaSystemStateV1
* Validator (the wrapper)
* ValidatorV1
* ValidatorMetadataV1
* ValidatorSetV1
* ValidatorEpochInfoEventV1
* SystemEpochInfoEventV1
* StakingPoolV1
* PoolTokenExchangeRateV1
* StakedIotaV1
* StorageFundV1
* TimelockedStakedIotaV1
* VotingPowerInfoV1

### Structures that would not get changed, thus with no version postfix:

***** genesis *****
* GenesisValidatorMetadata
* GenesisChainParameters
* TokenDistributionSchedule
* TokenAllocation

***** validator cap *****
* UnverifiedValidatorOperationCap
* ValidatorOperationCap

***** validator *****
* ValidatorJoinEvent
* ValidatorLeaveEvent
* StakingRequestEvent
* UnstakingRequestEvent

## Links to any relevant issues

Close #2089 

## Type of change

- Enhancement
- Breaking change 

## How the change has been tested

Run the build and test commands:
* `iota move build`
* `iota move test`

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-10-08 14:28 UTC, miker83z approved these changes
Looks good!

2024-10-08 16:08 UTC, muXxer approved these changes

2024-10-08 17:39 UTC, lzpap requested changes
Since we modify the framework and don't intend to release a new protocol version for this, we should update the framework-snapshot bytes for protocol version 1. If this is not done then nodes will panic on startup that they have a different framework loaded from the snapshot than what is present in the node software.

We don't have to do this once we start bumping protocol versions, then we only create a new snapshot cut when the new protocol version is introduced.

2024-10-09 08:29 UTC, lzpap approved these changes

2024-10-09 09:30 UTC, merged