feat(iota-genesis-builder,iota-node): Genesis restructuring
iotaledger/iota pull request #3054
Opened 2024-10-04 13:51 UTC by miker83z

# Description of change

This PR implements a data migration mechanism that modifies the way the genesis is built and the way the node is started for the first time.
It fixes two main issues described in #2878:
- It avoids the creation of a huge transaction that can be fetched via RPC and DDOS nodes.
- it reduces the RAM usage on nodes during startup.

The changes are:
- `genesis.blob` now doesn't contain object coming from the Stardust migration.
- It contains a checkpoint that includes a list of transaction digests and transaction effects digests; among these, 1 transaction is the "main" genesis transaction that creates system packagess and token allocations, whilst, 9999 transactions are there to push Stardust migration objects into the state.
- These so called 9999 "migration transactions" are genereted during the genesis-build process and stored in a separate file `migration.blob`.
- During all startup operations, the node only uses the data contained in the `genesis.blob`; only when the `AuthorityStore` DB is opened for the first time, `migration.blob` is read and its transactions/objects pushed into the DB (the node uses `migration.blob` in other 2 not so relevant occasions, in the same startup context). 

## Links to any relevant issues

Closes #2878 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

1. `cargo run --release --bin iota genesis --working-dir ../test_iota_config -f --with-faucet --num-validators 1 --remote-migration-snapshots https://stardust-objects.s3.eu-central-1.amazonaws.com/iota/alphanet/latest/stardust_object_snapshot.bin.gz` 
(for using a local snapshot `cargo run --release --bin iota genesis --working-dir ../test_iota_config -f --with-faucet --num-validators 1 --local-migration-snapshots ../stardust_object_snapshot.bin`)
3. `cargo run --release --bin iota start --network.config ../test_iota_config`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-07 09:40 UTC, kodemartin requested changes
Hey @miker83z @Dkwcs great job overall!

Went through `iota_genesis_builder` as a first review iteration, and left a few suggestions. Most are minor, expect for the one about validating `MigrationTxData` while building `Genesis`. This relates to the WIP in #3041.

Will go over the rest of the implementation once #3041 is finished.

2024-10-08 16:39 UTC, kodemartin approved these changes
Looks good to me! Left a few final refactoring suggestions that I hope you find plausible.

2024-10-09 18:43 UTC, muXxer requested changes

2024-10-10 09:59 UTC, piotrm50 approved these changes

2024-10-15 22:08 UTC, muXxer approved these changes

2024-10-16 08:18 UTC, Thoralf-M approved these changes

2024-10-16 09:34 UTC, alexsporn approved these changes

2024-10-16 09:54 UTC, merged