feat (devx) - Add Quizzes to the About IOTA > Tokenomics Section
iotaledger/iota pull request #3055
Opened 2024-10-04 13:58 UTC by Ginowine

# Description of change

Added Quizzes to the About IOTA > IOTA Tokenomics section.

## Links to any relevant issues

fixes #2583

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-04 15:11 UTC, salaheldinsoliman approved these changes
LGTM

2024-10-07 05:29 UTC, vivekjain23 approved these changes

2024-10-07 08:22 UTC, vivekjain23 requested changes
Just a few spacing issues commented on, rest of everything looks good to me.

2024-10-08 11:50 UTC, lucas-tortora approved these changes

2024-10-11 12:27 UTC, vivekjain23 approved these changes

2024-10-14 16:02 UTC, lucas-tortora requested changes

2024-10-22 13:03 UTC, lucas-tortora approved these changes

2024-10-24 08:39 UTC, valeriyr approved these changes
LGTM! There is only one question about the changes of the tonic version.

2024-10-24 10:12 UTC, bingyanglin approved these changes

2024-10-25 12:54 UTC, merged