refactor(wallet): Add 24 word mnemonics
iotaledger/iota pull request #306
Opened 2024-05-20 15:12 UTC by brancoder

# Description of change

Add 24 word mnemonic for new and imported accounts 

## Links to any relevant issues

resolves #272 
resolves #273 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-05-21 11:36 UTC, marc2332 requested changes

2024-05-22 07:22 UTC, marc2332 requested changes
When creating I still get 12-word mnemonics 🤔 
![image](https://github.com/iotaledger/kinesis/assets/38158676/26282a9f-1067-48e0-ae61-9375dcd918fc)

2024-05-22 07:44 UTC, cpl121 requested changes
When I create a new wallet, it creates it with a 12-word mnemonic
![Captura de pantalla de 2024-05-22 09-07-20](https://github.com/iotaledger/kinesis/assets/100352899/064e4057-5e33-4b57-aeb7-f6e45b58ebdd)

2024-05-22 08:55 UTC, marc2332 approved these changes

2024-05-23 06:34 UTC, cpl121 approved these changes
Perfect! 👏🏼

2024-05-23 06:34 UTC, merged