chore(dependencies): Move dependencies once again
iotaledger/iota pull request #3085
Opened 2024-10-07 14:56 UTC by DaughterOfMars

# Description of change

Re-implements the changes from #1484

2024-10-07 17:40 UTC, miker83z approved these changes

2024-10-08 12:13 UTC, Thoralf-M requested changes
Doesn't compile
```
Caused by:
  failed to load manifest for dependency `iota-adapter-v0`

Caused by:
  failed to parse manifest at `/home/t/Desktop/iota/iota-execution/v0/iota-adapter/Cargo.toml`

Caused by:
  error inheriting `leb128` from workspace root manifest's `workspace.dependencies.leb128`

Caused by:
  `dependency.leb128` was not found in `workspace.dependencies`
```

2024-10-08 13:55 UTC, Thoralf-M approved these changes

2024-10-10 16:29 UTC, muXxer approved these changes

2024-10-15 13:34 UTC, samuel-rufi approved these changes

2024-10-16 13:48 UTC, alexsporn approved these changes

2024-10-16 14:56 UTC, merged