feat(iota-sdk): restructure examples
iotaledger/iota pull request #3110
Opened 2024-10-08 12:03 UTC by Thoralf-M

# Description of change

Restructure the sdk examples to bring some order

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/2156

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Running examples

2024-10-08 12:19 UTC, thibault-martinez requested changes
Please address the conflicting file

2024-10-09 08:48 UTC, thibault-martinez approved these changes

2024-10-09 12:38 UTC, DaughterOfMars reviewed
So there are now a bunch of folders with one example in each?

2024-10-09 13:12 UTC, DaughterOfMars approved these changes
Ah, I see now

2024-10-09 13:37 UTC, merged