feat(iota-json-rpc-tests): add coin read api tests
iotaledger/iota pull request #3113
Opened 2024-10-08 12:26 UTC by sergiupopescu199

# Description of change

Added the remaining `CoinReadApi` tests for the `iota-json-rpc-tests` crate

## Links to any relevant issues

fixes #2916 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

```rust
cargo nextest run -p iota-json-rpc-tests --test coin_api
```

Make sure to provide instructions for the maintainer as well as any relevant configurations.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2024-10-09 09:57 UTC, tomxey reviewed
Looks good in general.
Left comments with some improvement ideas.

2024-10-10 11:25 UTC, tomxey approved these changes
Thanks for fixing all the comments. LGTM 🐗

2024-10-11 05:53 UTC, kodemartin requested changes
Looks good @sergiupopescu199 generally! 

Left a few nit suggestions on code that was already there nevertheless.

Plus I noticed that `test_get_all_coins_limit_zero_with_env_var` is flaky with `cargo test`, probably on account of the single process used in the execution model. Please have a look.

I would also suggest to remove the `test_` prefix from the test functions.

2024-10-14 10:16 UTC, kodemartin approved these changes

2024-10-14 14:56 UTC, merged