chore(apps-backend): cleanup features
iotaledger/iota pull request #3172
Opened 2024-10-09 18:06 UTC by panteleymonchuk

Closes #2075

2024-10-11 07:19 UTC, marc2332 submitted a review, later dismissed
lgtm but the CI is failing

2024-10-15 16:49 UTC, begonaalvarezd requested changes

2024-10-17 14:02 UTC, begonaalvarezd approved these changes

2024-10-17 15:15 UTC, msarcev approved these changes

2024-10-17 15:15 UTC, merged