feat(wallet): improve staking flow by allowing full amount stake but display warning on low remainder gas
iotaledger/iota pull request #3184
Opened 2024-10-10 10:52 UTC by brancoder

# Description of change

- add stake full amount
- add loaders to stake buttons
resolves #3026

2024-10-10 10:54 UTC, marc2332 requested changes

2024-10-15 14:21 UTC, begonaalvarezd requested changes
great job, just added a minor comment

2024-10-21 07:58 UTC, begonaalvarezd requested changes
Amazing, just added the tiniest comment and this is ready to go

2024-10-21 08:49 UTC, begonaalvarezd approved these changes

2024-10-21 14:56 UTC, marc2332 approved these changes

2024-10-21 14:59 UTC, merged