feat(docs): add clt tutorial
iotaledger/iota pull request #3201
Opened 2024-10-10 21:47 UTC by Dr-Electron

# Description of change

Added the CLT tutorial following TAs suggestion to implement there example use case.

## Links to any relevant issues

Fixes #1839.

## Type of change

- Documentation Enhancement

## How the change has been tested

-

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-05 14:07 UTC, lucas-tortora commented
@Dr-Electron , is this ready for review?

2025-01-09 11:00 UTC, Dr-Electron commented
Yes 😅

2025-01-15 17:14 UTC, lucas-tortora requested changes
Great article :)

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```
````suggestion
```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L24-L33
```
````

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +# CLT Tutorial: A Journey from Zero to Hero
The title may be overselling a bit.

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This tutorial will guide you through the process of creating a Closed Loop Token (CLT) by following a journey to create a dApp for municipalities to issue vouchers for local businesses.
Please add a link to the main article.

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This tutorial will guide you through the process of creating a Closed Loop Token (CLT) by following a journey to create a dApp for municipalities to issue vouchers for local businesses.
```suggestion
This tutorial will guide you through the process of creating a Closed Loop Token (CLT) dApp for municipalities to issue vouchers for local businesses.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +The use case is the following:
```suggestion

The use case is:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Let's dive right into it. We can start by minting a new token. Tokens are similar to coins in IOTA, but you if you have read the prior pages you already know that they can have their own rules and po
```suggestion
Let's dive right into it. We can start by minting a new token. Tokens are similar to coins in IOTA, but if you have read the prior articles, you already know that they can have their own rules and policies.
```
Please add a link to:
the rules article, 
the policies article, 
the coin article.

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +But as they share similarities with coins, we can start by creating an `init` function with an OTW for our module and create a coin with a name, symbol, and description using `coin::create_currency`:
```suggestion

Since they share similarities with coins, we can start by creating an `init` function with an OTW for our module and create a coin with a name, symbol, and description using `coin::create_currency`:
```

Please add a link to `init` developer/iota-101/move-overview/#init , /developer/iota-101/move-overview/one-time-witness and /references/framework/iota-framework/coin#0x2_coin_create_currency

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +As tokens are special we need to talk about the token policy here. The token policy is an object which contains a `spend_balance` and the rules we define.
```suggestion
As tokens are special, we need to discuss the token policy. The token policy is an object that contains a `spend_balance` function and the rules we define.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +So it play an important role in the token lifecycle defining what the token owner can do and what not.
```suggestion
So, it plays an important role in the token lifecycle: defining what the token owner can and cannot do.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Let's create the policy and share it as a shared object later on:
```suggestion

Let's create the policy and share it as a shared object later on:

```
Please add a link to /developer/iota-101/objects/shared-owned#shared-objects

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +The `new_policy` function also return a policy capability that grants as some sort of admin rights. Similar to the treasury capability. More about that later.
```suggestion
The `new_policy` function also returns a policy capability that grants admin rights, similar to the treasury capability (more about that later)
```
Link to /references/framework/iota-framework/iota#struct-iotatreasurycap
and to the `later` part of the article

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +- send the policy capability to the caller
```suggestion
After creating the token and its policy, we:
- Freeze the coin metadata
- Send the treasury cap to the caller
- Share the token policy
- send the policy capability to the caller
```
It may be better to add the snippet after each action, to it's clearer to the end user.

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +But as they share similarities with coins, we can start by creating an `init` function with an OTW for our module and create a coin with a name, symbol, and description using `coin::create_currency`:
Could you wrap this section in an `init` or define policies header (or similar)?

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This is quite easy, we create a `gift_voucher` with the following header:
```suggestion
Now that we created the logic for initializing our module and creating the voucher token, the municipality could deploy the contract but not yet distribute the token. So, let's implement a function to do that.
This is relatively easy; we create a `gift_voucher` function that will mint the tokens and send them to the receiver:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```
````suggestion
```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L65-L75
```
````
I think it's clearer if we split the file by functions, wdyt?

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This means we have to confirm the transfer for which we have [multiple options](./action-request.mdx#approving-actions).
```suggestion
As you can see, the `token::transfer` function returns an `ActionRequest`. This object can not be dropped so without passing it to another function that destroys it the contract wouldn't work.
This means we have to confirm the transfer for which we have [multiple options](./action-request.mdx#approving-actions).
```
Please add a link to /references/framework/iota-framework/token#0x2_token_transfer and /references/framework/iota-framework/token#0x2_token_ActionRequest

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```
```suggestion
In this case, as the caller of the `gift_voucher` function is the municipality, we can approve the action directly using our treasury capability, as shown in the last line of the `gift_voucher` function.

```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L74
```
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +So in this case the transfer of the token is already "done", but if we don't consume the ActionRequest in the same tx, the whole transaction will fail as Move tx are atomic.
```suggestion
So, in this case, the token transfer is already "done," but if we don't consume the `ActionRequest` in the same transaction, the whole transaction will fail as the Move tx is atomic.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +:::note Interesting to know
```suggestion
:::info More on Move 
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This is done by creating a function `buy_ledbulb`:
```suggestion
This is achieved by creating a `buy_led_bulb` function in which we check if we have enough voucher tokens for a LED bulb and then transfer it to the shop:: 
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L79-L84
```suggestion
```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L79-L93
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +in which we check if we have enough voucher token for a LED bulb and then transfer it to the shop:
```suggestion
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```
```suggestion
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +But wait, remember that we said tokens are different from coins? With `token::spend` we again get a `ActionRequest` object which we have to approve.
```suggestion
Since tokens are different from coins, with `token::spend`, we again get an `ActionRequest` object, which we have to approve.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +As we should only be allowed as a household to spend the voucher token for LED bulbs in a certified shop.
```suggestion
This time, we can't approve with the treasury capability as the caller is the household. Even if we did have the treasury capability, since it grants admin rights, it would confirm everything without checking the rules. So, we actually want to use the policy rules feature, as a household should only be allowed to spend the voucher token for LED bulbs in a certified shop.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +We are going with the later as this allows us to reuse the rules for other projects as well.
```suggestion
We are going with the latter as this allows us to reuse the rules for other projects.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +But we also don't want shops to be able to spend the voucher token. They should only be allowed to send it back to the municipality.
```suggestion
But we also don't want shops to be able to spend the voucher token; they should only be allowed to send it back to the municipality.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +A [rule](rules.mdx#rule-structure) is representet as a witness - a type with a drop ability. So let's define that first:
```suggestion
A [rule](rules.mdx#rule-structure) is represented as a witness - a type with a `drop` ability. So let's define that first:
```
Link to /developer/iota-101/move-overview/structs-and-abilities/drop

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Now let's add a function to add addresses to the rule configuration:
```suggestion
Next, add a function to add addresses to the rule configuration:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +First we check if the token policy already has a rule configuration. If not we create a new one with `token::add_rule_config`
```suggestion
First, we check if the token policy already has a rule configuration. If not, we create a new one with `token::add_rule_config`
```
Link to /references/framework/iota-framework/token#0x2_token_add_rule_config

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Then we can get the mutable config with our helpter function config_mut which is just a wrapper of `token::rule_config_mut`.
```suggestion
Then we can get the mutable config with our `config_mut` helper function, which is just a wrapper of `token::rule_config_mut.`
```

/references/framework/iota-framework/token#function-rule_config_mut

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Next we have to create functionality to stamp the action request if the rule is met. This is done by adding a `verify` function to the rules module:
```suggestion
Next, we have to create functionality to stamp the action request if the rule is met. This is done by adding a `verify` function to the rules module:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Next we have to create functionality to stamp the action request if the rule is met. This is done by adding a `verify` function to the rules module:
I'm not sure about including the comments in the snippet, it may be better to add them as text in the article

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +3) If we don't abort, we stamp the action request.
```suggestion
1) Check if the policy has a rule config.
2) Get the config, sender, and receiver.
3) We split the verification into two parts: 
    - If the action is a `spend_action`, someone is trying to return the token to the municipality. We check if the sender is on our list. If this is true, we stamp the action request. If not, we abort as we only want to allow shops to return the token.
    - If the action is a `transfer_action`, someone is trying to buy a LED bulb. So, we check if the sender is on our list. If this is true, that means a shop is trying to spend our token. We can't allow that, so we abort and never stamp the action request.
    - We also check if the receiver is a shop.

4) If we don't abort, we stamp the action request.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +## Back to our voucher module
```suggestion
## Back to Our Voucher Module
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Now that we created the rules modules let's use it in our voucher module.
```suggestion
Now that we created the rules modules, let's use them in our voucher module.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +We can import the rules like this:
```suggestion
Since both modules belong to the same package, we can import the rules like this:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L37-L39
```suggestion
```move file=<rootDir>/docs/examples/move/clt-tutorial/sources/clt_tutorial.move#L38-L39
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +The municipality also needs a way to register shops so we add a function for that which internally calls the `add_addresses` function from our rules module:
```suggestion
We defined the rule for the default `spend` and `transfer` actions. 
But we could also pass any other action as a string here and make the rule work for custom functions of our module.

The municipality also needs a way to register shops. So, we should add a function which internally calls the `add_addresses` function from our rules module:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/examples/move/clt-tutorial/tests/clt_tutorial_tests.move
> +            let (led_bulb, action_request) = buy_ledbulb(voucher, &policy, shop2, scenario.ctx());
```suggestion
            let (led_bulb, action_request) = buy_led_bulb(voucher, &policy, shop2, scenario.ctx());
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/examples/move/clt-tutorial/tests/clt_tutorial_tests.move
> +            let (led_bulb, action_request) = buy_ledbulb(voucher, &policy, shop, scenario.ctx());
```suggestion
            let (led_bulb, action_request) = buy_led_bulb(voucher, &policy, shop, scenario.ctx());
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/examples/move/clt-tutorial/tests/clt_tutorial_tests.move
> +        buy_ledbulb,
```suggestion
        buy_led_bulb,
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/examples/move/clt-tutorial/sources/clt_tutorial.move
> +    public fun buy_ledbulb(
```suggestion
    public fun buy_led_bulb(
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +This is similar to the `buy_ledbulb` function where we verify the rules of the `transfer` action, but in this case we use the `spend` action.
```suggestion
This is similar to the `buy_led_bulb` function, where we verify the rules of the `transfer` action. But, in this case, we use the `spend` action.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +So in this case in a PTB we have to call the `token_policy::confirm_request` function afterwards which will check the request for the approval stamp and make our TX succeed.
```suggestion
So, in this case, we have to call the `token_policy::confirm_request` function in a PTB afterward, which will check the request for the approval stamp and make our TX succeed.
```
LInk to /developer/iota-101/transactions/ptb/programmable-transaction-blocks-overview

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +And now we are back to our `buy_ledbulb` function. We can now verify/stamp the action request with the rules capability:
```suggestion
And now we are back to our `buy_led_bulb` function. We can now verify/stamp the action request with the rules capability:
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Now the shop is the owner is the owner of the voucher and the household just got a new energy-efficient LED bulb.
```suggestion
Now the shop owns the voucher, and the household just got a new energy-efficient LED bulb.
```

2025-01-15 17:14 UTC, lucas-tortora commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +So the token will be consumed and the `spend_balance` will be added to the the action request. Once the action got confirmed the `spend_balance` will be added to the balance of the token policy.
```suggestion
So, the token will be consumed, and the `spend_balance` will be added to the action request. Once the action is confirmed, the `spend_balance` will be added to the balance of the token policy.
```

2025-01-20 12:58 UTC, Dr-Electron commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +# CLT Tutorial: A Journey from Zero to Hero
Haha, it is a place holder from a joke with Adrian 😅 
Will remove it 😆

2025-01-31 09:03 UTC, Dr-Electron commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +Next we have to create functionality to stamp the action request if the rule is met. This is done by adding a `verify` function to the rules module:
9339fc581e

2025-01-31 09:04 UTC, Dr-Electron commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +# CLT Tutorial: Voucher
```suggestion
# Voucher Tutorial
```

2025-02-21 13:00 UTC, lucas-tortora approved these changes

2025-02-24 15:09 UTC, Ginowine requested changes
Great tutorial, LGTM. Just few commas needed.

2025-02-24 15:09 UTC, Ginowine commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +As you can see, the [`token::transfer`](../../../references/framework/iota-framework/token.mdx#function-transfer) function returns an [`ActionRequest`](../../../references/framework/iota-framework/to
```suggestion
As you can see, the [`token::transfer`](../../../references/framework/iota-framework/token.mdx#function-transfer) function returns an [`ActionRequest`](../../../references/framework/iota-framework/token.mdx#struct-actionrequest). This object can not be dropped, so without passing it to another function that destroys it, the contract wouldn't work.
```

2025-02-24 15:09 UTC, Ginowine commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +The `ActionRequest` objects gives us the chance to get a deeper understanding of Move.
```suggestion
The `ActionRequest` object gives us the chance to get a deeper understanding of Move. 
```

2025-02-24 15:09 UTC, Ginowine commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +The municipality is now able to create a voucher and transfer it to a household. Next we need to implement a way for the household to redeem the voucher.
```suggestion
The municipality is now able to create a voucher and transfer it to a household. Next, we need to implement a way for the household to redeem the voucher.
```

2025-02-24 15:09 UTC, Ginowine commented on docs/content/developer/standards/closed-loop-token/tutorial.mdx
> +And as a last step we add the address to our bag.
```suggestion
And as a last step, we add the address to our bag.
```

2025-02-25 16:49 UTC, Ginowine approved these changes

2025-03-03 19:50 UTC, merged