Add button to connect IOTA wallet
iotaledger/iota pull request #3204
Opened 2024-10-10 22:04 UTC by Dr-Electron

# Description of change

Add Connect Wallet Button to the top right

## Links to any relevant issues

Fixes #3203 

## Type of change

- Documentation Enhancement

## How the change has been tested

Tested locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-10 23:03 UTC, Dr-Electron commented
Open questions: 

- [x] Is there a way to pass props to the global provider? For example the autoconnect option for the wallet provider? Or do we need to enable it globally which could be annoying for users I guess 🤔 
- [x] I still didn't figure out what accounts exactly are. I thought it's just like different addresses on a single mnemonic. But although I have two it doesn't really work with the interactive components. Are accounts really two different mnemonics?

2024-10-18 12:23 UTC, vivekjain23 reviewed
The Button's styles in Modal should be the same as we did ConnectButton.mdx

2024-12-05 14:07 UTC, lucas-tortora commented
@Dr-Electron , could you resolve the conflicts?

2025-01-08 13:51 UTC, lucas-tortora requested changes
not sure if it's related to this PR or if it just needs an updated, but I'm getting `ReferenceError: useIotaClient is not defined` in `useSignTransaction` and 
`ReferenceError: useReportTransactionEffects is not defined` in `useReportTransactionEffects`.

2025-01-08 13:51 UTC, lucas-tortora commented on docs/content/references/ts-sdk/dapp-kit/wallet-hooks/useAccounts.mdx
> +}
Unrelated to your PR technically, but could you remove the `-` in the `li`. It also happens in `useWallets` .

![image](https://github.com/user-attachments/assets/3e1fa27c-be3e-4dce-a1ae-88282d2f214d)

2025-01-09 10:58 UTC, Dr-Electron commented
Converted to draft as I will wait for the [fix](https://github.com/iotaledger/iota/issues/4698) from tooling

2025-01-19 15:35 UTC, Dr-Electron commented on docs/content/references/ts-sdk/dapp-kit/wallet-hooks/useAccounts.mdx
> +}
Fixed in e01cc28

2025-01-21 14:59 UTC, begonaalvarezd commented
> Converted to draft as I will wait for the [fix](https://github.com/iotaledger/iota/issues/4698) from tooling

https://github.com/iotaledger/iota/issues/4698 merged

2025-01-31 12:06 UTC, lucas-tortora approved these changes

2025-02-05 12:02 UTC, vivekjain23 approved these changes

2025-02-10 19:41 UTC, merged