feat!(iota): remove KeyToolCommand::{LoadKeypair, Unpack}
iotaledger/iota pull request #3223
Opened 2024-10-11 16:06 UTC by Thoralf-M

# Description of change

Remove the unused and rather useless LoadKeypair and Unpack commands.
One can use `iota keytool convert` and `iota keytool show` to get the same information and to create a file/read from it one can use standard shell commands like these:
```
echo iotaprivkey1qqjgggrq47cgdp2x6wnuy6m5qud66pj9l3m0yt8vj23vs99c73xzcp5t0dd > priv.key
iota keytool convert "$(< priv.key)"
```

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/3214

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-11 16:44 UTC, DaughterOfMars approved these changes

2024-10-14 13:34 UTC, lucas-tortora approved these changes

2024-10-14 13:46 UTC, thibault-martinez requested changes
temporary block

2024-10-29 09:38 UTC, thibault-martinez approved these changes

2024-10-29 10:32 UTC, merged