feat(tooling-ci): run CI check on pnpm dependency changes.
iotaledger/iota pull request #3314
Opened 2024-10-15 14:31 UTC by panteleymonchuk

Closes #2505

2024-10-16 13:52 UTC, marc2332 requested changes

2024-10-21 11:10 UTC, VmMad requested changes

2024-10-21 15:27 UTC, VmMad approved these changes
lgtm

2024-10-24 13:34 UTC, marc2332 approved these changes
lgtm but clean up the testing things

2024-10-24 15:07 UTC, begonaalvarezd approved these changes

2024-10-24 15:15 UTC, msarcev approved these changes

2024-10-24 15:39 UTC, begonaalvarezd approved these changes

2024-10-24 15:39 UTC, merged