chore(core-node): Remove MultiSigLegacy
iotaledger/iota pull request #3375
Opened 2024-10-17 09:15 UTC by hmoog

# Description of change

This PR removes the old legacy MultiSig implementation.

fixes [#(3346)](https://github.com/iotaledger/iota/issues/3346)

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-17 15:16 UTC, miker83z requested changes
Looks good, just some small changes

2024-10-18 09:58 UTC, Thoralf-M approved these changes

2024-10-18 13:54 UTC, DaughterOfMars approved these changes

2024-10-18 14:13 UTC, miker83z approved these changes

2024-10-21 07:49 UTC, merged