remove(node): remove `random_beacon` feature flag and deprecated store tables
iotaledger/iota pull request #3383
Opened 2024-10-17 11:50 UTC by muXxer

# Description of change

This PR removes the deprecated protocol feature flag `random_beacon`. 
We don't need the backwards compatibility to former protocol versions.

Removing the flag enabled to remove some deprecated store tables as well.

## Links to any relevant issues

#3253

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-10-17 13:45 UTC, alexsporn submitted a review, later dismissed

2024-10-17 14:36 UTC, alexsporn approved these changes

2024-10-17 16:00 UTC, Thoralf-M approved these changes

2024-10-18 10:09 UTC, miker83z approved these changes

2024-10-18 11:14 UTC, sergiupopescu199 approved these changes
lgtm ✨

2024-10-18 11:22 UTC, kodemartin requested changes
@muXxer since I understand randomness is disabled, I suggest

* Removing the `transactions/random.*` tests in `iota-graphql-e2e-tests`
* Remove the `SetRandomStateCommand` in `iota-transactional-test-runner`.

2024-10-18 11:40 UTC, kodemartin approved these changes
lgtm :crab:

2024-10-18 14:28 UTC, DaughterOfMars approved these changes

2024-10-18 14:30 UTC, merged