feat (devx) - Add Quizzes to Developer >  EVM to Move Section
iotaledger/iota pull request #3394
Opened 2024-10-17 14:04 UTC by Ginowine

# Description of change

Add Quizzes to the Developer > EVM to Move Section.

## Links to any relevant issues

fixes #2592 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-21 05:41 UTC, vivekjain23 approved these changes
LGTM :)

2024-10-21 12:09 UTC, lucas-tortora requested changes

2024-10-24 15:43 UTC, salaheldinsoliman approved these changes
Looks good 🤝

2024-10-25 13:57 UTC, lucas-tortora approved these changes

2024-10-25 16:06 UTC, merged