feat(scripts): add script to update generated files
iotaledger/iota pull request #3423
Opened 2024-10-17 16:43 UTC by muXxer

# Description of change

I'm annoyed that I always forget how to generate `open-rpc` and `graphql` specs, and how to generate the typescript files that are based on those specs, so I added a script for everyone.

It uses a docker container, so we don't need to have `node`, `npm` and `pnpm` installed locally.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

It generates the expected files.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-10-17 16:46 UTC, alexsporn approved these changes

2024-10-17 17:52 UTC, samuel-rufi approved these changes

2024-10-18 08:12 UTC, begonaalvarezd requested changes
When running the script without arguments `./update_generated_files.sh` im getting the following errors:

```bash
Write schema to file: "./crates/iota-graphql-rpc/schema.graphql"
Copying generated graphlql schema to sdk folder...
Installing typescript sdk dependencies...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Installing graphql-transport dependencies...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Updating open rpc schema...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Updating graphql schema in 'client/types/generated.ts'...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Updating graphql schema using gql.tada...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Generating graphql-transport typescript types...
docker: Error response from daemon: create ../..: "../.." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

2024-10-22 13:28 UTC, miker83z approved these changes

2024-10-22 14:54 UTC, begonaalvarezd approved these changes

2024-10-25 08:59 UTC, msarcev approved these changes

2024-10-25 09:52 UTC, merged