fix(iota-protocol-config): remove recompute_has_public_transfer_in_execution flag and related checks, snapshot have been updated
iotaledger/iota pull request #3446
Opened 2024-10-18 09:44 UTC by Dkwcs

# Description of change

recompute_has_public_transfer_in_execution flag has been removed with according checks. 

## Links to any relevant issues

Fix #3428 .

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

`./scripts/update_all_snapshots.sh`

2024-10-18 09:53 UTC, Thoralf-M approved these changes

2024-10-18 10:07 UTC, alexsporn approved these changes

2024-10-18 10:16 UTC, valeriyr approved these changes
LGTM!

2024-10-18 13:07 UTC, DaughterOfMars approved these changes

2024-10-18 14:01 UTC, miker83z approved these changes

2024-10-18 14:03 UTC, miker83z requested changes

2024-10-21 09:25 UTC, muXxer approved these changes

2024-10-21 12:07 UTC, muXxer approved these changes

2024-10-21 15:07 UTC, miker83z approved these changes

2024-10-21 15:31 UTC, merged