remove(node): remove deprecated `TransactionKind::ChangeEpoch()`
iotaledger/iota pull request #3452
Opened 2024-10-18 10:30 UTC by alexsporn

# Description of change

This removes the deprecated `TransactionKind::ChangeEpoch()` variant since it is now part of the `TransactionKind::EndOfEpochTransaction(Vec<EndOfEpochTransactionKind>)` (The `ChangeEpoch` struct is still used in `EndOfEpochTransactionKind::ChangeEpoch(ChangeEpochTransaction)`).

## Links to any relevant issues

Fixes  #3391

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Ran node and tests locally.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-18 12:43 UTC, muXxer approved these changes

2024-10-18 13:56 UTC, miker83z requested changes
Just a couple of small changes!

2024-10-21 10:20 UTC, muXxer approved these changes

2024-10-21 11:33 UTC, Thoralf-M approved these changes

2024-10-21 12:33 UTC, miker83z approved these changes

2024-10-21 14:24 UTC, samuel-rufi approved these changes

2024-10-21 14:36 UTC, merged