fix(iota-json-rpc-tests): Fix unstaking and timelocked_unstaking tests
iotaledger/iota pull request #3471
Opened 2024-10-18 15:42 UTC by samuel-rufi

# Description of change

Fixes the `unstaking` and `timelocked_unstaking` tests.

The reason for the tests failing is that the test cluster is configured with a fixed epoch duration and while running multiple tests at the same time it can happen that the object refs for the stake objects invalidate by multiple versions.

To make sure we can run certain logic in a specific epoch, we should avoid building the cluster with a fixed epoch duration and force epoch transitions directly with `Cluster::force_new_epoch`.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/3007

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo simtest -p iota-json-rpc-tests --test governance_api`
`cargo nextest run -p iota-json-rpc-tests --test governance_api`

## Change checklist

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-10-21 09:52 UTC, tomxey requested changes

2024-10-21 14:23 UTC, tomxey approved these changes
lgtm 🐠

2024-10-21 14:27 UTC, sergiupopescu199 approved these changes
lgtm ✨

2024-10-22 21:55 UTC, muXxer approved these changes

2024-10-24 08:15 UTC, alexsporn approved these changes

2024-10-24 08:21 UTC, merged