fix(sui-genesis-builder): Adjust circulating supply eventually with token adjustment ratio
iotaledger/iota pull request #359
Opened 2024-05-21 14:45 UTC by samuel-rufi

# Description of change

The logic added in this PR will check if the circulating supply (U256) is larger than the adjusted maximum supply (u64) and eventually creates a token adjustment ratio.

## Links to any relevant issues

Fixes https://github.com/iotaledger/kinesis/issues/355

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Provided tests.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-05-27 13:10 UTC, kodemartin requested changes
Hey @samuel-rufi, looks great!

I would only suggest simplifying the API by limiting the cost of the `SimpleTokenSchemeU64`  (see more specific comments) and *not* passing the token-adjustment ratio in the `Executor`. Instead you can rely on the passed `FoundryOutput` to recalculate it.

As we move towards the new guidelines please also:

* Add documentation to whatever is public in this patch.
* Implement eagerly the most common traits for new types. [C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits)

2024-05-28 07:42 UTC, kodemartin reviewed
Something seems still off @samuel-rufi.

2024-05-29 08:19 UTC, kodemartin submitted a review, later dismissed
Looks good @samuel-rufi!

I think there is still is a [problem](https://github.com/iotaledger/kinesis/pull/359#discussion_r1618361674), at least in theory, but we can discuss and resolve this in a dedicated issue.

2024-05-29 09:12 UTC, Thoralf-M approved these changes

2024-05-29 09:13 UTC, kodemartin approved these changes

2024-05-29 09:20 UTC, merged