feat(iota-indexer): add move_utils tests
iotaledger/iota pull request #3599
Opened 2024-10-23 16:00 UTC by sergiupopescu199

# Description of change

Add `MoveUtils` tests for `iota-indexer`

## Links to any relevant issues

#2200 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

- Start a **postgres** instance using this command:
 ```sh
 docker run --name iota-indexer-tests -e POSTGRES_PASSWORD=postgrespw -e POSTGRES_USER=postgres -e POSTGRES_DB=iota_indexer -d -p 5432:5432 postgres
 ```

- run tests:
```sh
  cargo test -p iota-indexer --test rpc-tests move_utils --features shared_test_runtime
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2024-10-24 08:30 UTC, kodemartin requested changes
Looks good @sergiupopescu199 ! I simply think that you should implement `PartialEq` on the types directly.

2024-10-25 11:58 UTC, samuel-rufi requested changes
Looks good. Just the comment that @kodemartin mentioned about the custom eq.

2024-10-28 08:42 UTC, tomxey approved these changes
lgtm 🎃

2024-10-28 09:26 UTC, samuel-rufi approved these changes

2024-10-28 10:01 UTC, merged