feat(wallet-dashboard): Add navigation
iotaledger/iota pull request #361
Opened 2024-05-21 15:13 UTC by cpl121

# Description of change

Add navigation

## Links to any relevant issues

Closes #281 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Go to dashboard route and check if the navigation works

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-05-21 15:25 UTC, marc2332 requested changes

2024-05-22 06:54 UTC, marc2332 requested changes

2024-05-22 09:20 UTC, marc2332 requested changes

2024-05-22 09:49 UTC, marc2332 requested changes

2024-05-22 09:53 UTC, marc2332 requested changes

2024-05-22 09:58 UTC, marc2332 requested changes
The rest looks good!

2024-05-22 10:02 UTC, marc2332 approved these changes
✅

2024-05-22 11:51 UTC, evavirseda approved these changes
:rocket:

2024-05-22 12:53 UTC, msarcev approved these changes

2024-05-22 13:05 UTC, merged