feat(docs): Add abilities from the Move book
iotaledger/iota pull request #3629
Opened 2024-10-24 12:41 UTC by salaheldinsoliman

# Description of change

Add docs about structs and abilities from the move book, and link it to our docs

## Links to any relevant issues

Related to #3744 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## How the change has been tested

Docs built locally

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-10-25 11:28 UTC, lucas-tortora requested changes
Great addition :)

2024-10-29 14:37 UTC, lucas-tortora requested changes

2024-11-04 11:07 UTC, vivekjain23 requested changes

2024-11-05 06:19 UTC, vivekjain23 reviewed
Please add `Title` and  `Description` to other pages as well, the rest looks good to me. Good Work 👍

2024-11-07 20:08 UTC, lucas-tortora requested changes

2024-11-11 13:51 UTC, lucas-tortora approved these changes

2024-11-12 14:45 UTC, Ginowine approved these changes

2024-11-13 05:00 UTC, vivekjain23 approved these changes

2024-11-13 11:15 UTC, merged