feat(wallet): Add import account from seed
iotaledger/iota pull request #368
Opened 2024-05-22 14:38 UTC by brancoder

# Description of change

Adds functionality to import account from seed and also to derive accounts from seed.
resolves #275  

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-05-23 13:44 UTC, marc2332 requested changes

2024-05-28 06:46 UTC, marc2332 reviewed
Do you mind sharing a seed for us to easily test this?

2024-05-28 10:13 UTC, marc2332 requested changes

2024-05-29 08:32 UTC, marc2332 approved these changes

2024-05-29 10:17 UTC, cpl121 approved these changes

2024-05-29 10:17 UTC, merged