feat(wallet-dashboard): add list of coins
iotaledger/iota pull request #371
Opened 2024-05-22 18:29 UTC by panteleymonchuk

# Description of change

Closes #282 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-05-23 08:30 UTC, cpl121 requested changes

2024-05-23 09:50 UTC, marc2332 requested changes
Can you redo the `useBalance` and `useCoins` hooks using react-query? Let me know if you want some help

2024-05-23 11:24 UTC, marc2332 requested changes

2024-05-24 06:06 UTC, evavirseda requested changes

2024-05-24 06:58 UTC, marc2332 requested changes

2024-05-24 11:48 UTC, marc2332 requested changes

2024-05-24 12:05 UTC, evavirseda requested changes
just one little detail :pray:

2024-05-24 13:21 UTC, marc2332 approved these changes

2024-05-24 13:22 UTC, evavirseda approved these changes
:rocket:

2024-05-24 15:16 UTC, marc2332 requested changes

2024-05-24 15:43 UTC, cpl121 approved these changes

2024-05-27 07:04 UTC, marc2332 approved these changes

2024-05-27 07:08 UTC, merged