fix(docs): Correct all occurrences of toml code blocks
iotaledger/iota pull request #3713
Opened 2024-10-28 13:00 UTC by vivekjain23

# Description of change

Fixing all occurrences of `toml` code blocks by swizzling the `prism-include-languages.js` component and adding a custom `prism-toml.js` component to it.

## Links to any relevant issues

fixes #1947 

## Type of change

- Documentation Fix

## How the change has been tested

Changes were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-10-29 14:29 UTC, lucas-tortora requested changes
The codeblocks are displaying as plain text (no syntax highlights). Please take a look at https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages and add the necessary config for [prism](https://prismjs.com/#supported-languages)

2024-11-04 16:35 UTC, lucas-tortora requested changes

2024-11-05 14:04 UTC, lucas-tortora approved these changes

2024-11-08 10:19 UTC, Ginowine approved these changes

2024-11-08 10:52 UTC, merged