feat(wallet-dashboard): add grid for visual assets
iotaledger/iota pull request #3758
Opened 2024-10-29 13:15 UTC by VmMad

Fixes #3692 
Fixes #3924

Depends on #3724

2024-10-29 17:21 UTC, evavirseda requested changes

2024-10-30 10:08 UTC, evavirseda approved these changes

2024-11-06 09:29 UTC, marc2332 requested changes
I forgot to actually put the review..

2024-11-06 17:02 UTC, cpl121 approved these changes

2024-11-07 10:43 UTC, marc2332 approved these changes

2024-11-07 10:43 UTC, merged