feat(apps-backend, tooling-ci): Add e2e tests to apps backend
iotaledger/iota pull request #3760
Opened 2024-10-29 13:32 UTC by panteleymonchuk

Closes #3582

2024-10-30 14:10 UTC, thibault-martinez approved these changes
Workflow LGTM

2024-11-05 08:09 UTC, msarcev requested changes

2024-11-12 09:45 UTC, msarcev approved these changes

2024-11-12 10:01 UTC, begonaalvarezd approved these changes

2024-11-12 11:40 UTC, merged