feat(wallet-dashboard): add styles for Review & Send screen
iotaledger/iota pull request #3787
Opened 2024-10-30 11:25 UTC by VmMad

Fixes #3689 

Depends on #3832

2024-11-11 08:52 UTC, brancoder requested changes
Looks great just a few minor polishes :+1:

2024-11-12 10:36 UTC, brancoder requested changes

2024-11-13 10:54 UTC, evavirseda requested changes
I just noticed two things:
1. if I send 10 IOTAs, it's not formatting correctly because the actual amount being sent is 0.0000001
![image](https://github.com/user-attachments/assets/2af6816b-6b96-4c0b-9e2c-5563d9f633ca)
![image](https://github.com/user-attachments/assets/b06d0039-b245-4c92-a8ef-19268bfcfa16)

2. this looks weird :see_no_evil: 
![image](https://github.com/user-attachments/assets/60b2bb2b-f2dc-49fc-b964-a41f963526d4)

2024-11-13 13:57 UTC, cpl121 requested changes
conflicts 🙏🏼

2024-11-15 15:35 UTC, marc2332 requested changes
just some code improvement, rest lgtm!

2024-11-18 11:56 UTC, evavirseda approved these changes

2024-11-18 11:59 UTC, marc2332 approved these changes

2024-11-20 10:45 UTC, brancoder requested changes
Looks good just a nit with send screen

2024-11-20 10:45 UTC, brancoder commented on apps/core/src/components/Inputs/SendTokenFormInput.tsx
> +            }
with this change the GAS SYMBOL is always show even when there is no estimation:
before:
![image](https://github.com/user-attachments/assets/316faf12-3f11-4367-a09a-aca9b4d0cbdb)

after:
![image](https://github.com/user-attachments/assets/f9e84e23-6d04-4e2b-90fd-20c8c776faa4)

2024-11-20 12:46 UTC, brancoder requested changes
lint :pray:

2024-11-20 13:14 UTC, brancoder approved these changes
LGTM  nice job :rocket:

2024-11-20 13:44 UTC, cpl121 requested changes

2024-11-20 13:44 UTC, cpl121 commented on apps/core/src/components/coin/CoinIcon.tsx
> +    hasCoinWrapper?: boolean;
could we add this prop to the coin selector too?

2024-11-20 13:44 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +                onBack={step === FormStep.ReviewValues ? onBack : undefined}
This back button resets the form to the previous view

2024-11-20 13:44 UTC, cpl121 commented on apps/wallet-dashboard/components/coins/MyCoins.tsx
> +import { SendTokenDialog } from '../Dialogs/SendToken/SendTokenDialog';
why this import instead of '@/components'?

2024-11-20 13:44 UTC, cpl121 commented on apps/wallet-dashboard/next.config.mjs
> +        domains: ['d315pvdvxi2gex.cloudfront.net', 'd122fl2kiki5hg.cloudfront.net'],
not needed I think

2024-11-20 17:01 UTC, cpl121 requested changes

2024-11-20 17:01 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +    console.log({ formData });
unnecessary log

2024-11-20 17:01 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/views/EnterValuesFormView.tsx
> +                    formattedAmount: initialFormValues.formattedAmount ?? '',
same logic for `isPayAllIota` right?

2024-11-21 08:55 UTC, VmMad commented on apps/wallet-dashboard/components/Dialogs/SendToken/views/EnterValuesFormView.tsx
> +                    formattedAmount: initialFormValues.formattedAmount ?? '',
we are going to remove this so it's not important

2024-11-21 14:51 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/views/EnterValuesFormView.tsx
> +                    formattedAmount: initialFormValues.formattedAmount ?? '',
true!

2024-11-21 15:02 UTC, cpl121 requested changes

2024-11-21 15:02 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
>      const { data: transaction } = useSendCoinTransaction(
To generate the tx, we need to share the `formData.formattedAmount` instead of the `formData.amount`. If not, we are sending the amount in nano

2024-11-21 15:18 UTC, cpl121 approved these changes

2024-11-21 15:19 UTC, merged