feat(wallet-dashboard): style send entry screen
iotaledger/iota pull request #3807
Opened 2024-10-30 17:43 UTC by cpl121

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Closes #3688 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-08 13:00 UTC, brancoder requested changes
Looks good but validation needs just a few tweaks :+1:  
There is validation issue where sender address is not validated on change:
![image](https://github.com/user-attachments/assets/df1eb3ed-5b3d-405e-a8cf-c37de96a1efd)
Steps to repro:
1. open send token form
2. click on max button
3. paste address in sender field and start deleting the address characters with backspace

2024-11-11 11:56 UTC, marc2332 requested changes

2024-11-11 16:06 UTC, marc2332 requested changes

2024-11-12 14:41 UTC, marc2332 requested changes

2024-11-13 09:00 UTC, brancoder requested changes
this validation issue is still present in this PR but doesnt exist in develop:
https://github.com/iotaledger/iota/pull/3807#pullrequestreview-2423735946

2024-11-13 10:36 UTC, evavirseda requested changes
:pray: :pray:

2024-11-14 08:35 UTC, brancoder requested changes
Max button is disabled if there is no amount in the input field: 
![image](https://github.com/user-attachments/assets/391e7dfd-4300-40eb-bf2d-bd3d9bae213b)
![image](https://github.com/user-attachments/assets/c1194c03-ce20-407a-8372-b1bec2cb8306)

2024-11-14 11:32 UTC, brancoder requested changes
lint issues :pray:

2024-11-14 11:33 UTC, marc2332 requested changes
All usages of `ComponentProps<typeof Field>` are wrong, they all resolve to `any`, correct way would be to use Formik's `FormikProps` type, example:

```ts
  form: FormikProps<typeof INITIAL_VALUES>;
```

This is a random example, you should probably use a generic type instead of INITIAL_VALUES

2024-11-15 10:42 UTC, evavirseda approved these changes

2024-11-15 12:32 UTC, brancoder requested changes
the responsiveness issue is still there :pray: 
https://github.com/iotaledger/iota/pull/3807#pullrequestreview-2423735946

2024-11-15 15:20 UTC, marc2332 approved these changes

2024-11-18 16:25 UTC, brancoder requested changes
Looks good just a few validation polishes :pray:

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/AddressInput.tsx
> +    }, [field.value]);
```suggestion
```

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/AddressInput.tsx
> +            helpers.setValue(iotaAddressValidation.cast(address));
```suggestion
            helpers.setValue(iotaAddressValidation.cast(address)).then(() => {
                validateField(name);
            });
```
in this way we validate just this field in question doing something like this helpers.setValue(iotaAddressValidation.cast(address), true) would validate the entire form

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/AddressInput.tsx
> +        [name, iotaAddressValidation, helpers.setTouched, helpers.setValue, validateField],
```suggestion
        [name, iotaAddressValidation],
```

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/AddressInput.tsx
> +    const errorMessage = meta.touched && meta.error;
```suggestion
    const errorMessage = meta.error;
```

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/SendTokenFormInput.tsx
> +    const isActionButtonDisabled = isSubmitting || !!errorMessage || isMaxActionDisabled;
```suggestion
            const isActionButtonDisabled = isSubmitting || isMaxActionDisabled;
```
we should remove the ` !!errorMessage` because max button is disabled if there is an error message
![image](https://github.com/user-attachments/assets/b6559e4a-1ea8-4d5c-9786-6419cff800ee)

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/SendTokenFormInput.tsx
> +    }, [field.value, meta.touched]);
```suggestion
```

2024-11-18 16:25 UTC, brancoder commented on apps/core/src/components/Inputs/SendTokenFormInput.tsx
> +                helpers.setValue(values.value);
```suggestion
                helpers.setValue(values.value).then(() => {
                    validateField(name);
                });
```

2024-11-18 16:25 UTC, brancoder commented on apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
We should update this form to use AddressInput component, like in send coin form, instead of
```
<Field
                                component={AddressInput}
                                allowNegative={false}
                                name="to"
                                placeholder="Enter Address"
                            />
```
change to 
`
<AddressInput name="to" placeholder="Enter Address" />`

because the error is thrown here
![image](https://github.com/user-attachments/assets/677ec350-7108-42e7-bc57-356719538445)

2024-11-19 07:43 UTC, marc2332 commented on apps/core/src/components/Inputs/AddressInput.tsx
> +            helpers.setValue(iotaAddressValidation.cast(address));
damn it, I didn't realize setValue returned a promise

2024-11-19 07:43 UTC, marc2332 commented on apps/core/src/components/Inputs/AddressInput.tsx
> +            helpers.setValue(iotaAddressValidation.cast(address));
we should do something cleaner tho

```ts
await helpers.setValue(iotaAddressValidation.cast(address))
validateField(name);
```

2024-11-19 07:44 UTC, marc2332 commented on apps/core/src/components/Inputs/SendTokenFormInput.tsx
> +                helpers.setValue(values.value);
same as above

2024-11-19 07:44 UTC, marc2332 commented on apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
💯 I missed that one

2024-11-19 08:49 UTC, brancoder requested changes
Lint issues :pray:

2024-11-19 13:47 UTC, brancoder requested changes
We are getting there, just an issue with formik in dashboard:
1. click send 
2. click max button
![image](https://github.com/user-attachments/assets/70c411ef-63dc-43f4-895b-b9889e2174ab)

2024-11-20 09:43 UTC, brancoder approved these changes
LGTM :rocket:  :raccoon:

2024-11-20 10:17 UTC, VmMad requested changes
LGTM, just a small thing. Remove the default exports from the dashboard and core, and do `export *` in the index files.

Also, we should avoid exporting things that are not components from component files, and instead move them to other files if they are necessary to export. Just so we don't break HMR

2024-11-20 10:41 UTC, panteleymonchuk approved these changes

2024-11-20 10:51 UTC, marc2332 commented
ci failing

2024-11-20 11:06 UTC, VmMad approved these changes
LGTM

2024-11-20 11:16 UTC, merged