feat(tooling-ci): Improved explorer release process
iotaledger/iota pull request #3812
Opened 2024-10-31 09:10 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/1898

1. Disable automatic production deploys when merged into `develop`
2. Enable automatic staging deploys when merged into `develop`
3. Embed the current commit hash in the explorer footer

2024-10-31 09:56 UTC, thibault-martinez requested changes
Please change the confluence page `CI Architecture` accordingly

2024-11-04 15:00 UTC, begonaalvarezd approved these changes

2024-11-04 15:36 UTC, begonaalvarezd requested changes
staging is failing 🙏🏼

2024-11-04 15:40 UTC, thibault-martinez approved these changes

2024-11-04 15:58 UTC, begonaalvarezd approved these changes

2024-11-04 15:58 UTC, merged