fix(devx): fix broken images
iotaledger/iota pull request #3840
Opened 2024-10-31 17:25 UTC by lucas-tortora

# Description of change

* Fixed broken favicon and wiki logo
 
## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-04 20:39 UTC, salaheldinsoliman requested changes
There seems to be a broken image under `Why IOTA`, is there an asset for it?
![image](https://github.com/user-attachments/assets/4049c636-dc59-4840-8c22-3905b3ba7ce6)

2024-11-05 06:13 UTC, vivekjain23 reviewed
IOTA Wiki logo at the Navbar is not rendered.
<img width="1470" alt="ss" src="https://github.com/user-attachments/assets/d75fae0a-7357-4625-b74f-7214a526db66">

2024-11-06 10:48 UTC, vivekjain23 approved these changes
LGTM :)

2024-11-06 12:19 UTC, salaheldinsoliman approved these changes

2024-11-06 12:20 UTC, merged