refactor(iota-core): Add more comments for `ReadApi::try_get_object_before_version`
iotaledger/iota pull request #3844
Opened 2024-11-01 08:52 UTC by bingyanglin

# Description of change

- Added more comments to explain why we still keep it.

## Links to any relevant issues

Part of https://github.com/iotaledger/iota/issues/2092

## Type of change

- Enhancement

## How the change has been tested

Ran the local network with `RUST_LOG=info cargo run --release --bin iota start --force-regenesis --with-faucet`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-01 09:15 UTC, kodemartin reviewed
Could you please elaborate on why this is deprecated?

2024-11-01 12:18 UTC, kodemartin approved these changes
lgtm :cherry_blossom:

2024-11-01 12:26 UTC, thibault-martinez approved these changes
It was introduced as already deprecated to avoid people calling it directly, if we think that's not an issue then LGTM!

2024-11-01 13:58 UTC, muXxer requested changes

2024-11-04 12:50 UTC, muXxer approved these changes

2024-11-04 12:50 UTC, merged