feat(docs): Added initial guide to the docs for educating EVM/Solidity devs about Move
iotaledger/iota pull request #390
Opened 2024-05-24 12:41 UTC by fijter

# Description of change

An initial effort has been made to compare EVM/Solidity to Move to decrease the learning curve of existing smart contract developers looking to move over the Move ecosystem. 

As a side-effect of this Solidity syntax highlighting in the docs has been enabled.

## Links to any relevant issues

fixes issue iotaledger/kinesis-devex#6

Fixes iotaledger/kinesis-devex#6

## Type of change

- Enhancement (a non-breaking change which adds functionality)
 
## How the change has been tested

Locally built the docs and tested it.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-05-27 17:02 UTC, lucas-tortora submitted a review, later dismissed
Loved the articles @fijter :) I'd make a couple of changes in style only, but I think it'd probably be better to wait until we have all the content in one place to [edit](https://github.com/iotaledger/devx/issues/419) it as a whole.

2024-06-04 22:21 UTC, Dr-Electron requested changes
Except some smaller changes looks really good ❤️ 
Frontmatter is still missing, but I can add that after we added the tag.yml file to tag everything properly

2024-06-05 07:40 UTC, Dr-Electron approved these changes

2024-06-05 14:42 UTC, lucas-tortora approved these changes

2024-06-05 14:43 UTC, merged