feat(docs): add ownership and references sections
iotaledger/iota pull request #3911
Opened 2024-11-05 15:21 UTC by salaheldinsoliman

# Description of change

Add docs about ownership and scope

## Links to any relevant issues

fixes #3755 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## How the change has been tested

Docs built locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-11-06 10:17 UTC, vivekjain23 requested changes

2024-11-07 20:02 UTC, lucas-tortora requested changes
Just a few comments. Please add a 1 sentence description in the frontmatter for the articles

2024-11-11 15:58 UTC, lucas-tortora approved these changes

2024-11-12 14:44 UTC, Ginowine approved these changes

2024-11-13 05:01 UTC, vivekjain23 approved these changes

2024-11-13 11:17 UTC, merged