feat(wallet-dashboard): show dapps list.
iotaledger/iota pull request #394
Opened 2024-05-24 18:04 UTC by panteleymonchuk

# Description of change

Closes #316

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Connect wallet and take a look list of dApps.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-05-27 11:14 UTC, marc2332 requested changes

2024-05-27 11:22 UTC, marc2332 reviewed
Would be great to allow all domains in CORS locally.  There seems to be a git conflict btw.

2024-05-27 13:19 UTC, marc2332 requested changes

2024-05-27 14:10 UTC, cpl121 requested changes

2024-05-28 08:31 UTC, cpl121 requested changes
LGTM!
Just resolve conflicts 🙏🏼

2024-05-28 11:12 UTC, cpl121 submitted a review, later dismissed
Perfect!

2024-05-29 10:34 UTC, evavirseda requested changes

2024-05-29 10:54 UTC, marc2332 submitted a review, later dismissed

2024-05-29 11:54 UTC, evavirseda approved these changes

2024-05-29 12:42 UTC, cpl121 approved these changes

2024-05-29 12:42 UTC, merged