refactor(tooling-general): Update docs links
iotaledger/iota pull request #3980
Opened 2024-11-11 08:56 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/1934

2024-11-11 13:04 UTC, lucas-tortora approved these changes

2024-11-11 13:44 UTC, brancoder requested changes
There is still some places where [wiki.iota.org](https://wiki.iota.org) is used
 ex. `https://wiki.iota.org/build/install`
 Should all of these links be updated in this PR?

2024-11-12 09:18 UTC, cpl121 requested changes
outdated `FAQ_LINK` in `apps/wallet/src/shared/constants.ts`

2024-11-12 11:16 UTC, thibault-martinez approved these changes

2024-11-12 12:14 UTC, brancoder approved these changes
LGTM :confetti_ball:

2024-11-12 12:15 UTC, cpl121 approved these changes

2024-11-12 14:29 UTC, begonaalvarezd approved these changes

2024-11-12 14:35 UTC, valeriyr approved these changes

2024-11-12 14:39 UTC, piotrm50 approved these changes

2024-11-12 14:40 UTC, merged