fix(devx): Unified all documentation links to docs.iota.org
iotaledger/iota pull request #4013
Opened 2024-11-11 22:58 UTC by lucas-tortora

# Description of change

Unifies URLs for docs to docs.iota.org and fixed URLs

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/3877

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-11-12 08:36 UTC, Thoralf-M approved these changes

2024-11-12 11:31 UTC, samuel-rufi approved these changes

2024-11-12 13:29 UTC, vivekjain23 approved these changes

2024-11-12 14:24 UTC, Ginowine approved these changes

2024-11-13 08:12 UTC, jkrvivian requested changes

2024-11-14 13:19 UTC, DaughterOfMars approved these changes

2024-11-15 07:28 UTC, jkrvivian approved these changes

2024-11-18 16:38 UTC, muXxer approved these changes

2024-12-04 13:28 UTC, lucas-tortora commented
@iotaledger/boxfish , @iotaledger/tooling, @iotaledger/consensus, @iotaledger/devops-admin could you please review this PR ?

2024-12-04 13:32 UTC, Dr-Electron approved these changes

2024-12-05 13:29 UTC, msarcev approved these changes

2024-12-05 14:05 UTC, merged