feat(docs): update fullnode deployment testnet & devnet configurations
iotaledger/iota pull request #4021
Opened 2024-11-12 10:28 UTC by FranCerdan

# Description of change

Update documentation for Full node deployment.

## Links to any relevant issues

https://github.com/iotaledger/iota/issues/2135

## Type of change

- Documentation Fix

## How the change has been tested

Deploying the fullnode on a VM.

2024-11-12 11:48 UTC, shufps approved these changes
lgtm :+1:

2024-11-12 16:53 UTC, lucas-tortora approved these changes

2024-11-13 07:45 UTC, junwei0117 requested changes

2024-11-13 08:48 UTC, FranCerdan reviewed
Updated PR, with latest peer ID's

2024-11-13 08:55 UTC, junwei0117 approved these changes

2024-11-13 11:30 UTC, bingyanglin approved these changes

2024-11-13 16:40 UTC, samuel-rufi approved these changes

2024-11-14 09:01 UTC, merged