feat(wallet-dashboard): style staking overview
iotaledger/iota pull request #4026
Opened 2024-11-12 14:00 UTC by brancoder

# Description of change

Styles staking overview

## Links to any relevant issues

resolves #3695

2024-11-20 10:06 UTC, brancoder commented
Paused and waiting on this one: https://github.com/iotaledger/iota/pull/3832

2024-11-22 12:00 UTC, msarcev commented on apps/wallet-dashboard/app/(protected)/staking/page.tsx
> +    // const [isDialogStakeOpen, setIsDialogStakeOpen] = useState(false);
Leftover commented code here

2024-11-22 14:42 UTC, evavirseda requested changes

2024-11-22 14:42 UTC, evavirseda commented on apps/wallet/src/ui/app/staking/validators/ValidatorsCard.tsx
> -import { StatsDetail } from '_app/staking/validators/StatsDetail';
`StatsDetail` isn't used anymore :broom:

2024-11-22 14:42 UTC, evavirseda commented on apps/core/src/components/staking/StakingStats.tsx
> +        <div className="flex h-[96px] flex-1 flex-col justify-between rounded-xl bg-neutral-96 p-md">
can you please add styles for darkmode too? :pray:

2024-11-22 14:42 UTC, evavirseda commented on apps/wallet-dashboard/app/(protected)/staking/page.tsx
> +        <StartStaking />
can you please add in `StartStaking` a gap between text and button :pray: 
`<div className="flex h-full w-full flex-col justify-between gap-y-md p-lg">` 
![image](https://github.com/user-attachments/assets/2fe11ff9-24f3-4eef-991f-46f2cd7d6f14)

2024-11-26 14:39 UTC, panteleymonchuk commented on apps/core/src/components/staking/StakingCard.tsx
> +    onClick?: () => void;
```suggestion
    onClick: () => void;
```
From what I see we always provide onClick to StakingCard

2024-11-26 14:39 UTC, panteleymonchuk commented on apps/core/src/hooks/stake/useValidatorInfo.tsx
> +    const totalValidatorStake = getTotalValidatorStake(validatorSummary);
These lines were removed in my PR, so you might need to remove them as well. They are not used.

2024-11-26 14:39 UTC, panteleymonchuk commented on apps/core/src/utils/stake/getTotalValidatorStake.ts
> +export function getTotalValidatorStake(validatorSummary: IotaValidatorSummary | null) {
Same for this file. It was removed in the PR #3832

2024-11-27 15:37 UTC, evavirseda requested changes

2024-11-27 15:37 UTC, evavirseda commented on apps/wallet-dashboard/app/(protected)/staking/page.tsx
>              {isDialogStakeOpen && stakeDialogView && (
it seems like something's going on here, as the dialog isn't opening, and instead, a 0 is showing up :see_no_evil: 
![image](https://github.com/user-attachments/assets/fe075a29-3735-4913-8c07-8aabbd751516)

2024-11-28 14:53 UTC, evavirseda approved these changes

2024-11-29 09:50 UTC, msarcev commented on apps/core/src/hooks/useNftDetails.ts
> +    const isTransferable = isAssetTransferable(objectData);
This needs to be fixed (conflict) since this is merged https://github.com/iotaledger/iota/pull/4159

2024-11-29 09:57 UTC, msarcev commented on apps/core/src/hooks/useNftDetails.ts
> +    const isTransferable = isAssetTransferable(objectData);
Weird that github doesn't say there are conflict. But `isAssetTransferable` doesn't exist anymore. Use the `useIsAssetTransferable` hook.

2024-11-29 10:16 UTC, VmMad requested changes
e2e staking tests are failing in the wallet

2024-11-29 18:49 UTC, brancoder commented
closed in favor of this one https://github.com/iotaledger/iota/pull/4315

2024-11-29 18:49 UTC, closed without merging