feat(wallet): improve displaying assets
iotaledger/iota pull request #4038
Opened 2024-11-13 15:41 UTC by brancoder

## Links to any relevant issues

resolves #3900 
resolves #3938

2024-11-18 11:12 UTC, cpl121 requested changes

2024-11-21 15:49 UTC, marc2332 requested changes

2024-11-21 15:49 UTC, marc2332 commented on apps/wallet-dashboard/app/(protected)/assets/page.tsx
> +    const [visual, nonVisual] = useMemo(() => {
Unnecessary useMemo

2024-11-22 12:41 UTC, cpl121 requested changes

2024-11-22 12:41 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/assets/page.tsx
> +        50,
we can add a constant for this hardcoded value

2024-11-22 12:41 UTC, cpl121 commented on apps/wallet-dashboard/components/AssetsList.tsx
> +            <div ref={observerElem}>
wouldnt you use scroll for both screens? imo, we can include the scroll in the other assets category

![image](https://github.com/user-attachments/assets/b8d72740-3199-4b14-9d4c-2ec0497caf74)
![image](https://github.com/user-attachments/assets/2bff1634-4073-4067-8450-5623eaa3d6a0)

2024-11-25 07:03 UTC, cpl121 approved these changes
NJ!

2024-11-25 08:17 UTC, marc2332 requested changes

2024-11-25 08:17 UTC, marc2332 commented on apps/wallet-dashboard/components/AssetsList.tsx
> +    fetchNextPage?: () => void;
These are never optional
```suggestion
    hasNextPage: boolean;
    isFetchingNextPage: boolean;
    fetchNextPage: () => void;
```

2024-11-25 08:17 UTC, marc2332 commented on apps/wallet-dashboard/app/(protected)/assets/page.tsx
You could also optimize the code a bit so only the selected assets of the category are mapped

(I also simplified the code)
```ts
	const { data, isFetching, fetchNextPage, hasNextPage } = useGetOwnedObjects(
        account?.address,
        undefined,
        OBJECTS_PER_REQ,
    );

    const assets: IotaObjectData[] = [];

    for(const page of data?.pages || []){
        for(const asset of page.data){
            if (asset.data && asset.data.objectId) {
                if (selectedCategory == AssetCategory.Visual) {
                    if(hasDisplayData(asset)) {
                        assets.push(asset.data);
                    }
                } else if(selectedCategory == AssetCategory.Other) {
                    assets.push(asset.data);
                }
            }
        }
    }

    return (
        <Panel>
            <Title title="Assets" size={TitleSize.Medium} />
            <div className="px-lg">
                <div className="flex flex-row items-center justify-start gap-xs py-xs">
                    {ASSET_CATEGORIES.map((tab) => (
                        <Chip
                            key={tab.label}
                            label={tab.label}
                            onClick={() => setSelectedCategory(tab.value)}
                            selected={selectedCategory === tab.value}
                        />
                    ))}
                </div>

                <AssetList
                    assets={assets}
                    selectedCategory={selectedCategory}
                    hasNextPage={hasNextPage}
                    isFetchingNextPage={isFetching}
                    fetchNextPage={fetchNextPage}
                />
            </div>
        </Panel>
    );
```

2024-11-25 08:17 UTC, marc2332 commented on apps/wallet-dashboard/components/AssetsList.tsx
> +    isFetchingNextPage = false,
```suggestion
    hasNextPage,
    isFetchingNextPage,
```

2024-11-26 14:49 UTC, panteleymonchuk approved these changes

2024-11-26 16:05 UTC, marc2332 approved these changes

2024-11-26 17:19 UTC, merged