feat(explorer): add theme switcher
iotaledger/iota pull request #4041
Opened 2024-11-13 16:36 UTC by VmMad

Fixes #3617 

Depends on #4079

2024-11-14 11:26 UTC, brancoder requested changes
Looks good we just need to fix lint issues. Im also getting prettier issues localy which dont seam to be an issue in the CI
![image](https://github.com/user-attachments/assets/28dac009-c871-41a4-b054-20b90e79bb41)
nit: The color scheme of the validator icons in the Top Validators table on the homepage could be improved:
![image](https://github.com/user-attachments/assets/3d2b9a4a-4613-466c-bace-77584fc96e60)

2024-11-14 15:10 UTC, evavirseda requested changes
the feature should be merged into a feature branch for all the dark mode-related changes not in develop, as mentioned in the parent issue https://github.com/iotaledger/iota/issues/3616 :pray:

2024-11-22 14:53 UTC, evavirseda approved these changes
<details>
    <summary>
        niceee 
    </summary>
    <img src="https://github.com/user-attachments/assets/2e5670e4-23c6-431a-9d7c-ba1399a69f32" />
</details>

2024-11-25 18:41 UTC, msarcev approved these changes

2024-11-25 18:41 UTC, merged