refactor(wallet): Remove Qredo
iotaledger/iota pull request #408
Opened 2024-05-27 14:12 UTC by brancoder

# Description of change

Remove Qredo from codebase

resolves #271 

## Type of change

- Refactor

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-05-28 06:42 UTC, marc2332 requested changes
![image](https://github.com/iotaledger/kinesis/assets/38158676/c2c62b4e-a26d-4e38-9117-80af9d88a907)

![image](https://github.com/iotaledger/kinesis/assets/38158676/6a092218-0aa1-4fd3-91fa-c3232c1f317c)


Maybe remove these as well?

2024-05-29 08:44 UTC, marc2332 submitted a review, later dismissed

2024-05-29 11:09 UTC, cpl121 approved these changes

2024-05-29 11:10 UTC, marc2332 approved these changes

2024-05-29 11:10 UTC, merged