Upgrade async-graphql deps
iotaledger/iota pull request #4128
Opened 2024-11-19 13:29 UTC by samuel-rufi

# Description of change

Upgrade async-graphql deps

## Links to any relevant issues

Aims to fix https://github.com/iotaledger/iota/issues/4121

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

```
cd crates/iota-graphql-e2e-tests
cargo nextest run --features pg_integration
```

```
cd crates/iota-graphql-rpc
cargo test
```

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-19 15:13 UTC, kodemartin requested changes
@samuel-rufi you can simplify the `impl Loader` blocks by simply removing the `#[async_trait::async_trait]`.

See [this suggestion](https://github.com/async-graphql/async-graphql/pull/1468#issuecomment-1981254678) in the respective discussion after the breaking change with the `Loader` trait refactoring.

`clippy` also raises the [manual async lint](https://rust-lang.github.io/rust-clippy/master/index.html#manual_async_fn), at least locally.

2025-01-29 09:49 UTC, kodemartin approved these changes
lgtm :balloon:

2025-01-29 10:05 UTC, miker83z approved these changes
Maybe there's `test_schema_sdl_export` to fix?

2025-01-29 10:48 UTC, samuel-rufi commented
Yes, https://github.com/iotaledger/iota/pull/4128/commits/52886fe42e4845302add43d9e6bcd420c39f66d2 should fix the `test_schema_sdl_export` test

2025-01-29 11:28 UTC, alexsporn approved these changes

2025-01-29 11:40 UTC, merged