feat(explorer): add missing darkmode colors to the homepage
iotaledger/iota pull request #4152
Opened 2024-11-20 09:53 UTC by VmMad

Fixes #4072

2024-11-20 12:24 UTC, evavirseda requested changes
nice job, just one thing :pray:

2024-11-20 12:24 UTC, evavirseda commented on apps/explorer/src/components/ui/ImageIcon.tsx
can you please revert these changes? 🙏 everything related to icons, avatars, etc., will be updated in this [issue](https://github.com/iotaledger/iota/issues/3939) so that we can avoid conflicts and bad merges

2024-11-21 11:21 UTC, evavirseda approved these changes

2024-11-25 08:45 UTC, cpl121 approved these changes

2024-11-26 09:25 UTC, merged