feat(explorer): improve darkmode colors for transaction page
iotaledger/iota pull request #4158
Opened 2024-11-20 11:42 UTC by VmMad

Fixes #4074

2024-11-21 09:17 UTC, evavirseda requested changes
could you also refine this arrow in the split panel for dark mode? :pray: 
![image](https://github.com/user-attachments/assets/a1990a4d-8232-40ad-816e-657c017b9ab7)

2024-11-21 09:17 UTC, evavirseda commented on apps/explorer/src/pages/transaction-result/TransactionView.tsx
> +                        <Panel bgColor="bg-neutral-100 dark:bg-neutral-6">
this change is unnecessary because the panel has the wrong dark mode color, in this [PR](https://github.com/iotaledger/iota/pull/4140/files#diff-3a0e8bb349141c54d5b753f5e25fff1d738114ad172e42d2822f2b57384ce64cR21), that issue will be resolved. :pray:

2024-11-21 11:19 UTC, evavirseda approved these changes

2024-11-25 12:54 UTC, msarcev approved these changes

2024-11-25 18:37 UTC, merged