feat(core): Add hook with logic to check if an asset is 'Transferabe'.
iotaledger/iota pull request #4159
Opened 2024-11-20 11:47 UTC by msarcev

# Description of change

- Add new hook way
- Remove old util function way

## Links to any relevant issues

Closes https://github.com/iotaledger/iota/issues/3962

2024-11-21 13:38 UTC, brancoder requested changes, later dismissed
conflicts :pray:

2024-11-25 14:50 UTC, begonaalvarezd approved these changes
nice

2024-11-26 14:57 UTC, panteleymonchuk approved these changes

2024-11-27 12:32 UTC, marc2332 submitted a review, later dismissed

2024-11-27 12:32 UTC, marc2332 commented on apps/wallet/src/ui/app/pages/home/nft-transfer/index.tsx
> +            <Loading loading={isPending || isCheckingAssetTransferability}>
```suggestion
            <Loading loading={isPending}>
```

2024-11-27 12:32 UTC, marc2332 commented on apps/wallet/src/ui/app/pages/home/nft-transfer/index.tsx
>      const isPending = isNftLoading || isGuardLoading;
```suggestion
    const isPending = isNftLoading || isGuardLoading || isCheckingAssetTransferability;
```

2024-11-27 12:32 UTC, marc2332 commented on apps/core/src/hooks/useIsAssetTransferable.ts
> +    });
Not that it makes a huge difference but I think it is a good practice.
```suggestion
		enabled: !!(packageId && moduleName && functionName),
    });
```

2024-11-28 16:58 UTC, msarcev commented on apps/wallet/src/ui/app/pages/home/nft-transfer/index.tsx
> +            <Loading loading={isPending || isCheckingAssetTransferability}>
Why ?

2024-11-28 16:59 UTC, msarcev commented on apps/wallet/src/ui/app/pages/home/nft-transfer/index.tsx
>      const isPending = isNftLoading || isGuardLoading;
Ah, i see why :)

2024-11-29 09:50 UTC, merged