feat(devx): Split and Edit full node guide
iotaledger/iota pull request #4182
Opened 2024-11-21 15:54 UTC by lucas-tortora

# Description of change

* Split the Full Node guide into an overview, docker, source, and monitoring and pruning.
* Updated the relevant links.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4109

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

## Release notes

Updated docs on running a full node.

2024-11-26 10:18 UTC, jkrvivian requested changes

2024-11-26 10:18 UTC, jkrvivian commented on docker/fullnode/README.md
> +    - address: /dns/access-1.r.testnet.iota.cafe/udp/8084
Testnet peers in Devnet section. :eyes:

2024-11-26 10:18 UTC, jkrvivian commented on docker/fullnode/README.md
> +        peer-id: 32875c547ea3b44fa08a711646cedb70fa0c97959d236578131505da09723add
Devnet peers in Testnet section.

2024-11-26 10:18 UTC, jkrvivian commented on docker/fullnode/README.md
> +#### Tesnet
```suggestion
#### Testnet
```

2024-11-26 10:18 UTC, jkrvivian commented on docker/fullnode/README.md
> +Full Node, open the URL: [hhttps://explorer.rebased.iota.org/](https://explorer.rebased.iota.org/), and select Custom
```suggestion
Full Node, open the URL: [https://explorer.rebased.iota.org/](https://explorer.rebased.iota.org/), and select Custom
```

2024-11-26 10:18 UTC, jkrvivian commented on docs/content/operator/iota-full-node/docker.mdx
> +description: Learn how to set up an IOTA Full node using docker.
```suggestion
description: Learn how to set up an IOTA Full Node using docker.
```

2024-11-26 10:18 UTC, jkrvivian commented on docs/content/operator/iota-full-node/overview.mdx
> +description: Operate an IOTA Full node to validate blockchain activities, like transactions, checkpoints, and epoch changes.
```suggestion
description: Operate an IOTA Full Node to validate blockchain activities, like transactions, checkpoints, and epoch changes.
```

2024-12-02 13:35 UTC, salaheldinsoliman approved these changes
looks good, just a few comments

2024-12-02 13:35 UTC, salaheldinsoliman commented on docker/fullnode/README.md
> +Use this guide to install and configure an IOTA Full Node locally using Docker for testing. These instructions are valid for the following operating system and processor combinations:
```suggestion
Use this guide to install and configure an IOTA Full Node locally using Docker for testing. The instructions apply to the following operating system and processor combinations:
```

2024-12-02 13:35 UTC, salaheldinsoliman commented on docker/fullnode/README.md
> +- [Mainnet genesis blob](https://github.com/iotaledger/iota/TODO):
Can we remove the Mainnet links and add a note that mainnet is not yet up, and a TODO as an invisible comment perhaps?

2024-12-02 13:35 UTC, salaheldinsoliman commented on docs/content/_snippets/warning-advanced-instructions-node-setup.mdx
> +These instructions are for advanced users. If you just need a local development environment,
```suggestion
These instructions are for setting up a Full node for network participation. If you just need a local development environment, 
```

2024-12-03 07:55 UTC, vivekjain23 approved these changes
LGTM :)

2024-12-03 09:31 UTC, jkrvivian approved these changes

2024-12-04 13:47 UTC, merged