Add Identity Wasm docs
iotaledger/iota pull request #4183
Opened 2024-11-21 16:33 UTC by eike-hass

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #(issue)`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-03-04 14:23 UTC, eike-hass commented
Still WIP, undrafting to run CI

2025-03-14 12:13 UTC, lucas-tortora requested changes

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +## Start the local chain
```suggestion
## Start the Local Chain
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +The examples in the repository and in this getting started section require a test network running locally, so if you do not already have, [install the IOTA CLI tool](https://docs.iota.org/developer/g
```suggestion
The examples in the repository and in this getting started section require a test network running locally, so if you do not already have one, [install the IOTA CLI tool](https://docs.iota.org/developer/getting-started/install-iota).
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +Now start the local network, e.g. with the following command (more details [here](https://docs.iota.org/developer/getting-started/local-network)).
```suggestion
Next, [start the local network](../../developer/getting-started/local-network.mdx) with the following command.
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +## Configure IOTA client for local chain
```suggestion
## Configure IOTA Client For the Local Chain
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +### Fresh IOTA client
```suggestion
### Fresh IOTA Client
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +If you haven't started the IOTA CLI client features tool yet, you have to generate a config file during first start, e.g. by calling
```suggestion
If you haven't started the IOTA CLI client features tool yet, you have to generate a config file during the first start by calling:
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +### New env
```suggestion
### New Env
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +Or if you don't already have an environment pointing to the local node, create a new env with for an IOTA Full node server with the same values as described above.
```suggestion
Alternatively, if you don't already have an environment pointing to the local node, create a new env for an IOTA Full node server with the same values as described above.
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +### Switch to local node env
```suggestion
### Switch to Local Node Env
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +If you did one of the steps above or if you already have an env as described above, make sure to switch to it.
```suggestion
If you did one of the steps above or already have an env as described above, make sure to switch to it.
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +### Request funds for active accounts
```suggestion
### Request Funds for Active Accounts
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +### Publish IOTA Identity Package
```suggestion
### Publish the IOTA Identity Package
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +If you haven't already, clone the IOTA identity [repository](https://github.com/iotaledger/identity.rs), and switch to the tag matching the version, you're working with.
```suggestion
Clone the IOTA identity [repository](https://github.com/iotaledger/identity.rs), and switch to the tag matching the version, you're working with.
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +Publish the identity package to your local test network:
```suggestion
Next, publish the identity package to your local test network:
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +The last line of the output will be the id of the package , that was just published. You'll need this id when creating an instance of `IdentityClient` and `IdentityClientReadOnly` for a custom networ
```suggestion
The last line of the output will be the id of the package that was just published. You'll need this ID when creating an instance of `IdentityClient` and `IdentityClientReadOnly` for a custom network, like the local network.
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/local-network-setup.mdx
> +The examples ([here](../how-tos/decentralized-identifiers/create.mdx) and following) fetch this value from the environment variable `IOTA_IDENTITY_PKG_ID`, so in order to run them, set this variable,
```suggestion
The  [create a decentralized identifier example](../how-tos/decentralized-identifiers/create.mdx), as well as the following examples, fetch this value from the environment variable `IOTA_IDENTITY_PKG_ID`, so in order to run them, set this variable, e.g. for package id `0x20f640b0dc01c50c04a84443d4320d7a77a15ed94f9bc19ebb6d0a5805045ddc` with:
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/wasm.mdx
> +Alternatively, you can build the bindings yourself, e.g. if you want to want to work currently unreleased features. You can find instructions for this in `identity.rs` repository [here](https://githu
```suggestion
Alternatively, you can build the bindings to work with currently unreleased features. You can find instructions for this in the [`identity.rs` repository](https://github.com/iotaledger/identity.rs/blob/v1.6.0-alpha/bindings/wasm/identity_wasm#build).
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/wasm.mdx
> +## NodeJS Usage
```suggestion
## Node.js Usage
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/wasm.mdx
> +The following code creates a new IOTA DID Document suitable for publishing to a locally running test network.  See the [instructions](./local-network-setup) on running your own test network.
```suggestion
The following code creates a new IOTA DID Document suitable for publishing to a [locally running test network](./local-network-setup).
```

2025-03-14 12:13 UTC, lucas-tortora commented on docs/content/iota-identity/getting-started/wasm.mdx
> +The following code creates a new IOTA DID Document suitable for publishing to a locally running test network.  See the [instructions](./local-network-setup) on running your own test network.
```suggestion
The following code creates a new IOTA DID Document suitable for publishing to a [locally running test network](./local-network-setup).
```

2025-03-14 16:41 UTC, wulfraem commented on docs/content/iota-identity/getting-started/wasm.mdx
> +The following code creates a new IOTA DID Document suitable for publishing to a locally running test network.  See the [instructions](./local-network-setup) on running your own test network.
Applied the other suggestion, with the same content. ^^

2025-03-17 15:01 UTC, lucas-tortora approved these changes

2025-03-17 15:27 UTC, wulfraem approved these changes

2025-03-17 15:39 UTC, merged