refactor(wallet): Remove kiosk
iotaledger/iota pull request #419
Opened 2024-05-28 09:00 UTC by marc2332

## Links to any relevant issues

Depends on https://github.com/iotaledger/kinesis/pull/418
Closes https://github.com/iotaledger/kinesis/issues/268

## Type of change

- Refactor

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2024-05-31 11:34 UTC, cpl121 submitted a review, later dismissed

2024-06-03 09:01 UTC, brancoder requested changes
Remove leftover unused vars and imports in couple of places

2024-06-03 13:32 UTC, brancoder approved these changes
LGTM

2024-06-04 07:42 UTC, cpl121 approved these changes

2024-06-04 07:45 UTC, merged