feat(explorer): reduce space of owned objects if there isn't many
iotaledger/iota pull request #4192
Opened 2024-11-22 10:18 UTC by VmMad

Fixes #4166

2024-11-22 11:02 UTC, evavirseda approved these changes
:star:

2024-11-22 12:06 UTC, cpl121 requested changes

2024-11-22 12:06 UTC, cpl121 commented on apps/explorer/src/lib/ui/enums/ownedObjects.enums.ts
> +    Md = 'h-[600px]',
I'm having some problems with some size

![image](https://github.com/user-attachments/assets/b1685783-724f-4079-86ed-239efb4769b5)
![image](https://github.com/user-attachments/assets/26a4b66a-0347-4079-80fb-c19c4bf8b52c)

2024-11-22 12:30 UTC, VmMad commented on apps/explorer/src/lib/ui/enums/ownedObjects.enums.ts
> +    Md = 'h-[600px]',
🤔

2024-11-22 14:58 UTC, marc2332 requested changes

2024-11-22 14:58 UTC, marc2332 commented on apps/explorer/src/components/owned-objects/OwnedObjects.tsx
Why do we need to set the height in the parent component, can't we do it in this one? I am referring about the `setContainerHeight` strategy

2024-11-25 13:16 UTC, cpl121 approved these changes

2024-11-25 15:28 UTC, evavirseda approved these changes

2024-11-25 15:43 UTC, panteleymonchuk approved these changes

2024-11-25 16:11 UTC, marc2332 approved these changes

2024-11-25 16:21 UTC, merged