feat(tooling): fix logo/avatar/icon image, move to core and cleanup debris
iotaledger/iota pull request #4249
Opened 2024-11-26 14:32 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/3939

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-27 08:18 UTC, VmMad commented on apps/core/src/hooks/stake/useValidatorInfo.tsx
> +        imageUrl: validatorSummary?.imageUrl || '',
This was supposed to be made in another issue

2024-11-27 08:18 UTC, VmMad commented on apps/wallet-dashboard/components/Dialogs/Staking/views/DetailsView.tsx
> +                                src={imageUrl}
Same here

2024-11-27 08:18 UTC, VmMad commented on apps/wallet-dashboard/components/Dialogs/Staking/views/Validator.tsx
> +                <ImageIcon src={imageUrl} label={name} fallback={name} size={ImageIconSize.Large} />
Same here

2024-11-27 14:34 UTC, brancoder requested changes
Looks good just lint issues 🙏

2024-11-27 16:21 UTC, VmMad approved these changes
LGTM

2024-12-03 12:56 UTC, panteleymonchuk approved these changes

2024-12-03 13:26 UTC, brancoder approved these changes
LGTM 🎊

2024-12-03 14:00 UTC, brancoder requested changes
nit: unused import

2024-12-03 14:00 UTC, brancoder commented on apps/core/src/components/icon/ImageIcon.tsx
This file has a leftover React import that is not added in this Pr but maybe we can remove it?

2024-12-03 14:42 UTC, brancoder approved these changes
LGTM 🎊

2024-12-03 14:42 UTC, merged