fix(wallet-dashboard): sending max amount does not send the correct a…
iotaledger/iota pull request #4252
Opened 2024-11-26 17:51 UTC by cpl121

…mount

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Closes #4229 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-11-27 11:36 UTC, brancoder approved these changes
This fixes the bug but the logic here seams a bit reversed to me. The `amount` holds the "formatted value" with decimal points and `formattedAmount` filed holds the full value without the decimal point. maybe this can be fixed in some other PR? wdyt?

2024-11-27 12:12 UTC, brancoder requested changes
Refactor the amount, formattedAmount and formatAmount:
https://github.com/iotaledger/iota/pull/4252#pullrequestreview-2464768916

2024-11-29 13:09 UTC, VmMad approved these changes

2024-12-02 17:56 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +    const [fullAmount] = useFormatCoin(formData.amount, selectedCoin.coinType, CoinFormat.FULL);
Is that ok that we don't show est gas fee in the new window?
![image](https://github.com/user-attachments/assets/93e92766-4fa1-4024-bc6e-7df7ed4be885)

For instance in the `develop` branch we show this value, but another point it's different from what we have in the dashboard
![image](https://github.com/user-attachments/assets/1d1a0eb1-535c-40de-b6af-fb41fc7558fc)

2024-12-02 17:56 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +    const [fullAmount] = useFormatCoin(formData.amount, selectedCoin.coinType, CoinFormat.FULL);
btw, we have the same issue about different gas fee numbers for staking flow.

Here is a created issue.
https://github.com/iotaledger/iota/issues/4081

2024-12-04 12:25 UTC, brancoder approved these changes
LGTM 👍 

we could do something similar to wallet send token flow in wallet where we still have this unused code that you removed here:
```
const coinsIDs = [...coins]
            .sort((a, b) => Number(b.balance) - Number(a.balance))
            .map(({ coinObjectId }) => coinObjectId);
```
Should we do it in this PR or open anew one?

2024-12-04 12:35 UTC, brancoder commented
> LGTM 👍
> 
> we could do something similar to wallet send token flow in wallet where we still have this unused code that you removed here:
> 
> ```
> const coinsIDs = [...coins]
>             .sort((a, b) => Number(b.balance) - Number(a.balance))
>             .map(({ coinObjectId }) => coinObjectId);
> ```
> 
> Should we do it in this PR or open anew one?

looks to me that coinIds is a leftover of old way of sending tx https://github.com/MystenLabs/sui/pull/8674/files

2024-12-04 13:18 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +    const [fullAmount] = useFormatCoin(formData.amount, selectedCoin.coinType, CoinFormat.FULL);
It works for me 🤔 Have you tried updating the wallet from this branch?

![image](https://github.com/user-attachments/assets/5f650854-2e84-4125-b4c4-e90cefe1d413)

2024-12-04 15:24 UTC, merged