fix(tooling-wallet): Fix staking with ledger
iotaledger/iota pull request #4296
Opened 2024-11-28 13:34 UTC by msarcev

# Description of change

Closes https://github.com/iotaledger/iota/issues/4222

2024-11-28 14:59 UTC, begonaalvarezd requested changes

2024-11-28 14:59 UTC, begonaalvarezd commented on apps/wallet/src/ui/app/SpeculosHttpTransport.tsx
> +const SPECULOS_API_DEFAULT_PORT = '5001';
the default port in speculos is 5000 i wouldnt change this

2024-11-28 15:10 UTC, begonaalvarezd commented on apps/wallet/src/ui/app/SpeculosHttpTransport.tsx
> +const SPECULOS_API_DEFAULT_PORT = '5001';
actually...let me think about this because if 5000 is always occupied by the network we should probably change to 5001

2024-12-03 16:18 UTC, begonaalvarezd approved these changes

2024-12-04 08:03 UTC, evavirseda approved these changes

2024-12-04 09:54 UTC, merged