fix(wallet): Proper check of tx result after signing
iotaledger/iota pull request #4328
Opened 2024-12-02 15:43 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/4327

2024-12-03 11:55 UTC, brancoder approved these changes
LGTM 👍

2024-12-03 12:04 UTC, begonaalvarezd requested changes
very nice, I suggest we improve the e2e test coverage so we fetch this issue in the future if we break the funcionality

2024-12-03 14:41 UTC, begonaalvarezd requested changes

2024-12-03 14:41 UTC, begonaalvarezd commented on apps/wallet/tests/sites-to-cs-messaging.spec.ts
> +        test('signing a message fails', async () => {
https://github.com/iotaledger/iota/pull/4337 the tests passed in a temp PR that does not include your FIX, that means the tests do not really work for a broken implementation 🙏🏼

2024-12-04 13:19 UTC, cpl121 approved these changes

2024-12-04 15:05 UTC, begonaalvarezd approved these changes

2024-12-04 15:05 UTC, merged