feat(wallet-dasboard): style vesting schedule
iotaledger/iota pull request #4340
Opened 2024-12-03 15:38 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

:warning: nested PR, first merge https://github.com/iotaledger/iota/pull/4278

fixes https://github.com/iotaledger/iota/issues/4264

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-04 13:42 UTC, cpl121 requested changes

2024-12-04 13:42 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/vesting/page.tsx
> +        nextPayout && buildSupplyIncreaseVestingSchedule(nextPayout, Number(currentEpochMs));
We need the lastPayout to build the schedule

2024-12-04 13:42 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/vesting/page.tsx
> +                            buttonDisabled={!vestingSchedule}
```suggestion
                            buttonDisabled={!vestingPortfolio}
```

2024-12-04 13:42 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/vesting/VestingScheduleBox.tsx
> +    const isLocked = expirationTimestampMs > Date.now();
```suggestion
    const isLocked = expirationTimestampMs > currentEpochTimestamp;
```

2024-12-04 13:42 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/vesting/VestingScheduleBox.tsx
> +    const isLocked = expirationTimestampMs > Date.now();
Im not sure about this, let me ask

2024-12-04 16:02 UTC, brancoder approved these changes
LGTM 👍

2024-12-04 16:54 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/vesting/VestingScheduleBox.tsx
> +    const isLocked = expirationTimestampMs > Date.now();
okay, all clear now
I will create new comments with the changes 🙏🏼

2024-12-04 16:57 UTC, cpl121 requested changes

2024-12-04 16:57 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/vesting/VestingScheduleBox.tsx
> +            label={new Date(expirationTimestampMs).toLocaleString()}
we will only show the date until we know what time to show
```suggestion
            label={new Date(expirationTimestampMs).toLocaleDateString()}
```
https://github.com/iotaledger/iota/issues/4369

2024-12-04 17:10 UTC, cpl121 requested changes
build error 🙏🏼

2024-12-05 09:52 UTC, brancoder requested changes
Lint 🙏

2024-12-05 12:09 UTC, cpl121 requested changes

2024-12-05 12:09 UTC, cpl121 commented on apps/wallet-dashboard/lib/utils/vesting/vesting.spec.ts
> +const MOCKED_CURRENT_EPOCH_TIMESTAMP = 1733340503570; // Wednesday, 04 December 2024 19:28:23
It is better that this mocked constant is dynamic
```suggestion
const MOCKED_CURRENT_EPOCH_TIMESTAMP = Date.now() + (MILLISECONDS_PER_HOUR * 6); // 6 hours later
```

2024-12-05 12:21 UTC, cpl121 approved these changes
NJ Eva 👏🏼

2024-12-05 13:16 UTC, brancoder approved these changes
LGTM 🎊

2024-12-05 13:27 UTC, merged