feat(scripts): Add script to track upstream commits
iotaledger/iota pull request #4370
Opened 2024-12-05 08:14 UTC by jkrvivian

# Description of change

This script identifies all commits for the crates managed by the specified code owner within the provided time range.

## Type of change

- Enhancement 

## How the change has been tested

change directory to `scripts/track_upstream_commits`, then 
`./run.sh --since "2024-09-05" --until "2024-10-26" --codeowner "node"`

output:
```
Parsing the CODEOWNERS file...
First commit: bb778828e36d53a7d91a27e55109f2f45621badc
Last commit: 29ff3e3f53fc7aa590da97d1033265645be1ea1a
SINCE: 2024-09-05
UNTIL: 2024-10-25
CRATES: docker, crates/sui-archival, crates/sui-authority-aggregation, crates/sui-config, crates/sui-core, crates/sui-network, crates/sui-network-stack, crates/sui-node, crates/sui-types, crates/sui-protocol-config, crates/sui-protocol-config-macros, crates/sui-rest-api, crates/sui-snapshot, crates/sui-storage

## docker (4)
- https://github.com/MystenLabs/sui/commit/6b231597e707bae887ca038d670ba3aa02775d37
- https://github.com/MystenLabs/sui/commit/037f13e3e413dced1ea6d6ac6b52d7ac27642ba8
- https://github.com/MystenLabs/sui/commit/e67a2f40db3c68d879ec723c7a73d3ba27f4099b
- https://github.com/MystenLabs/sui/commit/88c7c85453bff0f41492cf591a52c2781d681b68

## crates/sui-archival (1)
- https://github.com/MystenLabs/sui/commit/72603de6260795d5c9ed60f885a4ebe717a9430e
```

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2024-12-05 08:34 UTC, bingyanglin approved these changes
Looks pretty good to me!

2024-12-11 17:00 UTC, miker83z reviewed
Looks very good! I tested it and used in the vm-language report. I think these two changes can make it even better:
- Provide the commits in temporal order, from the oldest to the newest (either forced or providing a flag to enable it)
- Add a flag that can be used instead of "codeowner" to specify a list of crates (right now it seems the only way I have to specify custom crates is to modify my CODEOWNER local file).

Great job!

2024-12-17 12:33 UTC, muXxer commented on scripts/track_upstream_commits/run.sh
> +if command -v python3 &>/dev/null; then
why don't you use the `python_venv_wrapper.sh` like in the other scripts?

2024-12-17 12:33 UTC, muXxer commented on scripts/track_upstream_commits/README.md
> +  --since SINCE         Start date for git log (e.g., "2024-09-05").
I wonder if we shouldn't rather use commit hashes instead of dates. That would be more explicit IMO.

2024-12-17 12:33 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +def clone_repo(repo_url, repo_tag, target_folder):
I think we should rather extract those functions into a "util.py" instead of copy pasting and modifying the code.
But we can also do that in another cleanup PR.

2025-01-07 08:39 UTC, jkrvivian commented on scripts/track_upstream_commits/track_upstream_commits.py
> +def clone_repo(repo_url, repo_tag, target_folder):
Issue created: https://github.com/iotaledger/iota/issues/4697

2025-01-07 08:40 UTC, jkrvivian commented on scripts/track_upstream_commits/README.md
> +  --since SINCE         Start date for git log (e.g., "2024-09-05").
That makes a lot more sense!

2025-01-08 13:51 UTC, muXxer requested changes

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/run.sh
> +#                         code owner of the crates (e.g., "node)
```suggestion
#                         code owner of the crates (e.g., "node")
```

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/run.sh
> +#   --version VERSION     The semantic version to filter overwrites/patches if not found in the repo-tag.
Is this a copy paste leftover? If not, at least the comment is wrong.

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +    parser.add_argument('--version', default=None, help="The semantic version to filter overwrites/patches if not found in the repo-tag.")
you never use that, remove it.

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +    parser.add_argument('--compare-source-folder', help="The path to the source folder for comparison.")
you never use that, remove it.

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +    source_folder = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))
not used anywere as far as I see. Remove it and the parameter.

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +        crates = [f"crates/{crate.replace('iota', 'sui')}" for crate in args.crates]
I think we also renamed some crates, so that won't work 100%. Maybe you need some mapping table?

2025-01-08 13:51 UTC, muXxer commented on scripts/track_upstream_commits/run.sh
> +#   --since SINCE         Start commit hash for git log (e.g., "bb778828e36d53a7d91a27e55109f2f45621badc").
is it included?

2025-01-09 07:43 UTC, jkrvivian commented on scripts/track_upstream_commits/run.sh
> +#   --since SINCE         Start commit hash for git log (e.g., "bb778828e36d53a7d91a27e55109f2f45621badc").
Nope, the comment is updated.

2025-01-09 08:00 UTC, jkrvivian commented on scripts/track_upstream_commits/run.sh
> +#   --version VERSION     The semantic version to filter overwrites/patches if not found in the repo-tag.
version is not used, it's removed now.

2025-01-09 16:05 UTC, muXxer requested changes

2025-01-09 16:05 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +def convert_iota_to_sui_crates(crates):
I know this is a bit of nitpicking, and sorry for that... but why do we even talk about crates in the code at all?
Shouldn't the script be valid for all folders in the repository that belong to different codeowners?

I realized that in this function, where we append the `crates/`.

Maybe instead of passing owned crates via parameter, we should pass owned folders with relative paths to the root. And rename all occurenced of crates in the code 😅

2025-01-09 16:06 UTC, muXxer commented on scripts/track_upstream_commits/track_upstream_commits.py
> +def convert_iota_to_sui_crates(crates):
Or even pass valid regexes like in the codeowners file 🏃

2025-01-10 10:48 UTC, miker83z approved these changes

2025-01-13 12:53 UTC, jkrvivian commented on scripts/track_upstream_commits/track_upstream_commits.py
> +def convert_iota_to_sui_crates(crates):
You're right, we should track all folders of the codeowner, not just `/crates`.

2025-01-16 13:20 UTC, muXxer approved these changes

2025-01-16 13:20 UTC, merged