feat(sdk/dappkit): fix styles in the dropdown
iotaledger/iota pull request #4374
Opened 2024-12-05 09:54 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4359

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-05 12:31 UTC, cpl121 submitted a review, later dismissed

2024-12-06 13:11 UTC, panteleymonchuk commented on sdk/dapp-kit/src/components/AccountDropdownMenu.css.ts
> +    height: 'auto',
Probably better to use `overflow-y: scroll` instead of height: auto?
Then we'll have a scroll instead of infinite height div.

It's for case if someone has a lot of accounts & height more than screen's height. Not how real this case, but anyway have to mention about that.

wdyt?

![image](https://github.com/user-attachments/assets/f60c7c81-cf1f-4746-b280-cec2e35748eb)

2024-12-12 10:19 UTC, cpl121 requested changes
It seems weird to me that with 6 accounts, in dark mode I have scroll and in light mode I don't
![Captura desde 2024-12-12 11-10-17](https://github.com/user-attachments/assets/00d5f5b9-8eea-41eb-8ca0-72c48c401b59)
![Captura desde 2024-12-12 11-10-35](https://github.com/user-attachments/assets/a0da765c-8d3c-44f1-933d-468f8af16d4e)

2024-12-12 13:36 UTC, cpl121 approved these changes

2024-12-12 16:16 UTC, panteleymonchuk approved these changes
LGTM🚀

2024-12-12 16:20 UTC, merged