feat(wallet-dashboard): show tx details in unstaking flow
iotaledger/iota pull request #4433
Opened 2024-12-11 08:15 UTC by cpl121

# Description of change

Add tx details to unstaking flow
Depends on #4422 

## Links to any relevant issues

Closes #4258 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2024-12-11 08:33 UTC, cpl121 commented
I have doubts about [this](https://github.com/iotaledger/iota/pull/4433/files#diff-b1e79598d83c78204112721bdac70b93cc98a7456d2e6eeeffcee07bf76e9333R73)
Were we blocking the unstake button while it was pending for some reason?
If the user unstakes before staking starts, he will not earn rewards, but I think it is a bad idea to leave the user with the funds blocked until staking starts

2024-12-11 15:16 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx
> +                    onSuccess?.(tx.digest);
I see some of onSuccess callbacks uses `iotaClient.waitForTransaction` which is async.

Should we await it before move to the next TransactionDetails screen?

2024-12-11 17:11 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx
> +                    onSuccess?.(tx.digest);
As I see, this component is called in `apps/wallet-dashboard/app/(protected)/staking/page.tsx` and `apps/wallet-dashboard/app/(protected)/vesting/page.tsx,` and in both places the `onSuccess` is not async
Where do you say it is async?

2024-12-11 18:00 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx
> +                    onSuccess?.(tx.digest);
up to my understanding waitfortransaction async

![image](https://github.com/user-attachments/assets/0b4d1869-ef86-4c20-8d51-b49979813669)

2024-12-12 16:10 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx
> +                    onSuccess?.(tx.digest);
nft output claim is not related with unstaking flow

2024-12-12 16:12 UTC, panteleymonchuk approved these changes
LGTM 🚀

2024-12-12 16:15 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/Staking/StakeDialog.tsx
> +                    onSuccess?.(tx.digest);
It's just an example that waitForTransaction is async function.
It's using in the onSuccess callbacks. My concern here was if we need to await it before move to the next screen.
But we discussed that we don't 🫡

2024-12-12 18:20 UTC, begonaalvarezd approved these changes

2024-12-12 18:21 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/Dialogs/Staking/views/UnstakeView.tsx
> +    const delegationId = extendedStake?.stakedIotaId;
nice catch 🚀

2024-12-13 09:04 UTC, marc2332 commented on apps/wallet-dashboard/components/Dialogs/Staking/views/UnstakeView.tsx
> +    const delegationId = extendedStake?.stakedIotaId;
🚀

2024-12-13 09:10 UTC, marc2332 requested changes

2024-12-13 09:10 UTC, marc2332 commented on apps/wallet-dashboard/components/Dialogs/Staking/views/UnstakeView.tsx
>  interface UnstakeDialogProps {
Mind renaming this while you are it?
```suggestion
interface UnstakeViewProps {
```

2024-12-16 15:22 UTC, marc2332 approved these changes

2024-12-17 10:52 UTC, merged

2024-12-17 10:53 UTC, marc2332 approved these changes