feat(wallet-dashboard): add tx details state to the end of send visual asset flow
iotaledger/iota pull request #4449
Opened 2024-12-11 14:15 UTC by panteleymonchuk

## Links to any relevant issues

Closes #4256
Depends on: https://github.com/iotaledger/iota/pull/4422

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Send a visual asset to some address.

Expected behaviour: user is able to see recipt.
<img width="392" alt="image" src="https://github.com/user-attachments/assets/eac71242-242c-4dac-8aa6-e940fcc8ba94" />

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-11 15:20 UTC, begonaalvarezd requested changes

2024-12-11 15:20 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/Dialogs/Assets/AssetDialog.tsx
> +            setView(AssetsDialogView.Recipt);
Spellcheck is failing, it should be `Receipt`

2024-12-12 18:16 UTC, begonaalvarezd requested changes

2024-12-12 18:16 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/Dialogs/Assets/AssetDialog.tsx
> +            setView(AssetsDialogView.Recipt);
In order PRs I see we are calling this `TransactionDetails` though, we should unify it

2024-12-13 13:15 UTC, evavirseda approved these changes

2024-12-16 12:49 UTC, cpl121 requested changes
build error 🙏🏼

2024-12-17 13:52 UTC, begonaalvarezd requested changes

2024-12-17 13:52 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/Dialogs/Assets/AssetDialog.tsx
> +            setDigest(tx.digest);
I think we should refetch at this point

2024-12-18 09:57 UTC, cpl121 requested changes

2024-12-18 09:57 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/Assets/AssetDialog.tsx
> +            </DialogLayout>
we don't need views `DetailsView` and `TransactionDetailsView` inside the Formik Provider
```suggestion
           <DialogLayout>
                {view === AssetsDialogView.Details && (
                    <DetailsView asset={asset} onClose={onOpenChange} onSend={onDetailsSend} />
                )}
                {view === AssetsDialogView.Send && (
                    <FormikProvider value={formik}>
                        <SendView asset={asset} onClose={onOpenChange} onBack={onSendViewBack} />
                    </FormikProvider>
                )}
                {view === AssetsDialogView.TransactionDetails && !!digest ? (
                    <TransactionDetailsView digest={digest} onClose={onOpenChange} />
                ) : null}
            </DialogLayout>
```

2024-12-18 12:01 UTC, begonaalvarezd approved these changes

2024-12-18 12:17 UTC, cpl121 approved these changes

2024-12-18 12:17 UTC, merged