refactor(apps-core, wallet-dashboard, wallet): move ValidatorLogo to apps/core and use it in Unstake Details
iotaledger/iota pull request #4475
Opened 2024-12-12 14:28 UTC by panteleymonchuk

## Links to any relevant issues

fixes #3916

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-13 10:57 UTC, marc2332 requested changes, later dismissed
Also remove `validatorLogo.interfaces.ts`

2024-12-13 10:57 UTC, marc2332 commented on apps/core/src/components/Validator.tsx
> +    onClick?(): void;
I wonder how did this even compile
```suggestion
    onClick?: () => void;
```

2024-12-18 13:07 UTC, cpl121 requested changes

2024-12-18 13:07 UTC, cpl121 commented on apps/core/src/components/Validator.tsx
> +        return <div className="flex items-center justify-center">...</div>;
We can use Skeleton here, wdyt?
```suggestion
        return <Card>
                <CardImage shape={ImageShape.SquareRounded}>
                    <div className="h-10 w-10 animate-pulse bg-neutral-90 dark:bg-neutral-12" />
                    <Skeleton widthClass="w-10" heightClass="h-10" isRounded={false} />
                </CardImage>
                <div className="flex flex-col gap-y-xs">
                    <Skeleton widthClass="w-40" heightClass="h-3.5" />
                    <Skeleton widthClass="w-32" heightClass="h-3" hasSecondaryColors />
                </div>
                <div className="ml-auto flex flex-col gap-y-xs">
                    <Skeleton widthClass="w-20" heightClass="h-3.5" />
                </div>
            </Card>;
```

2024-12-18 13:47 UTC, panteleymonchuk commented on apps/core/src/components/Validator.tsx
> +        return <div className="flex items-center justify-center">...</div>;
sounds good

2024-12-20 08:08 UTC, cpl121 approved these changes

2024-12-23 08:29 UTC, evavirseda requested changes

2024-12-23 08:29 UTC, evavirseda commented on apps/core/src/components/transaction/info/UnstakeTransactionInfo.tsx
>  import { Divider, KeyValueInfo, Panel } from '@iota/apps-ui-kit';
```suggestion
import { Divider, KeyValueInfo, Panel, CardType } from '@iota/apps-ui-kit';
```

2024-12-23 10:20 UTC, evavirseda approved these changes

2025-01-07 14:25 UTC, begonaalvarezd requested changes
The APY is duplicated now when I start a stake
![image](https://github.com/user-attachments/assets/61b68df6-b94c-4934-958f-1b328421f2ed)

2025-01-13 11:03 UTC, evavirseda reviewed
:pray:

2025-01-13 11:03 UTC, evavirseda commented on apps/core/src/components/Validator.tsx
> +import React from 'react';
unnecessary import :broom:

2025-01-16 15:23 UTC, marc2332 approved these changes

2025-01-16 15:23 UTC, marc2332 commented on apps/core/src/components/Validator.tsx
While you are at it you could change `activeEpoch` type from `string` to `number`, rest lgtm

2025-01-17 10:06 UTC, panteleymonchuk commented on apps/core/src/components/Validator.tsx
done

2025-01-20 15:10 UTC, begonaalvarezd approved these changes

2025-01-20 15:24 UTC, merged