feat(tooling-dashboard): improve staking dialog
iotaledger/iota pull request #4476
Opened 2024-12-12 14:54 UTC by brancoder

# Description of change

resolves #4367

2024-12-16 11:56 UTC, evavirseda approved these changes

2024-12-17 16:10 UTC, evavirseda requested changes
conflicts :ok_woman:

2024-12-18 10:48 UTC, evavirseda approved these changes

2024-12-18 11:45 UTC, panteleymonchuk approved these changes

2024-12-18 12:35 UTC, begonaalvarezd approved these changes

2024-12-18 12:35 UTC, merged