feat(wallet-dashboard): polish homepage scroll
iotaledger/iota pull request #4502
Opened 2024-12-16 09:21 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4492

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-16 13:14 UTC, cpl121 requested changes

2024-12-16 13:14 UTC, cpl121 commented on apps/wallet-dashboard/components/VirtualList.tsx
> -        virtualizer.getVirtualItems(),
why has this been removed from the useEffect?
Its still needed to get the last item

2024-12-16 13:14 UTC, cpl121 commented on apps/wallet-dashboard/app/globals.css
> +        height: calc(100vh - 130px);
why 130px? Shouldn't it be 72px?
![image](https://github.com/user-attachments/assets/62057b14-1b35-43db-97e2-a01243d444d6)

2024-12-16 13:14 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/home/page.tsx
> +                    <div className="home-page-grid-container w-full">
Its weird for an account without tokens. All the sections should be together, right?
![image](https://github.com/user-attachments/assets/132acf59-434b-48b3-b51a-ea2d8e499f8b)

2024-12-16 14:18 UTC, evavirseda commented on apps/wallet-dashboard/components/VirtualList.tsx
> -        virtualizer.getVirtualItems(),
I forgot to add the new one, sorry :sweat_smile:  :pray:

2024-12-16 17:58 UTC, cpl121 requested changes
NJ!
Only conflicts 🙏🏼

2024-12-17 09:44 UTC, begonaalvarezd requested changes
looks great, just a nit

2024-12-17 09:44 UTC, begonaalvarezd commented on apps/wallet-dashboard/app/globals.css
> +            height: calc(100vh - 140px);
i would still make a min height so this doesnt happen 
![image](https://github.com/user-attachments/assets/77d8f2fd-1a49-4a39-8ad8-e0bbe077f1f0)

2024-12-17 09:59 UTC, begonaalvarezd approved these changes

2024-12-17 10:04 UTC, brancoder requested changes
we could add some padding under button segments so the scrolled coins dont disappear right under the segment
![image](https://github.com/user-attachments/assets/d5eeb614-3df9-46f1-9e9f-2dc4edd1fb86)

this is a nit about the segmented buttons and is probably not related to this PR but on smaller viewports the segmented button looks too rounded when it spans in to the second row 
![image](https://github.com/user-attachments/assets/6c420a66-cc27-4e7d-a6fb-57ddaa60157b)

2024-12-17 10:59 UTC, cpl121 approved these changes

2024-12-17 12:34 UTC, brancoder approved these changes
LGTM

2024-12-18 09:53 UTC, merged