feat(wallet-dashboard): improve dark/light mode
iotaledger/iota pull request #4503
Opened 2024-12-16 09:57 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4494

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-16 12:58 UTC, cpl121 requested changes
just minimal comment

2024-12-16 12:58 UTC, cpl121 commented on apps/core/src/components/buttons/ThemeSwitcher.tsx
> +export * from './ThemeSwitcher';
Is this export necessary?

2024-12-16 13:21 UTC, cpl121 approved these changes

2024-12-17 10:19 UTC, begonaalvarezd approved these changes

2024-12-17 10:36 UTC, merged