feat(docs): mint ctf completion nft
iotaledger/iota pull request #4521
Opened 2024-12-17 14:30 UTC by vivekjain23

# Description of change

This PR brings up the enhancement of NFT minting on completion of the CTF challenge.

## Links to any relevant issues

Fixes #4133 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Changes were built locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-12-19 12:52 UTC, lucas-tortora commented
@vivekjain23 , I'm getting these errors when attempting to get the first NFT. My account has 10 IOTAs, so in theory, we should have enough for gas. If it helps I can record a short video 

![Screenshot from 2024-12-19 09-50-21](https://github.com/user-attachments/assets/d20ef3ff-3ca6-4fde-8191-e87cc82a75fc)
![Screenshot from 2024-12-19 09-50-03](https://github.com/user-attachments/assets/a4f960b3-1bab-48ed-a435-f8df56cfba6a)

2025-01-08 13:29 UTC, lucas-tortora requested changes
One small comment about casing in the nftName Param

2025-01-09 10:23 UTC, begonaalvarezd requested changes

2025-01-09 10:23 UTC, begonaalvarezd commented on apps/core/src/hooks/useNftDetails.ts
> -    const nftName = nftDisplayData?.name || formatAddress(nftId);
lets please not rename anything in the apps folder 🙏🏼

2025-01-10 11:42 UTC, vivekjain23 commented on apps/core/src/hooks/useNftDetails.ts
> -    const nftName = nftDisplayData?.name || formatAddress(nftId);
my bad, noted!

2025-01-10 11:49 UTC, begonaalvarezd commented on apps/core/src/hooks/useNftDetails.ts
> -    const nftName = nftDisplayData?.name || formatAddress(nftId);
there are still 2 files that need to be reverted

2025-01-10 13:47 UTC, begonaalvarezd requested changes

2025-01-10 13:47 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/dialogs/assets/views/DetailsView.tsx
please revert this file, the code wont compile otherwise

2025-01-10 13:47 UTC, begonaalvarezd commented on apps/wallet-dashboard/components/dialogs/assets/views/SendView.tsx
please revert this file, the code wont compile otherwise

2025-01-13 07:35 UTC, vivekjain23 commented on apps/core/src/hooks/useNftDetails.ts
> -    const nftName = nftDisplayData?.name || formatAddress(nftId);
done.

2025-01-13 07:36 UTC, vivekjain23 commented on apps/wallet-dashboard/components/dialogs/assets/views/DetailsView.tsx
done

2025-01-13 07:36 UTC, vivekjain23 commented on apps/wallet-dashboard/components/dialogs/assets/views/SendView.tsx
done.

2025-01-13 18:36 UTC, begonaalvarezd approved these changes

2025-01-15 13:37 UTC, lucas-tortora approved these changes

2025-01-16 05:49 UTC, merged