feat(wallet-dashboard): add send coin popup
iotaledger/iota pull request #453
Opened 2024-05-29 18:41 UTC by cpl121

# Description of change

Create send coin popup

## Links to any relevant issues

fixes issue #283 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Click on the send button in the coin list

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-05-30 09:33 UTC, marc2332 requested changes

2024-05-31 08:25 UTC, VmMad requested changes
This is missing the generic `send` button in home, right?

2024-05-31 09:50 UTC, evavirseda submitted a review, later dismissed

2024-06-04 08:58 UTC, marc2332 requested changes

2024-06-07 11:41 UTC, marc2332 submitted a review, later dismissed

2024-06-10 08:47 UTC, brancoder requested changes
update @mysten/sui.js to iota.js

2024-06-10 10:43 UTC, brancoder submitted a review, later dismissed
LGTM

2024-06-10 11:38 UTC, begonaalvarezd requested changes

2024-06-11 07:57 UTC, begonaalvarezd approved these changes

2024-06-11 08:01 UTC, VmMad approved these changes

2024-06-11 11:23 UTC, merged