feat(wallet-dashboard): cleanup usage of `addNotification` and debris
iotaledger/iota pull request #4553
Opened 2024-12-18 16:27 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4520

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-19 15:34 UTC, cpl121 requested changes

2024-12-19 15:34 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +                toast.success('Transfer transaction successful');
I would leave the text that was before
`'Transfer transaction has been sent'`

2024-12-20 07:43 UTC, cpl121 approved these changes

2024-12-20 13:10 UTC, panteleymonchuk approved these changes

2024-12-20 13:10 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/Dialogs/SendToken/SendTokenDialog.tsx
> +            toast.error('There was an error with the transaction');
![image](https://github.com/user-attachments/assets/f860cb35-9fce-41c0-b3b9-604d8762557f)


All looks good.
nit: just from the UI perspective it might be better to show toast in the left corner. So it won't overlap dialog.

2024-12-26 16:24 UTC, merged