fix(docs): add notes about indexer in rpc specs
iotaledger/iota pull request #4584
Opened 2024-12-20 12:22 UTC by Dr-Electron

# Description of change

Some RPC endpoints are only available on indexer. So I added a note and changed the text where needed.

## Links to any relevant issues

Fixes #4565.

## Type of change

- Documentation Fix

## How the change has been tested

Run locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-20 12:59 UTC, kodemartin approved these changes

2024-12-20 13:32 UTC, DaughterOfMars commented on crates/iota-json-rpc-api/src/extended.rs
> +    /// Return a list of epoch info. Exclusively served by the indexer
```suggestion
    /// Return a list of epoch info. Exclusively served by the indexer.
```

2024-12-20 13:32 UTC, DaughterOfMars commented on crates/iota-json-rpc-api/src/extended.rs
> +    /// Return a list of epoch info. Exclusively served by the indexer
And below as well please 🙏

2024-12-20 13:47 UTC, lucas-tortora approved these changes
Besides @DaughterOfMars 's comments, LGTM :)

2024-12-23 07:14 UTC, vivekjain23 approved these changes

2025-01-07 10:12 UTC, Dr-Electron commented on crates/iota-json-rpc-api/src/extended.rs
> +    /// Return a list of epoch info. Exclusively served by the indexer
Done in 5671e46

2025-01-07 10:52 UTC, Thoralf-M approved these changes

2025-01-07 10:54 UTC, Thoralf-M requested changes
fmt failing, did you run `cargo +nightly fmt`?

2025-01-09 13:31 UTC, Thoralf-M approved these changes

2025-01-16 08:46 UTC, thibault-martinez commented
Let's fix the conflicts and merge this

2025-01-17 12:14 UTC, merged