fix(sdk): Update typography light theme line height
iotaledger/iota pull request #4589
Opened 2024-12-20 14:22 UTC by marc2332

.

2024-12-20 14:25 UTC, Dr-Electron approved these changes
Looks good to me. when fix the real thing tho? :trollface:

2024-12-23 07:33 UTC, evavirseda approved these changes

2024-12-23 08:56 UTC, begonaalvarezd requested changes

2024-12-23 08:56 UTC, begonaalvarezd commented on sdk/dapp-kit/src/themes/lightTheme.ts
> +        lineHeight: '24px',
We should add a patch changeset, i'll add it

2024-12-23 09:14 UTC, begonaalvarezd approved these changes

2024-12-23 09:15 UTC, merged