Devx/leap frog nft challenge
iotaledger/iota pull request #4602
Opened 2024-12-23 09:32 UTC by vivekjain23

# Description of change

This PR brings up the changes to add Challenge 0: Mint a Leap Frog NFT.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/4132

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

changes were built locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2025-01-08 09:35 UTC, salaheldinsoliman approved these changes
Looks good 👍 just remove the extra test file

2025-01-08 09:35 UTC, salaheldinsoliman commented on docs/examples/move/ctf/challenge_0/tests/leap_frog.move
There is no need for this one I guess

2025-01-08 12:58 UTC, lucas-tortora requested changes
Please validate that the user inputs a valid IOTA address and connects a wallet if necessary.

![image](https://github.com/user-attachments/assets/093b8f4c-a648-4a8c-b314-f6e1559bd283)

2025-01-09 07:13 UTC, vivekjain23 commented on docs/examples/move/ctf/challenge_0/tests/leap_frog.move
You are right, I removed it.

2025-01-09 13:44 UTC, lucas-tortora approved these changes

2025-01-09 13:44 UTC, lucas-tortora commented on docs/site/src/utils/ctf-utils.ts
> +                                            description: 'An NFT reward is minted to your IOTA wallet address upon completing the challenge.',
```suggestion
                                            description: 'An NFT reward was minted and transferred to your IOTA wallet address for completing the challenge.',
```

2025-01-10 07:59 UTC, merged