feat(wallet-dashboard): show kiosk NFTs
iotaledger/iota pull request #4610
Opened 2024-12-23 16:19 UTC by panteleymonchuk

# Description of change

Depends on: https://github.com/iotaledger/iota/pull/4512

## Links to any relevant issues

fixes #4543

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-07 09:19 UTC, evavirseda requested changes
ci is failing :pray:

2025-01-13 08:55 UTC, cpl121 requested changes

2025-01-13 08:55 UTC, cpl121 commented on apps/wallet-dashboard/components/dialogs/assets/AssetDialog.tsx
> +    const isOwnerToken = isKioskOwnerToken(kioskClient.network, asset);
```suggestion
    const isKioskOwnerToken = isKioskOwnerToken(kioskClient.network, asset);
```

2025-01-13 08:55 UTC, cpl121 commented on apps/wallet-dashboard/components/dialogs/assets/views/DetailsView.tsx
> +import React from 'react';
is this import necessary?

2025-01-13 08:55 UTC, cpl121 commented on apps/wallet-dashboard/components/tiles/AssetTileLink.tsx
> +    const isOwnerToken = isKioskOwnerToken(kioskClient.network, asset);
```suggestion
    const isKioskOwnerToken = isKioskOwnerToken(kioskClient.network, asset);
```

2025-01-13 08:55 UTC, cpl121 commented on apps/core/src/hooks/usePageAssets.ts
> +    );
`useGetNFTs` only receive 2 params
`Expected 0-2 arguments, but got 3.`

2025-01-13 08:55 UTC, cpl121 commented on apps/wallet-dashboard/components/dialogs/assets/views/KioskDetailsView.tsx
> +export function KioskDetailsView({ onClose, asset, onItemClick }: DetailsViewProps) {
When an item is opened from this view, I think the item dialog could have a back button that would return to the kiosk dialog

2025-01-13 09:57 UTC, panteleymonchuk commented on apps/core/src/hooks/usePageAssets.ts
> +    );
It's because of the conflicts, I assume
I'm fixing it

2025-01-13 09:58 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/dialogs/assets/views/DetailsView.tsx
> +import React from 'react';
It was before, now it's not important

2025-01-14 07:51 UTC, cpl121 requested changes

2025-01-14 07:51 UTC, cpl121 commented on apps/core/src/hooks/useTransferKioskItem.tsx
> +            console.log('Transfering object', objectType, to);
:trollface:

2025-01-14 07:51 UTC, cpl121 commented on apps/wallet-dashboard/components/dialogs/assets/AssetDialog.tsx
> +                            onBack={onBack()}
```suggestion
                            onBack={onBack}
```

2025-01-14 07:51 UTC, cpl121 commented on apps/wallet-dashboard/components/dialogs/assets/AssetDialog.tsx
> +        };
```suggestion
            setChoosenKioskAsset(null);
            setView(AssetsDialogView.KioskDetails);
```

2025-01-16 12:04 UTC, cpl121 approved these changes

2025-01-17 14:58 UTC, evavirseda requested changes
conflicts :pray:

2025-01-20 12:13 UTC, evavirseda requested changes
nice job, I just have a suggestion about the ui :pray:

2025-01-20 12:13 UTC, evavirseda commented on apps/wallet-dashboard/components/dialogs/assets/views/KioskDetailsView.tsx
> +            </DialogLayoutFooter>
I'd modify the view a little to keep it consistent with the rest of the views and I've been thinking that something like this could work, wdyt?
```suggestion
            <DialogLayoutBody>
                <div className="flex flex-col gap-md">
                    <div className="flex flex-row gap-x-sm">
                        <span className="text-title-lg text-neutral-10 dark:text-neutral-92">
                            Kiosk items
                        </span>
                        <Badge type={BadgeType.Neutral} label={items?.length.toString() ?? '0'} />
                    </div>
                    <div className="grid grid-cols-3 items-center justify-center gap-sm">
                        {items?.map((item) => {
                            return item.data?.objectId ? (
                                <div
                                    onClick={() => {
                                        item.data && onItemClick(item.data);
                                    }}
                                    key={item.data?.objectId}
                                >
                                    <KioskItem object={item.data} address={senderAddress} />
                                </div>
                            ) : null;
                        })}
                    </div>
                </div>
            </DialogLayoutBody>
            <DialogLayoutFooter>
                <ExplorerLink objectID={objectId} type={ExplorerLinkType.Object}>
                    <ViewTxnOnExplorerButton digest={objectId} />
                </ExplorerLink>
            </DialogLayoutFooter>
```

2025-01-20 13:57 UTC, panteleymonchuk commented on apps/wallet-dashboard/components/dialogs/assets/views/KioskDetailsView.tsx
> +            </DialogLayoutFooter>
sounds good, applied

2025-01-20 14:03 UTC, evavirseda approved these changes

2025-01-20 14:16 UTC, merged