refactor(wallet, explorer, dashboard): change default export for components
iotaledger/iota pull request #4617
Opened 2024-12-24 12:31 UTC by panteleymonchuk

## Links to any relevant issues

Closes #4375

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-24 13:04 UTC, evavirseda requested changes
:pray: :pray:

2024-12-24 13:04 UTC, evavirseda commented on apps/explorer/src/components/header/Header.tsx
> +import { Search } from '../search/Search';
```suggestion
import { Search } from '../search';
```

2024-12-24 13:04 UTC, evavirseda commented on apps/explorer/src/components/layout/PageLayout.tsx
> +import { Header } from '../header/Header';
```suggestion
import { Footer, Header } from '..';
```

2024-12-24 13:04 UTC, evavirseda commented on apps/explorer/src/components/ui/image/Image.tsx
```suggestion
```

2024-12-24 13:04 UTC, evavirseda commented on apps/explorer/src/components/ui/image/Image.tsx
> +import { useImage } from '~/hooks/useImage';
```suggestion
import { useImage } from '~/hooks';
```

2024-12-24 13:04 UTC, evavirseda commented on apps/explorer/src/pages/object-result/ObjectResult.tsx
>  import { TokenView } from './views/TokenView';
can you add an index.ts file to organize these imports? that way, we can simplify them like this:
```suggestion
import { PkgView, TokenView } from './views';
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/components/iota-apps/IotaApp.tsx
```suggestion
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/components/iota-apps/index.tsx
> +export * from './ConnectedAppsCard';
I think it’s a little unusual to have the `AppsPlayGround` function and this export together here, would you mind moving the `AppsPlayGround` function to a separate file? :pray:

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/index.tsx
> +export const App = () => {
```suggestion
export function App() {
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/pages/home/index.tsx
> +export const HomePage = ({ disableNavigation }: HomePageProps) => {
```suggestion
export function HomePage({ disableNavigation }: HomePageProps) {
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
> +import { type InterstitialConfig } from '../interstitial';
```suggestion
import { Interstitial, type InterstitialConfig } from '../interstitial';
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/app/pages/home/tokens/index.tsx
```suggestion
```

2024-12-24 13:04 UTC, evavirseda commented on apps/wallet/src/ui/index.tsx
```suggestion
```

2024-12-26 11:33 UTC, evavirseda approved these changes

2025-01-03 11:12 UTC, VmMad commented
There are some left in `apps/wallet/src/ui/app/hooks/index.ts`

2025-01-03 11:27 UTC, VmMad approved these changes
🚀

2025-01-03 11:28 UTC, merged