feat(wallet-dashboard): fix number of native tokens in migration summary
iotaledger/iota pull request #4619
Opened 2024-12-24 16:21 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4578

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-12-26 17:48 UTC, begonaalvarezd requested changes

2024-12-26 17:48 UTC, begonaalvarezd commented on apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts
>  export function summarizeMigratableObjectValues({
I bet this issue also happens in the unmigratable objects too, so we should replicate the same logic there too 🙏🏼

2024-12-26 17:48 UTC, begonaalvarezd commented on apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts
> +            !uniqueTokens.includes(obj.name)
I think there are be potentially 2 coins with the same name but the type must be different, so we should check against the type, not the name

2024-12-26 17:48 UTC, begonaalvarezd commented on apps/wallet-dashboard/lib/utils/migration/groupStardustObjectsByMigrationStatus.ts
> +            !uniqueTokens.includes(obj.name)
eg 
```ts
export function getUniqueNativeTokensByCoinType(objects: ResolvedObjectTypes[]): number {
    return new Set(
        objects
            .filter((obj) => obj.commonObjectType === CommonMigrationObjectType.NativeToken)
            .map((obj) => obj.coinType),
    ).size;
}
```

2025-01-02 12:18 UTC, VmMad approved these changes, later dismissed

2025-01-08 15:15 UTC, begonaalvarezd approved these changes

2025-01-09 09:14 UTC, VmMad approved these changes
Looks good to me

2025-01-09 09:48 UTC, cpl121 requested changes

2025-01-09 09:48 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/migrations/page.tsx
> +    );
we could do this inside the `getStardustObjectsTotals` function, by this way we would avoid repeating code

2025-01-09 09:54 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/migrations/page.tsx
> +    );
I haven't said anything, we can't add a hook in the function 🤐

2025-01-09 09:54 UTC, cpl121 approved these changes

2025-01-09 09:54 UTC, merged