feat(wallet, dashboard): share useCreateSendAssetTransaction between wallet and dashboard
iotaledger/iota pull request #4630
Opened 2024-12-26 17:27 UTC by panteleymonchuk

## Links to any relevant issues

Closes #4427

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-07 08:58 UTC, evavirseda requested changes
ci is failing :pray:

2025-01-09 08:49 UTC, cpl121 requested changes

2025-01-09 08:49 UTC, cpl121 commented on apps/core/src/types/transactionExecute.ts
> +export type DappKitExecuteFn = (input: {
are we using this?

2025-01-09 08:49 UTC, cpl121 commented on apps/core/src/hooks/useTransferAsset.ts
> +            });
Just as a comment, What do you think about splitting the logic into two separate functions for the direct asset tx and the kiosk tx?

```suggestion
const handleKioskTransfer = async (to: string) => {
    return transferKioskItem.mutateAsync({ to });
};

const handleDirectTransfer = async (to: string) => {
    const tx = new Transaction();
    tx.transferObjects([tx.object(objectId)], to);

    return executeFn!({
        transaction: tx,
        options: {
            showInput: true,
            showEffects: true,
            showEvents: true,
        },
    });
};
return isContainedInKiosk
        ? handleKioskTransfer(to)
        : handleDirectTransfer(to);
```

2025-01-09 08:49 UTC, cpl121 commented on apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
> +            : undefined,
imo, we could add this conditional logic inside the normalize function

2025-01-09 14:24 UTC, panteleymonchuk commented on apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
> +            : undefined,
We can try to do it, but I'm assume we'll lose typescipt autocomplete after. Let me try.

2025-01-10 08:33 UTC, panteleymonchuk commented on apps/core/src/hooks/useTransferAsset.ts
> +            });
On the one hand it's one more layer, on the another it adds more readibility. I'm in.

2025-01-10 08:34 UTC, panteleymonchuk commented on apps/core/src/types/transactionExecute.ts
> +export type DappKitExecuteFn = (input: {
we used in the previous commit. Not now. Nice catch!

2025-01-10 12:17 UTC, cpl121 approved these changes
Perfect!

2025-01-13 08:28 UTC, evavirseda approved these changes

2025-01-13 08:41 UTC, merged