feat(wallet-dashboard): display migration summary in migration confirmation view
iotaledger/iota pull request #4640
Opened 2024-12-30 10:17 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4624

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-02 15:36 UTC, VmMad approved these changes
Looks good to me 💯

2025-01-08 14:07 UTC, cpl121 requested changes
Also, I dont know why, but I cant to migrate because the Migrate button is always loading
![image](https://github.com/user-attachments/assets/7e29b26a-591a-4d53-bd2b-a7a9a67f8a19)

2025-01-08 14:07 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/migration/views/ConfirmMigrationView.tsx
> +import { MigrationObjectDetailsCard } from '@/components/migration/migration-object-details-card';
better import it in `@/components`, right?

2025-01-08 14:07 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/migration/views/ConfirmMigrationView.tsx
> +        },
These assets dont need to be shown, right? They will not be migrated

2025-01-08 15:04 UTC, evavirseda commented
> Also, I dont know why, but I cant to migrate because the Migrate button is always loading ![image](https://private-user-images.githubusercontent.com/100352899/401175135-7e29b26a-591a-4d53-bd2b-a7a9a67f8a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDU4OTksIm5iZiI6MTczNjM0NTU5OSwicGF0aCI6Ii8xMDAzNTI4OTkvNDAxMTc1MTM1LTdlMjliMjZhLTU5MWEtNGQ1My1iZDJiLWE3YTlhNjdmOGExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQxNDEzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGIxNDA5MTVhOWI2MmZmNzJhMDVhMTE5ZjhjMTdiNTUyMzdiY2MxYmI1MTc1ZmRjNjZkNDY4NjVhZDc0M2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KPIt_ZrW_7bHNsgN5MBitQreXiREQU2M_XVdvn-OwRc)

this is not a problem related to this PR, it seems like your profile may be corrupted so try using a different mnemonic :pray:

2025-01-08 18:17 UTC, cpl121 approved these changes

2025-01-08 18:18 UTC, merged