feat(wallet-dashboard): show expiration in migration details
iotaledger/iota pull request #4642
Opened 2024-12-30 12:11 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4625

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-02 15:54 UTC, VmMad requested changes

2025-01-02 15:54 UTC, VmMad commented on apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx
> -    const showLabel = !isFromPreviousEpoch && outputTimestampMs > currentDateMs;
This change makes the logic incorrect, because:
`const outputTimestampMs = isInAFutureEpoch ? unlockConditionTimestampMs : epochEndMs;`
if the unlockConditionTimestampMs is in the past (a past epoch possibly) the timestamp used is the **current epoch timestamp end**, so even expired objects will show a expiration time, when really, they should have expired already

2025-01-02 15:56 UTC, VmMad commented on apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx
> -    const showLabel = !isFromPreviousEpoch && outputTimestampMs > currentDateMs;
This is related to `https://github.com/iotaledger/iota/issues/4369`, where the object could have expired today, but won't really expire until the end of the epoch, that's why that one is used

2025-01-03 10:17 UTC, evavirseda commented on apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx
> -    const showLabel = !isFromPreviousEpoch && outputTimestampMs > currentDateMs;
paused until the rest of the team comes back, and we can discuss it :wink:

2025-01-07 09:29 UTC, cpl121 commented on apps/wallet-dashboard/components/migration/migration-object-details-card/MigrationObjectDetailsCard.tsx
> -    const showLabel = !isFromPreviousEpoch && outputTimestampMs > currentDateMs;
The logic for not showing a label in previous epochs was fine as it was before

2025-01-09 12:38 UTC, cpl121 requested changes

2025-01-09 12:38 UTC, cpl121 commented on apps/wallet-dashboard/lib/utils/migration/groupMigrationObjects.ts
> +    currentEpochStartMs: number,
It is optional, because in case you group by timelockUC, you don't need it
```suggestion
    currentEpochStartMs?: number,
```

2025-01-13 06:49 UTC, cpl121 approved these changes

2025-01-13 16:49 UTC, VmMad approved these changes
nice 🐈

2025-01-13 16:50 UTC, merged