feat(wallet-dashboard): do not allow timelocked staking if there are not enough funds
iotaledger/iota pull request #4645
Opened 2024-12-30 14:57 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4628

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-02 16:36 UTC, VmMad approved these changes

2025-01-09 12:30 UTC, cpl121 requested changes

2025-01-09 12:30 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/vesting/page.tsx
> +        !supplyIncreaseVestingSchedule.totalEarned;
we can migrate this logic to `useGetSupplyIncreaseVestingObjects` hook, and use it in SupplyIncreaseVestingOverview too

2025-01-09 16:27 UTC, cpl121 requested changes

2025-01-09 16:27 UTC, cpl121 commented on apps/wallet-dashboard/app/(protected)/vesting/page.tsx
> +                    {!isSupplyIncreaseVestingScheduleEmpty ? (
```suggestion
                    {isSupplyIncreaseVestingScheduleEmpty ? (
```

2025-01-13 15:44 UTC, cpl121 requested changes

2025-01-13 15:44 UTC, cpl121 commented on apps/wallet-dashboard/components/SupplyIncreaseVestingOverview.tsx
> +    return !isSupplyIncreaseVestingScheduleEmpty ? (
we are missing the staked condition
```suggestion
    return !isSupplyIncreaseVestingScheduleEmpty || supplyIncreaseVestingStakedMapped.length > 0 ? (
```

2025-01-14 08:27 UTC, cpl121 approved these changes

2025-01-14 12:45 UTC, merged