feat(wallet-dashboard): persist selected network
iotaledger/iota pull request #4646
Opened 2024-12-31 10:40 UTC by evavirseda

# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4566

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2025-01-02 10:11 UTC, VmMad approved these changes
LGTM

2025-01-02 10:26 UTC, VmMad requested changes
After further review, I noticed that when reloading, the values are taken from the default initial network, not the one persisted, so you should use the local storage item as the `defaultNetwork` in `apps/wallet-dashboard/providers/AppProviders.tsx`

Example:
```
const [initialNetwork] = useLocalStorage<string>('network_iota-dashboard', defaultNetwork);

    <IotaClientProvider
        networks={allNetworks}
---->   defaultNetwork={initialNetwork}
        onNetworkChange={handleNetworkChange}
    >
```

2025-01-02 10:57 UTC, VmMad approved these changes
💯

2025-01-07 15:39 UTC, cpl121 requested changes

2025-01-07 15:39 UTC, cpl121 commented on apps/core/src/utils/capitalizeFirstLetter.ts
> +    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
```suggestion
    return str.charAt(0).toUpperCase() + str.slice(1);
```

2025-01-07 15:39 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/settings/views/SettingsListView.tsx
> +            subtitle: persistedNetwork,
```suggestion
            subtitle: capitalizeFirstLetter(persistedNetwork),
```

2025-01-07 15:39 UTC, cpl121 commented on apps/wallet-dashboard/components/Dialogs/settings/views/SettingsListView.tsx
> +                                    subtitle={capitalizeFirstLetter(item.subtitle)}
```suggestion
                                    subtitle={item.subtitle}
```

2025-01-07 15:39 UTC, cpl121 commented on apps/wallet-dashboard/hooks/usePersistedNetwork.ts
> +        'network_iota-dashboard',
can we use a constant for this?

2025-01-08 09:17 UTC, cpl121 approved these changes

2025-01-08 09:59 UTC, cpl121 requested changes

2025-01-08 09:59 UTC, cpl121 commented on apps/wallet-dashboard/hooks/usePersistedNetwork.ts
> +    );
there are some errors in the terminal with this hook
`localStorage error ReferenceError: window is not defined`

2025-01-08 10:50 UTC, cpl121 approved these changes

2025-01-08 10:50 UTC, merged