feat(wallet): Add password recovery for seed account source
iotaledger/iota pull request #466
Opened 2024-05-30 12:47 UTC by brancoder

# Description of change

Adds password recovery for accounts derived from Seed Account Source
resolves #460 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

On a locked account enter the forgot password flow

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-03 11:48 UTC, marc2332 requested changes

2024-06-04 10:15 UTC, cpl121 requested changes
I also have a strange flow when I click the `forgot password` button, I getting an error on the input with text `Required` the first time I click on it, but I don't know if it is related to this PR

2024-06-04 16:03 UTC, cpl121 submitted a review, later dismissed

2024-06-07 15:12 UTC, begonaalvarezd requested changes

2024-06-10 14:17 UTC, begonaalvarezd approved these changes

2024-06-10 14:21 UTC, cpl121 approved these changes

2024-06-10 15:02 UTC, marc2332 approved these changes

2024-06-10 15:03 UTC, merged