feat(dashboard): add visual asset logic
iotaledger/iota pull request #470
Opened 2024-05-30 16:08 UTC by cpl121

# Description of change

Add visual asset logic

## Links to any relevant issues

fixes issue #290 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

You have to get NFTs with image, then, go to visual assets page

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-06-07 12:17 UTC, brancoder requested changes
resolve conflicts :pray:

2024-06-10 16:02 UTC, VmMad submitted a review, later dismissed

2024-06-10 16:26 UTC, begonaalvarezd submitted a review, later dismissed

2024-06-10 16:51 UTC, begonaalvarezd approved these changes

2024-06-11 12:28 UTC, brancoder approved these changes
LGTM

2024-06-11 12:38 UTC, merged