Fixed `sui-json-rpc` compilation errors
iotaledger/iota pull request #49
Opened 2024-02-27 14:02 UTC by valeriyr

## Description 

The compilation errors were fixed by adding stubs of the removed dependencies.
The crate can be compiled, and the tests passed.

Fixes #32

2024-02-27 14:30 UTC, kodemartin reviewed
@valeriyr it seems to me that with the `legacy` module we reintroduce a lot of code that we decided to remove, and that we will likely have to remove again soon.

Isn't it possible instead to remove the references to the missing types from the rest of `sui-json-rpc`?

2024-03-01 11:26 UTC, kodemartin requested changes

2024-03-01 15:55 UTC, kodemartin approved these changes

2024-03-04 12:25 UTC, samuel-rufi approved these changes
Great idea to introduce the `StateRead` trait to have some similar functionality as in `StateAuthority`. I guess this `StateRead` trait could also very much be helpful for our `RemoteStorage` implementation.

LGTM.

2024-03-04 12:33 UTC, merged