refactor(explorer): rename interfaces.
iotaledger/iota pull request #529
Opened 2024-06-04 15:58 UTC by panteleymonchuk

# Description of change

Renaming interface to more properly.

## Links to any relevant issues

Fixes #320

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-06-05 06:39 UTC, marc2332 submitted a review, later dismissed

2024-06-05 08:20 UTC, evavirseda requested changes
I think there are still a few things left to update :face_with_peeking_eye: 

- `apps/explorer/src/components/error-boundary/ErrorBoundary.tsx` is unnecessarily exporting the `ErrorBoundaryProps` type
- Same in `apps/explorer/src/components/Layout/PageLayout.tsx`
- Same in `apps/explorer/src/components/module/module-functions-interaction/index.tsx`
- Same in `apps/explorer/src/components/module/module-functions-interaction/LinkGroup.tsx`
- Same in `apps/explorer/src/components/module/module-functions-interaction/ModuleFunction.tsx`
- `apps/explorer/src/components/OwnedCoins/index.tsx`, `apps/explorer/src/components/OwnedObjects/index.tsx,` `apps/explorer/src/components/Table/HighlightedTableCol.tsx`, `apps/explorer/src/components/Table/SuiAmount.tsx`, `apps/explorer/src/components/validator-map/index.tsx`, `apps/explorer/src/components/transactions/TransactionsForAddress.tsx`, `apps/explorer/src/pages/address-result/AddressResult.tsx`, `apps/explorer/src/components/OwnedObjects/ListView.tsx` I think the WhateverProps interface should be added in case we add something additional later on
- `apps/explorer/src/components/OwnedObjects/OwnedObject.tsx` should be renamed to `OwnedObjectProps`
- `apps/explorer/src/components/top-packages/TopPackagesCard.tsx` has types that are unnecessarily exported and others that should be moved to lib/types I think
- `apps/explorer/src/components/validator-map/types.ts`  move the exported ones to the lib/types folder

There would still be files left, but I think that's the idea :pray:

2024-06-05 15:01 UTC, marc2332 submitted a review, later dismissed

2024-06-05 15:37 UTC, evavirseda submitted a review, later dismissed
I think there are still files with props undefined in their own type, but it's ok, I've added them in the PR of the functions when adding the function returns, so all good :+1:

2024-06-10 15:31 UTC, marc2332 submitted a review, later dismissed

2024-06-11 08:00 UTC, evavirseda approved these changes

2024-06-11 08:08 UTC, VmMad approved these changes

2024-06-11 11:33 UTC, marc2332 approved these changes

2024-06-11 11:36 UTC, merged