feat(sui-genesis-builder): Build stardust objects snapshot
iotaledger/iota pull request #535
Opened 2024-06-05 08:43 UTC by miker83z

# Description of change

This PR allows to create a stardust objects snapshot. A main function was created for the `sui-genesis-builder` crate, that takes as input a Hornet snapshot path and produces a compressed stardust objects snapshot in the root folder.

Using a mainnet snapshot with date 03/06/2024 the resulting stardust objects snapshot is 669MB (2.35GB uncompressed).

It uses [brotli](https://lib.rs/crates/brotli) as the lib for compressing the snapshot, it takes around 30 minutes for the compression process in a MacBook Pro (M1 Pro). 

## Links to any relevant issues
Fixes #135 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo run --release --bin sui-genesis-builder -- ../latest-full_snapshot.bin` 

(in `run_migration` in `migration.rs` the line `self.verify_ledger_state(&outputs)?;` was commented out)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2024-06-05 11:25 UTC, samuel-rufi reviewed
LGTM

2024-06-05 15:42 UTC, kodemartin requested changes
Hey @miker83z! Left a couple of suggestions that I reckon can improve the patch.

2024-06-07 08:26 UTC, samuel-rufi requested changes
I think we can't use the `itertools.workspace` dependency at version `0.10.5`. It doesn't seem to provide the API we need in order to run the main (it doesn't compile for me at least). However, when including `itertools` version `0.12.0`, it works.

2024-06-07 16:33 UTC, kodemartin submitted a review, later dismissed

2024-06-07 16:57 UTC, Thoralf-M submitted a review, later dismissed

2024-06-10 06:45 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-10 08:04 UTC, samuel-rufi submitted a review, later dismissed

2024-06-10 09:07 UTC, PhilippGackstatter approved these changes

2024-06-10 09:34 UTC, kodemartin approved these changes

2024-06-10 09:36 UTC, samuel-rufi approved these changes

2024-06-10 09:41 UTC, merged