fix(iota-genesis-builder): Check ownership for all created objects
iotaledger/iota pull request #547
Opened 2024-06-05 12:32 UTC by DaughterOfMars

# Description of change

Not all types were properly validating their ownership. This PR adds a util fn and verifies all ownership. Additionally, it adds missing checks to ensure that no extra objects were created.

## Links to any relevant issues

Closes #540

2024-06-05 16:47 UTC, Thoralf-M submitted a review, later dismissed

2024-06-06 06:53 UTC, Thoralf-M submitted a review, later dismissed

2024-06-06 12:17 UTC, Alex6323 submitted a review, later dismissed

2024-06-06 13:15 UTC, kodemartin requested changes
Some tests are now failing:

```
    stardust::migration::tests::basic::basic_id
    stardust::migration::tests::basic::basic_migration_with_expired_unlock_condition
    stardust::migration::tests::basic::basic_migration_with_unexpired_unlock_condition
```

2024-06-06 14:28 UTC, Thoralf-M approved these changes

2024-06-06 15:20 UTC, kodemartin approved these changes

2024-06-06 16:10 UTC, Alex6323 approved these changes

2024-06-06 18:45 UTC, samuel-rufi approved these changes

2024-06-06 18:49 UTC, merged