refactor(tooling-wallet): Remove Legacy Vault logic
iotaledger/iota pull request #548
Opened 2024-06-05 14:06 UTC by brancoder

# Description of change

- removes legacy vault logic
- leaves in migration logic
resolves #264 

## Type of change

- Refactor

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-06 16:13 UTC, cpl121 requested changes
Also, when building the wallet and trying to open the extension app, it stays on this screen but I don't get any errors when inspecting the console. Does it happen to you?
![Captura de pantalla de 2024-06-06 18-11-51](https://github.com/iotaledger/iota/assets/100352899/90e8836c-52d5-48d6-945b-9f1470a3b60a)

2024-06-07 11:35 UTC, cpl121 submitted a review, later dismissed
Perfect!!

2024-06-07 14:31 UTC, begonaalvarezd requested changes

2024-06-10 16:44 UTC, begonaalvarezd approved these changes

2024-06-11 07:20 UTC, cpl121 approved these changes
Perfect 👏🏼

2024-06-11 07:21 UTC, merged