feat(iota-genesis-builder): Labeled TimeLocks integration
iotaledger/iota pull request #572
Opened 2024-06-06 13:02 UTC by valeriyr

# Description of change

Integrated labeled timelocks into:
- `iota-types`
- `iota-genesis-builder`
- `iota-indexer`
-  `iota-json-rpc-types` and `iota-json-rpc`

## Links to any relevant issues

fixes #443

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Auto tests

2024-06-06 13:46 UTC, kodemartin requested changes
Hey @valeriyr! Looks good in general. Left only a comment that should be trivial to address.

2024-06-07 07:49 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-07 08:33 UTC, samuel-rufi submitted a review, later dismissed

2024-06-07 08:47 UTC, kodemartin submitted a review, later dismissed

2024-06-07 09:15 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-07 09:22 UTC, PhilippGackstatter approved these changes

2024-06-07 09:38 UTC, kodemartin approved these changes

2024-06-07 09:40 UTC, merged