refactor(wallet): revert "refactor(wallet): Remove kiosk (#419)"
iotaledger/iota pull request #589
Opened 2024-06-06 15:59 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/582
Reverts https://github.com/iotaledger/iota/pull/419

2024-06-10 07:39 UTC, cpl121 requested changes

2024-06-10 08:20 UTC, cpl121 requested changes

2024-06-10 15:16 UTC, cpl121 approved these changes

2024-06-11 07:54 UTC, begonaalvarezd requested changes
Requesting changes just because I would like to review it myself too 🙏🏼 will do asap

2024-06-11 13:28 UTC, begonaalvarezd approved these changes

2024-06-11 13:29 UTC, merged