feat(iota-framework/stardust): make stardust models are generic
iotaledger/iota pull request #619
Opened 2024-06-10 13:36 UTC by Dkwcs

Stardust models have turned into generic
Rename iota variables to more general - "balance"

# Description of change

Stardust models(especially outputs) have generic balance field in order to apply not only IOTA coin.

## Links to any relevant issues

Fixes #577 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected) **possibly**? 

## How the change has been tested

Run existing unit tests for iota/crates/iota-framework/packages/stardust

2024-06-10 14:13 UTC, valeriyr requested changes
Hey @Dkwcs! Looks good in general!
I left several minor comments related to code simplification. Also, it is necessary to check and fix the documentation comments after changing IOTA to a generic type.

2024-06-10 16:21 UTC, lzpap approved these changes
LGTM

2024-06-11 08:47 UTC, kodemartin approved these changes
LGTM

2024-06-11 09:04 UTC, valeriyr approved these changes

2024-06-11 09:35 UTC, merged