feat(docs): Add IOTA EVM content
iotaledger/iota pull request #626
Opened 2024-06-10 23:17 UTC by jlvandenhout

⚠️ BASED ON #932 ⚠️ 

# Description of change

Copy over ISC content from the legacy Wiki and rename it to IOTA EVM to not conflict with Move smart contracts.

- As IOTA Smart Contracts as a name won't cut it now that we will have L1 smart contracts too, it felt appropriate to rename ISC to IOTA EVM and IOTA EVM Smart Contracts in this PR, to distinguish it from our L1 Move smart contracts.
- Only content from the legacy Build and Maintain sections are copied over. Learn section content will be done in a different PR.
- Legacy Build content went into the `developer` section, legacy Maintain content went into `operator`, any API references went into the `references` section.
- The reference generation script was adjusted to the new layout.

## Links to any relevant issues

fixes issue iotaledger/devx#400

## Type of change

- Documentation Fix

## How the change has been tested

Local docs build.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

2024-07-08 13:41 UTC, Dr-Electron requested changes

2024-07-10 21:26 UTC, Dr-Electron submitted a review, later dismissed

2024-07-11 12:33 UTC, lucas-tortora requested changes
The EVM content gets lost or mixed up with the move content. What do you think about something moving it up one level and changing up the labels a bit? Something like Move Guides and EVM Guides, for example,

2024-07-16 12:02 UTC, lucas-tortora submitted a review, later dismissed

2024-07-18 11:53 UTC, fijter submitted a review, later dismissed
Good initial content to have, I would just merge this one in and improve it over time. We should have a separate issue and PR to remove the Wasm related stuff given thats no longer relevant/supported. (Anything Wasm mentioning, and the complete Schema tool section).

2024-07-18 12:33 UTC, Dr-Electron submitted a review, later dismissed

2024-07-18 14:30 UTC, fijter approved these changes

2024-07-18 14:37 UTC, Dr-Electron approved these changes

2024-07-18 15:29 UTC, begonaalvarezd approved these changes

2024-07-18 15:36 UTC, merged