feat(iota-genesis-builder): Add migration documentation
iotaledger/iota pull request #649
Opened 2024-06-12 09:21 UTC by PhilippGackstatter

# Description of change

Add documentation for the migration on all objects (not just native tokens).

The goal was a mid-level overview without describing ever possible edge case of native token id derivation and IRC-XY metadata extraction.

Let me know if anything important is missing or if some parts are superfluous.

Docusaurus setup was tested.

## Links to any relevant issues

fixes #164

2024-06-14 13:22 UTC, lucas-tortora requested changes
Just a few suggestions. We should use absolute links for the repo links if they're outside the `docs` folder.

2024-06-14 15:26 UTC, samuel-rufi requested changes

2024-06-18 14:17 UTC, lucas-tortora requested changes

2024-06-18 14:36 UTC, lucas-tortora submitted a review, later dismissed

2024-06-18 16:31 UTC, Thoralf-M approved these changes

2024-06-18 17:31 UTC, lucas-tortora approved these changes

2024-06-19 11:03 UTC, samuel-rufi approved these changes

2024-06-19 11:09 UTC, merged