feat(iota-framework):define the smr token in iota framework
iotaledger/iota pull request #665
Opened 2024-06-12 11:46 UTC by Dkwcs

# Description of change

Defining Shimmer token with an appropriate supply corresponds the [TIP0032](https://wiki.iota.org/tips/tips/TIP-0032/)

## Links to any relevant issues

Fixes #573 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

2024-06-12 12:11 UTC, valeriyr requested changes

2024-06-12 16:11 UTC, miker83z requested changes

2024-06-13 07:20 UTC, miker83z submitted a review, later dismissed

2024-06-13 07:42 UTC, valeriyr requested changes

2024-06-13 08:40 UTC, valeriyr submitted a review, later dismissed

2024-06-13 11:32 UTC, fijter submitted a review, later dismissed
Looks good, the `increase_supply` thing should be doublechecked though :)

2024-06-13 12:36 UTC, fijter submitted a review, later dismissed

2024-06-13 14:00 UTC, valeriyr submitted a review, later dismissed

2024-06-13 14:32 UTC, fijter submitted a review, later dismissed

2024-06-13 15:00 UTC, valeriyr submitted a review, later dismissed

2024-06-13 15:11 UTC, miker83z submitted a review, later dismissed

2024-06-13 22:25 UTC, merged