feat(iota-genesis-builder): Integrate `CoinManager`
iotaledger/iota pull request #673
Opened 2024-06-12 13:07 UTC by samuel-rufi

# Description of change

This PR adapts the package template, migration and verification logic to work with the `CoinManager`. In addition, a corresponding  `CoinManager` type in `iota_types` is introduced for deserialization. The `CappedCoin` module is deleted.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/193

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo test` in the the iota-genesis-builder.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

2024-06-13 09:35 UTC, fijter submitted a review, later dismissed
Great work Samuel! Someone else should have a good look at the Rust code but the Move part is implemented as expected and according to the needs 👍

2024-06-14 16:10 UTC, miker83z requested changes
Great work Sam! I just left a suggestion to improve the new `iota_types` coming out from the CoinManager.

2024-06-17 13:15 UTC, kodemartin reviewed
LGTM with minor comments.

2024-06-17 19:55 UTC, miker83z approved these changes

2024-06-18 06:48 UTC, kodemartin approved these changes

2024-06-18 08:49 UTC, merged