feat(iota-framework, iota-genesis-builder): make stardust output models generic
iotaledger/iota pull request #681
Opened 2024-06-12 15:10 UTC by Dkwcs

# Description of change

#### Rust: 
Tag function has additional argument type_param: TypeTag
iota-genesis-builder tests are fixed.
Some minor variables renaming(iota to balance)

#### Move:
Stardust models have turned into generic
Rename iota variables to more general - "balance"

## Links to any relevant issues

Fixes #577 and #610 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

#### Rust:
Run existing unit tests for iota-genesis-builder

#### Move:
Run existing unit tests for iota/crates/iota-framework/packages/stardust

2024-06-12 15:12 UTC, kodemartin submitted a review, later dismissed

2024-06-13 08:55 UTC, samuel-rufi submitted a review, later dismissed

2024-06-13 09:10 UTC, kodemartin requested changes
@Dkwcs it doesn't build. Some refactoring leftovers I guess:

```sh
$ cargo test -j2 -p iota-genesis-builder
   Compiling iota-framework v0.1.0 (/home/kodemartin/projects/kinesis/crates/iota-framework)
   Compiling iota-config v0.0.0 (/home/kodemartin/projects/kinesis/crates/iota-config)
   Compiling iota-framework-snapshot v0.1.0 (/home/kodemartin/projects/kinesis/crates/iota-framework-snapshot)
   Compiling iota-genesis-builder v0.0.0 (/home/kodemartin/projects/kinesis/crates/iota-genesis-builder)
error[E0609]: no field `iota` on type `stardust::types::alias::AliasOutput`
  --> crates/iota-genesis-builder/src/stardust/migration/verification/alias.rs:95:36
   |
95 |     *total_value += created_output.iota.value();
   |                                    ^^^^ unknown field
   |
   = note: available fields are: `id`, `balance`, `native_tokens`

error[E0609]: no field `iota` on type `stardust::types::output::BasicOutput`
   --> crates/iota-genesis-builder/src/stardust/migration/verification/basic.rs:125:40
    |
125 |         *total_value += created_output.iota.value();
    |                                        ^^^^ unknown field
    |
    = note: available fields are: `id`, `balance`, `native_tokens`, `storage_deposit_return`, `timelock` ... and 4 others

error[E0609]: no field `iota` on type `stardust::types::nft::NftOutput`
  --> crates/iota-genesis-builder/src/stardust/migration/verification/nft.rs:96:36
   |
96 |     *total_value += created_output.iota.value();
   |                                    ^^^^ unknown field
   |
   = note: available fields are: `id`, `balance`, `native_tokens`, `storage_deposit_return`, `timelock`, `expiration`
```

2024-06-13 09:54 UTC, kodemartin approved these changes

2024-06-13 09:59 UTC, samuel-rufi approved these changes

2024-06-13 10:43 UTC, lzpap approved these changes

2024-06-13 11:20 UTC, merged