feat(iota-genesis-builder): add migration tests for outputs with multiple native tokens
iotaledger/iota pull request #684
Opened 2024-06-13 07:44 UTC by Alex6323

## Links to any relevant issues

Closes #554

2024-06-13 15:10 UTC, Thoralf-M submitted a review, later dismissed

2024-06-17 12:51 UTC, kodemartin requested changes
Looks great but requires a refactoring to account for the salting added in `develop`:

```
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> crates/iota-genesis-builder/src/stardust/migration/tests/basic.rs:145:25
    |
145 |     let mut migration = Migration::new(1, 1_000_000).unwrap();
    |                         ^^^^^^^^^^^^^^-------------- an argument of type `migration_target_network::MigrationTargetNetwork` is missing
    |
note: associated function defined here
   --> crates/iota-genesis-builder/src/stardust/migration/migration.rs:73:12
    |
73  |     pub fn new(
    |            ^^^
74  |         target_milestone_timestamp_sec: u32,
    |         -----------------------------------
75  |         total_supply: u64,
    |         -----------------
76  |         target_network: MigrationTargetNetwork,
    |         --------------------------------------
help: provide the argument
    |
145 |     let mut migration = Migration::new(1, 1_000_000, /* migration_target_network::MigrationTargetNetwork */).unwrap();
```

2024-06-19 20:42 UTC, Thoralf-M submitted a review, later dismissed

2024-06-20 05:54 UTC, kodemartin submitted a review, later dismissed

2024-06-24 07:37 UTC, Thoralf-M submitted a review, later dismissed

2024-06-24 12:38 UTC, lzpap submitted a review, later dismissed

2024-06-24 13:36 UTC, samuel-rufi submitted a review, later dismissed

2024-06-24 13:39 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-25 12:16 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-25 12:56 UTC, Thoralf-M submitted a review, later dismissed

2024-06-25 13:11 UTC, lzpap submitted a review, later dismissed

2024-06-25 13:39 UTC, miker83z submitted a review, later dismissed

2024-06-25 15:19 UTC, lucas-tortora approved these changes

2024-06-25 16:48 UTC, Thoralf-M approved these changes

2024-06-25 19:52 UTC, DaughterOfMars approved these changes

2024-06-26 15:31 UTC, miker83z approved these changes

2024-06-26 15:50 UTC, merged