refactor(wallet,wallet-dashboard): add shared `useBalance` hook
iotaledger/iota pull request #688
Opened 2024-06-13 10:52 UTC by brancoder

# Description of change

Add shared `useBalance` hook to apps/core
resolves #666 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-13 12:07 UTC, msarcev reviewed
I would avoid using non-null asserts (`!`) when passing parameters. We already fought with lint in multiple places to remove those.

2024-06-13 14:04 UTC, marc2332 submitted a review, later dismissed

2024-06-17 16:27 UTC, begonaalvarezd requested changes

2024-06-18 07:44 UTC, begonaalvarezd approved these changes

2024-06-18 08:10 UTC, msarcev approved these changes

2024-06-18 08:12 UTC, merged