feat(iota-genesis-builder): Add salting parameter
iotaledger/iota pull request #692
Opened 2024-06-13 13:02 UTC by PhilippGackstatter

# Description of change

Add salting parameter as a cli option.

This means one needs to specify the target network of the migration as a second parameter on the cli:

`cargo run --package iota-genesis-builder -- latest_snapshot.bin mainnet`
or
`cargo run --package iota-genesis-builder -- latest_snapshot.bin testnet`
or
`cargo run --package iota-genesis-builder -- latest_snapshot.bin alphanet`
or
`cargo run --package iota-genesis-builder -- latest_snapshot.bin testnet-optional-other-string`
or
`cargo run --package iota-genesis-builder -- latest_snapshot.bin alphanet-optional-other-string`

This will result in different migration transaction contexts which in turn will ensure different `ObjectDigest`s of all objects created by the migration.

If, for some reason, more target networks are required they can be easily added.

## Links to any relevant issues

fixes #483

2024-06-13 13:53 UTC, valeriyr submitted a review, later dismissed
Looks good to me :+1:

2024-06-13 16:55 UTC, miker83z requested changes

2024-06-14 10:48 UTC, miker83z approved these changes
Great! LGTM!

2024-06-14 10:54 UTC, valeriyr approved these changes

2024-06-14 10:57 UTC, merged