fix(iota-genesis-builder): verify stardust genesis snapshot
iotaledger/iota pull request #693
Opened 2024-06-13 13:13 UTC by Alex6323

## Links to any relevant issues

Closes #107

2024-06-13 16:37 UTC, miker83z requested changes
I suggest to check just some naming/merge issues, all the rest LGTM!

2024-06-14 13:01 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-14 16:35 UTC, miker83z submitted a review, later dismissed
Great addition!

2024-06-17 12:34 UTC, kodemartin requested changes
Requires a small fix in `src/main.rs`

2024-06-20 11:34 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-20 13:15 UTC, Thoralf-M submitted a review, later dismissed

2024-06-20 13:33 UTC, kodemartin submitted a review, later dismissed

2024-06-20 20:46 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-21 08:48 UTC, Thoralf-M submitted a review, later dismissed

2024-06-21 09:47 UTC, kodemartin submitted a review, later dismissed

2024-06-24 07:31 UTC, Thoralf-M submitted a review, later dismissed

2024-06-24 12:37 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-24 12:40 UTC, lzpap submitted a review, later dismissed

2024-06-25 10:35 UTC, samuel-rufi submitted a review, later dismissed

2024-06-25 13:37 UTC, miker83z submitted a review, later dismissed

2024-06-25 18:48 UTC, Thoralf-M submitted a review, later dismissed

2024-06-25 19:53 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-26 16:54 UTC, miker83z approved these changes

2024-06-26 17:04 UTC, DaughterOfMars approved these changes

2024-06-26 17:05 UTC, merged