fix(docs): Fix the interactive examples
iotaledger/iota pull request #710
Opened 2024-06-14 13:53 UTC by marc2332

Closes #709 

- Add the docs site to the pnpm workspace
- Remove annoying zksend hook from the dapp-kit
- Update reactr from 18.2.0 to 18.3.1 in all the monorepo packages
- Clean up the interactive example code

2024-06-24 10:30 UTC, Dr-Electron reviewed
Seems like good changes, but if I run
pnpm install
pnpm build

It doesn't build. Am I doing something wrong?
```sh
[ERROR] Client bundle compiled with errors therefore further build is impossible.
Module not found: Error: Can't resolve '@iota/dapp-kit' in '/iota/docs/site/src/components/sdk-examples'

--------------------------

Module not found: Error: Can't resolve '@iota/iota.js/client' in '/iota/docs/site/src/components/sdk-examples'

--------------------------

Module not found: Error: Can't resolve '@iota/dapp-kit/dist/index.css' in '/iota/docs/site/src/components/sdk-examples'
 ELIFECYCLE  Command failed with exit code 1.
```

2024-06-24 16:54 UTC, begonaalvarezd requested changes
im testing running a fresh clone and installing the dependencies before building the documentation and im getting a crash trying to build eg the wallet-dashboard (to build de dapp-kit and the sdk with it) 

```
@iota/build-scripts:build: src/build-dapp-kit.ts(16,38): error TS2321: Excessive stack depth comparing types '(typeof autoprefixer | ((root: Root_) => void))[]' and 'AcceptedPlugin[] | undefined'.
@iota/build-scripts:build: src/build-dapp-kit.ts(16,38): error TS2769: No overload matches this call.
@iota/build-scripts:build:   Overload 1 of 2, '(plugins?: AcceptedPlugin[] | undefined): Processor_', gave the following error.
@iota/build-scripts:build:     Type '(root: Root_) => void' is not assignable to type 'AcceptedPlugin'.
@iota/build-scripts:build:       Type '(root: Root_) => void' is missing the following properties from type 'OldPlugin<any>': postcss, postcssPlugin, postcssVersion
@iota/build-scripts:build:   Overload 2 of 2, '(...plugins: AcceptedPlugin[]): Processor_', gave the following error.
@iota/build-scripts:build:     Argument of type '(typeof autoprefixer | ((root: Root_) => void))[]' is not assignable to parameter of type 'AcceptedPlugin'.
@iota/build-scripts:build:  ELIFECYCLE  Command failed with exit code 1.
@iota/build-scripts:build: ERROR: command finished with error: command (/iota/sdk/build-scripts) pnpm run build exited (1)
command (/iota/sdk/build-scripts) pnpm run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.448s
Failed:    @iota/build-scripts#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

2024-06-25 10:35 UTC, begonaalvarezd approved these changes

2024-06-25 13:30 UTC, Dr-Electron approved these changes
LGTM. I used node 22 and it didn't work. With 20 it works. Thanks for your help

2024-06-25 13:32 UTC, merged