feat(tooling-dashboard): add send asset popup
iotaledger/iota pull request #717
Opened 2024-06-14 15:47 UTC by VmMad

# Description of change

Create a popup to send assets (only UI)

## Links to any relevant issues

Fixes #295 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How to Test

1. Download the mint_nft move package from the resources repo.
2. Build and publish the package.
3. Mint your own nft.
4. Use one of these visual assets to test for the sending asset flow

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-17 08:53 UTC, cpl121 requested changes

2024-06-18 10:12 UTC, evavirseda requested changes

2024-06-21 07:40 UTC, marc2332 requested changes

2024-06-21 10:55 UTC, marc2332 requested changes

2024-06-24 10:31 UTC, evavirseda submitted a review, later dismissed
LGTM

2024-06-25 07:07 UTC, evavirseda submitted a review, later dismissed

2024-06-26 08:14 UTC, evavirseda submitted a review, later dismissed

2024-06-26 09:18 UTC, cpl121 requested changes

2024-06-26 11:24 UTC, evavirseda submitted a review, later dismissed

2024-06-26 11:24 UTC, cpl121 submitted a review, later dismissed

2024-06-27 06:45 UTC, marc2332 requested changes
the rest lgtm

2024-06-27 08:47 UTC, marc2332 approved these changes

2024-06-27 08:47 UTC, cpl121 approved these changes

2024-06-27 08:48 UTC, evavirseda approved these changes

2024-06-27 08:48 UTC, merged