refactor(iota-genesis-builder, iota-types): move stardust types from iota-genesis-builder to iota-types
iotaledger/iota pull request #735
Opened 2024-06-17 11:28 UTC by Dkwcs

Move stardust types from iota-genesis-builder to iota-types 
Imports fixes

# Description of change

Moving stardust types from iota-genesis-builder to iota-types with appropriate refactoring.

## Links to any relevant issues

Fixes #192 .

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Run iota-genesis-builder tests
Run iota_types tests

2024-06-17 13:18 UTC, DaughterOfMars requested changes
Merge conflicts

2024-06-17 13:54 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-17 14:22 UTC, Thoralf-M submitted a review, later dismissed

2024-06-18 09:06 UTC, Thoralf-M submitted a review, later dismissed

2024-06-18 12:21 UTC, DaughterOfMars submitted a review, later dismissed

2024-06-18 12:41 UTC, Thoralf-M submitted a review, later dismissed

2024-06-19 07:32 UTC, kodemartin requested changes
Hey @Dkwcs it looks good in general. I left a few minor suggestions for refactoring/structure reorganization that I think would help improve the refactoring.

2024-06-21 10:58 UTC, kodemartin submitted a review, later dismissed
LGTM @Dkwcs ! Thanks for the changes.

Note that tests in `iota-types` fail with the `--all-targets` flat. Not relevant to this patch, but we should track this. Could you create an issue?

2024-06-21 11:17 UTC, Thoralf-M submitted a review, later dismissed

2024-06-21 11:19 UTC, valeriyr requested changes

2024-06-21 11:43 UTC, valeriyr approved these changes

2024-06-21 11:44 UTC, Thoralf-M approved these changes

2024-06-21 11:47 UTC, kodemartin approved these changes

2024-06-21 11:53 UTC, merged