Chore: Add renaming script
iotaledger/iota pull request #75
Opened 2024-03-07 15:19 UTC by fijter

# Description of change

This PR adds a script that allows you to batch rename all references from SUI to IOTA. 

## Links to any relevant issues

should be used as a part to address issue #9 

## Type of change

## How the change has been tested

Ran against the SUI Repo latest, no errors and builds successfully. 

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-03-08 09:41 UTC, kodemartin requested changes
Hey @dave, good job! I have a few suggestions for improvements:

* I suggest nesting the script and its requirements in a `script/rename_to_iota` folder, and also add a README there on how to setup the requirements, and run the script.
* You can optionally consider using regular expressions to limit matches of the terms we want to replace in word boundaries with the `\b` character (see [more](https://docs.python.org/3/library/re.html#regular-expression-syntax)). This will eliminate the need for maintaining a manually curated list of what terms to exclude from replacement. See also more specific comment below.
* You can also consider using [GitPython](https://gitpython.readthedocs.io/en/stable/index.html). This can be useful in multiple ways:
   * Go through files only tracked by git through, similarly to `git ls-files`. This will eliminate the need to parse `.gitignore` in order to exclude ti.
   * But most importantly to `git mv <old-file/folder> <renamed-file/folder`, that adds the changes directly to the index. This is a better alternative to renaming through the filesystem, that requires additional git manual operations.

2024-03-08 14:16 UTC, kodemartin approved these changes

2024-03-11 09:43 UTC, samuel-rufi approved these changes
Great work Dave!

2024-03-11 10:57 UTC, valeriyr approved these changes
Great script!

2024-03-14 11:40 UTC, merged