feat(wallet): Add account finder to manage accounts view
iotaledger/iota pull request #775
Opened 2024-06-20 13:23 UTC by brancoder

# Description of change

Adds search button to each account source in manage accounts
resoves #724 

~~depends on #759~~

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-21 11:23 UTC, evavirseda submitted a review, later dismissed
Gut gemacht :rocket:

2024-06-25 11:32 UTC, evavirseda submitted a review, later dismissed

2024-06-25 14:44 UTC, begonaalvarezd requested changes

2024-06-28 10:34 UTC, marc2332 requested changes

2024-07-02 08:31 UTC, marc2332 approved these changes

2024-07-03 07:01 UTC, begonaalvarezd approved these changes

2024-07-03 07:01 UTC, merged