refactor(move-execution, iota-execution): remove v0, v1, v2 versions of iota-execution and move-execution
iotaledger/iota pull request #781
Opened 2024-06-21 07:48 UTC by Dkwcs

# Description of change

Removing obsolete v0, v1, v2 versions of iota-execution and move-execution
These versions are removing because they are outdated for IOTA and will never be used
Making a new cut of latest version (new v0)

The cut from the `latest` created by running appropriate command in the root of repo: `./scripts/execution_layer.py` cut v0

Snapshot testing/regenerating:

```
cargo insta test -p iota-cost --review
cargo insta test -p iota-config --review
cargo insta test -p iota-protocol-config --review
```

## Links to any relevant issues

fixes #671 and #674 .

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Run build and tests for iota-execution.
Run build and tests for external-crates/move

2024-06-21 08:22 UTC, valeriyr submitted a review, later dismissed

2024-06-24 16:03 UTC, miker83z requested changes
Looks good in general, just a couple of issues left to deal with!

2024-06-25 07:28 UTC, miker83z submitted a review, later dismissed
LGTM!

2024-06-25 08:14 UTC, miker83z submitted a review, later dismissed

2024-06-26 10:34 UTC, kodemartin submitted a review, later dismissed
lgtm

2024-06-26 11:01 UTC, miker83z submitted a review, later dismissed

2024-06-26 15:35 UTC, miker83z approved these changes

2024-06-26 15:39 UTC, kodemartin approved these changes

2024-06-26 15:42 UTC, merged