refactor(sdk): Remove deepbook
iotaledger/iota pull request #784
Opened 2024-06-21 09:45 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/731

2024-06-26 08:45 UTC, begonaalvarezd approved these changes

2024-06-26 09:48 UTC, cpl121 requested changes
There are still some documentation references about `deepbook` in the docs folder that I think should be deleted
- `docs/content/standards.mdx`
- `docs/content/concepts/versioning.mdx`
- `docs/content/guides/developer/iotat-101/using-events.mdx`
- `docs/content/references/cli/ptb.mdx`
and more

2024-06-26 11:32 UTC, cpl121 approved these changes

2024-06-28 13:53 UTC, fijter approved these changes
less is more 👍

2024-06-28 14:25 UTC, merged