refactor(sdk): Move Kiosk package IDs to `IOTA_NETWORKS` env var
iotaledger/iota pull request #791
Opened 2024-06-21 14:08 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/787

2024-06-26 09:54 UTC, cpl121 requested changes
We would have to update `apps/core/src/utils/kiosk.ts` too, right?

2024-06-26 11:13 UTC, begonaalvarezd submitted a review, later dismissed

2024-06-28 11:54 UTC, cpl121 approved these changes

2024-07-01 07:12 UTC, begonaalvarezd submitted a review, later dismissed

2024-07-01 07:14 UTC, VmMad approved these changes

2024-07-01 09:06 UTC, merged