feat(iota-genesis-builder): add test outputs owned by aliases
iotaledger/iota pull request #797
Opened 2024-06-24 08:17 UTC by Alex6323

# Description of change

Adds test outputs owned by alias outputs.

Tested with:
```sh
cargo run --release --example snapshot_test_outputs --features="test-outputs" iota-latest-full_snapshot.bin
```

## Links to any relevant issues

#752

2024-07-02 12:09 UTC, Thoralf-M submitted a review, later dismissed

2024-07-02 12:21 UTC, thibault-martinez requested changes
Preventing merge as I have a doubt about something, will think about it later today.

2024-07-02 18:53 UTC, Thoralf-M submitted a review, later dismissed

2024-07-03 08:25 UTC, Thoralf-M submitted a review, later dismissed

2024-07-03 10:34 UTC, Thoralf-M submitted a review, later dismissed

2024-07-03 17:14 UTC, Thoralf-M submitted a review, later dismissed

2024-07-05 11:53 UTC, DaughterOfMars submitted a review, later dismissed

2024-07-05 14:08 UTC, kodemartin submitted a review, later dismissed

2024-07-05 14:19 UTC, thibault-martinez submitted a review, later dismissed

2024-07-08 08:09 UTC, Thoralf-M approved these changes

2024-07-08 08:19 UTC, thibault-martinez approved these changes

2024-07-08 11:49 UTC, kodemartin approved these changes

2024-07-08 11:52 UTC, merged