feat(wallet): Hook Account Finder
iotaledger/iota pull request #829
Opened 2024-06-26 10:48 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/825
~~DEPENDS ON THIS PULL REQUEST ------>> https://github.com/iotaledger/iota/pull/762~~

2024-07-03 09:35 UTC, begonaalvarezd approved these changes

2024-07-03 09:36 UTC, begonaalvarezd submitted a review, later dismissed

2024-07-03 10:03 UTC, cpl121 requested changes

2024-07-03 13:07 UTC, begonaalvarezd submitted a review, later dismissed

2024-07-03 15:07 UTC, cpl121 submitted a review, later dismissed
Amazing 👏🏼

2024-07-03 15:18 UTC, cpl121 approved these changes

2024-07-04 14:45 UTC, panteleymonchuk approved these changes

2024-07-05 07:07 UTC, merged