feat(wallet-dashboard): add send asset logic
iotaledger/iota pull request #830
Opened 2024-06-26 11:50 UTC by VmMad

# Description of change

We needed to be able to send assets from the dashboard. This is a PR to accomplish that. 

## Links to any relevant issues

Closes #296 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

- Mint an NFT
- Connect your wallet to the dashboard
- Click on send asset

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-06-27 11:44 UTC, evavirseda submitted a review, later dismissed

2024-07-01 11:50 UTC, cpl121 requested changes
Conflicts too 🙏🏼

2024-07-01 15:22 UTC, marc2332 submitted a review, later dismissed

2024-07-02 05:38 UTC, cpl121 approved these changes

2024-07-02 14:36 UTC, marc2332 approved these changes

2024-07-03 10:01 UTC, merged