fix(iota-types): Update total supply const and rename Micros to Nanos
iotaledger/iota pull request #859
Opened 2024-06-27 13:57 UTC by DaughterOfMars

# Description of change

This fixes the disparity between the const definitions between `iota.move` and `iota-types` `TOTAL_SUPPLY_IOTA`, and renames Micros to Nanos. I also removed a duplicate const from `iota-genesis-builder`.

## Links to any relevant issues

Closes #856

2024-06-27 13:59 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-27 14:21 UTC, Thoralf-M submitted a review, later dismissed

2024-06-27 14:37 UTC, samuel-rufi submitted a review, later dismissed

2024-06-27 14:39 UTC, PhilippGackstatter submitted a review, later dismissed

2024-06-27 14:46 UTC, kodemartin requested changes
Looks good, only a minor issue for restoring the `iota-genesis-builder` example assertions.

2024-06-27 16:43 UTC, kodemartin submitted a review, later dismissed

2024-06-27 17:29 UTC, miker83z submitted a review, later dismissed
Looks good! Just left some comments to open a new isue and maybe implement a minor change.

2024-06-28 07:13 UTC, lzpap submitted a review, later dismissed

2024-06-28 07:37 UTC, samuel-rufi submitted a review, later dismissed

2024-06-28 08:15 UTC, miker83z submitted a review, later dismissed

2024-06-28 09:57 UTC, Thoralf-M approved these changes

2024-06-28 10:16 UTC, lzpap approved these changes

2024-06-28 12:51 UTC, kodemartin approved these changes

2024-06-28 13:03 UTC, merged