feat(new-layout): Update doc style
iotaledger/iota pull request #916
Opened 2024-07-01 07:16 UTC by vivekjain23

### This PR brings the changes of the new [FIgma](https://www.figma.com/design/vHZqM5G4oeXwNuJRUyxePw/IOTA-Wiki-2.0?node-id=1-2&t=9TKVDkwtD5dZTfXk-0) design layout of our documentation and also contains the fixes of the [PR](https://github.com/iotaledger/iota/pull/841).

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-07-01 13:38 UTC, lucas-tortora requested changes
See https://github.com/iotaledger/iota/pull/916#issuecomment-2200181441 for details. 

Please update the PR title as this is not really a fix

2024-07-03 14:04 UTC, lucas-tortora submitted a review, later dismissed

2024-07-03 15:07 UTC, Dr-Electron requested changes
Landing page looks nice. It is not really responsive tho. On mobile it will be hard to read the text if the background images don't scale

Also where the swizzles save? If not I would not swizzle components just for the design.
In general I think we should now swizzle just for design if there is no strong opinions. Because swizzling always lead to issues in the past.
And we don't have to 100% stick to what design gives us.

So I would try to figure out that we really need to swizzle.
Btw if you swizzle something always add the reason for swizzling and the version you swizzled as a comment on top of the page like we do in the wiki

Also there is some issues in light mode.
<img width="332" alt="navbutton_light" src="https://github.com/iotaledger/iota/assets/61637085/d6856205-d495-48e7-9933-74198bbcf9d6">

The theme switcher is missing on the landing page

2024-07-08 12:31 UTC, lucas-tortora submitted a review, later dismissed

2024-07-08 14:07 UTC, Dr-Electron approved these changes
Let's merge and iterate 👍 Looks great with the new landing page

2024-07-08 14:10 UTC, lucas-tortora approved these changes

2024-07-08 14:46 UTC, merged