feat(tooling-ui): add configs necessary for the package
iotaledger/iota pull request #953
Opened 2024-07-02 15:08 UTC by VmMad

# Description of change

Adds config for tailwind and modify package.json "exports" field 

## Links to any relevant issues

Fixes #870 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

1. `pnpm i`
2. `pnpm run build`
3. Change the name in the package.json
4. `npm publish --access=public`

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-07-05 07:42 UTC, brancoder submitted a review, later dismissed
LGTM

2024-07-05 14:02 UTC, marc2332 submitted a review, later dismissed

2024-07-05 14:03 UTC, brancoder submitted a review, later dismissed

2024-07-06 15:31 UTC, begonaalvarezd requested changes
the turborepo CI is failing 🙏🏼

2024-07-08 13:28 UTC, brancoder submitted a review, later dismissed
LGTM

2024-07-08 13:35 UTC, evavirseda requested changes

2024-07-08 14:53 UTC, evavirseda approved these changes

2024-07-08 16:08 UTC, begonaalvarezd approved these changes

2024-07-08 16:09 UTC, merged