feat(sc-platform): Introduce validator target reward with minting and burning
iotaledger/iota pull request #971
Opened 2024-07-03 11:22 UTC by PhilippGackstatter

# Description of change

Introduce validator target reward which, compared with the computation reward, determines whether IOTA tokens are minted or burned. The computation reward is the total number of fees paid in the epoch for transaction execution. If the fees are lower than the target reward, additional tokens are minted. If the fee is higher, tokens are burned. At the end of this process, this always results in `validator_target_reward` amount of IOTA tokens which are distributed to the validators.

Additional noteworthy changes:
- Disable the IOTA conservation check in the `AuthorityStore`, which checks that the number of tokens stays constant over time. I have created another issue (#1017) to deal with this check properly later, see also inline comments.
- Disable the IOTA conservation check of the execution engine, not only for genesis transactions but also for epoch change transactions, which now may change the total IOTA supply. Other transactions are still not allowed to modify the total IOTA supply.

## Links to any relevant issues

fixes #945
fixes #947
fixes #949 

## How the change has been tested

- `iota-test-validator` successfully starts and successfully runs across epoch boundaries (where `advance_epoch` is called and rewards are distributed).
- Test in `crates/iota-framework/packages/iota-system/` pass.

2024-07-03 15:54 UTC, Dkwcs approved these changes

2024-07-04 16:15 UTC, valeriyr requested changes
@PhilippGackstatter, I left several questions/suggestions in the PR but great job overall!

2024-07-05 11:30 UTC, valeriyr approved these changes
LGTM!

2024-07-08 12:49 UTC, miker83z approved these changes
LGTM!

2024-07-08 13:11 UTC, merged