fix(iota): Fix and improve fullnode and faucet configuration for `test-validator`
iotaledger/iota pull request #973
Opened 2024-07-03 11:27 UTC by marc2332

Closes https://github.com/iotaledger/iota/issues/968

1. Actually pass correctly the configured IP of the fullnode to the swarm builder
2. Allow passing custom hosts (ips) for both the faucet and fullnode (optional, default will be `127.0.0.1` for both)

2024-07-04 06:57 UTC, Thoralf-M submitted a review, later dismissed

2024-07-04 07:49 UTC, samuel-rufi submitted a review, later dismissed

2024-07-09 08:54 UTC, kodemartin requested changes
Hey @marc2332, looks good. Made a suggestion to eliminate the possibility of panics due conflicting configurations in the callers of `test-cluster`.

2024-07-09 13:46 UTC, kodemartin approved these changes

2024-07-09 14:13 UTC, Thoralf-M approved these changes

2024-07-10 11:44 UTC, merged