refactor(external-crates): apply clippy
iotaledger/iota pull request #990
Opened 2024-07-04 10:15 UTC by Thoralf-M

# Description of change

Apply clippy suggestions

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`cargo ci-clippy-external`

2024-07-05 07:34 UTC, thibault-martinez submitted a review, later dismissed

2024-07-05 12:04 UTC, DaughterOfMars requested changes
error: unknown lint: `clippy::duplicated_attributes`
  --> crates/iota-graphql-rpc/src/types/move_object.rs:53:9
   |
53 | #[allow(clippy::duplicated_attributes)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::allow_attributes`
   |
   = note: `-D unknown-lints` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unknown_lints)]`

2024-07-08 12:19 UTC, DaughterOfMars submitted a review, later dismissed

2024-07-08 15:35 UTC, thibault-martinez submitted a review, later dismissed

2024-07-08 15:54 UTC, DaughterOfMars approved these changes

2024-07-08 15:55 UTC, DaughterOfMars requested changes
error: unknown lint: `clippy::duplicated_attributes`
   --> crates/iota-graphql-rpc/src/types/object.rs:230:9
    |
230 | #[allow(clippy::duplicated_attributes)]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::allow_attributes`

2024-07-08 16:00 UTC, DaughterOfMars submitted a review, later dismissed

2024-07-09 07:35 UTC, thibault-martinez submitted a review, later dismissed

2024-07-09 08:02 UTC, samuel-rufi submitted a review, later dismissed

2024-07-09 16:00 UTC, thibault-martinez approved these changes

2024-07-09 18:44 UTC, DaughterOfMars approved these changes

2024-07-10 12:19 UTC, miker83z approved these changes

2024-07-10 12:20 UTC, kodemartin approved these changes

2024-07-10 12:20 UTC, merged